/**
 * Seed dataset for Nabd Healthcare.
 * Real Saudi-localized data for pharmacies, doctors, delivery drivers, and medicines.
 */
export const SEED_USERS = [
  // Test patient
  { kind: 'patient', full_name: 'أحمد السالم', phone: '+966509999999', password: 'Test@123', city: 'الرياض', district: 'العليا' },
];

export const SEED_PHARMACIES = [
  {
    full_name: 'صيدلية النهدي — العليا', phone: '+966555000001', password: 'Pharm@123',
    name_ar: 'صيدلية النهدي', name_en: 'Al-Nahdi Pharmacy', pharmacy_chain: 'Al Nahdi',
    city: 'الرياض', district: 'العليا', location: { lat: 24.7136, lng: 46.6753 },
    has_own_drivers: true, delivery_radius_km: 12, rating: 4.7,
    working_hours: [
      { day: 'sat', open: '08:00', close: '23:00' },
      { day: 'sun', open: '08:00', close: '23:00' },
      { day: 'mon', open: '08:00', close: '23:00' },
      { day: 'tue', open: '08:00', close: '23:00' },
      { day: 'wed', open: '08:00', close: '23:00' },
      { day: 'thu', open: '08:00', close: '23:00' },
      { day: 'fri', open: '14:00', close: '23:00' },
    ],
  },
  {
    full_name: 'صيدلية الدواء — الملقا', phone: '+966555000002', password: 'Pharm@123',
    name_ar: 'صيدلية الدواء', name_en: 'Al-Dawaa Pharmacy', pharmacy_chain: 'Al Dawaa',
    city: 'الرياض', district: 'الملقا', location: { lat: 24.7741, lng: 46.7385 },
    has_own_drivers: false, delivery_radius_km: 10, rating: 4.5,
    working_hours: [{ day: 'all', open: '09:00', close: '00:00' }],
  },
  {
    full_name: 'صيدلية الحياة — الربوة', phone: '+966555000003', password: 'Pharm@123',
    name_ar: 'صيدلية الحياة', name_en: 'Life Pharmacy', pharmacy_chain: '',
    city: 'الرياض', district: 'الربوة', location: { lat: 24.6973, lng: 46.7280 },
    has_own_drivers: true, delivery_radius_km: 8, rating: 4.3,
    working_hours: [{ day: 'all', open: '08:00', close: '23:00' }],
  },
];

/**
 * Standard weekly hours used by most doctors. Each doctor can override.
 * day ∈ sat..fri; open/close = 'HH:MM'.
 */
const STD_HOURS = [
  { day: 'sat', open: '09:00', close: '21:00' },
  { day: 'sun', open: '09:00', close: '21:00' },
  { day: 'mon', open: '09:00', close: '21:00' },
  { day: 'tue', open: '09:00', close: '21:00' },
  { day: 'wed', open: '09:00', close: '21:00' },
  { day: 'thu', open: '09:00', close: '17:00' },
  { day: 'fri', open: '16:00', close: '21:00' },
];
const MORNING_HOURS = [
  { day: 'sat', open: '09:00', close: '14:00' },
  { day: 'sun', open: '09:00', close: '14:00' },
  { day: 'mon', open: '09:00', close: '14:00' },
  { day: 'tue', open: '09:00', close: '14:00' },
  { day: 'wed', open: '09:00', close: '14:00' },
  { day: 'thu', open: '09:00', close: '14:00' },
  { day: 'fri', open: '00:00', close: '00:00', closed: true },
];
const EVENING_HOURS = [
  { day: 'sat', open: '16:00', close: '23:00' },
  { day: 'sun', open: '16:00', close: '23:00' },
  { day: 'mon', open: '16:00', close: '23:00' },
  { day: 'tue', open: '16:00', close: '23:00' },
  { day: 'wed', open: '16:00', close: '23:00' },
  { day: 'thu', open: '16:00', close: '23:00' },
  { day: 'fri', open: '17:00', close: '23:00' },
];

export const SEED_DOCTORS = [
  // 1
  { full_name: 'د. سعد القحطاني', phone: '+966544000001', password: 'Doctor@123',
    name_ar: 'د. سعد القحطاني', name_en: 'Dr. Saad Al-Qahtani',
    specialty: 'باطنة', title: 'د.', license_number: 'KSA-MED-12345', years_experience: 12,
    academic_degree: 'consultant', facility_slug: 'king-faisal-specialist',
    city: 'الرياض', district: 'العليا', hospital: 'مستشفى الملك فيصل التخصصي',
    location: { lat: 24.7142, lng: 46.6859 },
    consultation_modes: ['clinic', 'video', 'home'],
    price_clinic: 250, price_online: 150, price_home: 400, rating: 4.8, working_hours: STD_HOURS,
    bio: 'استشاري الباطنة العامة بخبرة 12 عاماً في تشخيص وعلاج أمراض الجهاز الهضمي والسكري والضغط.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf', 'walaa'] },
  // 2
  { full_name: 'د. فاطمة الجبر', phone: '+966544000002', password: 'Doctor@123',
    name_ar: 'د. فاطمة الجبر', name_en: 'Dr. Fatima Al-Jabr',
    specialty: 'أطفال', title: 'د.', license_number: 'KSA-MED-23456', years_experience: 9,
    academic_degree: 'consultant', facility_slug: 'dallah-hospital',
    city: 'الرياض', district: 'النخيل', hospital: 'مستشفى دله',
    location: { lat: 24.7762, lng: 46.6378 },
    consultation_modes: ['clinic', 'video'],
    price_clinic: 300, price_online: 180, rating: 4.9, working_hours: MORNING_HOURS,
    bio: 'استشارية طب الأطفال متخصصة في الرضع وحديثي الولادة والتطعيمات.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf', 'rajhi_takaful', 'walaa'] },
  // 3
  { full_name: 'د. خالد العتيبي', phone: '+966544000003', password: 'Doctor@123',
    name_ar: 'د. خالد العتيبي', name_en: 'Dr. Khalid Al-Otaibi',
    specialty: 'جلدية', title: 'د.', license_number: 'KSA-MED-34567', years_experience: 7,
    academic_degree: 'specialist', facility_slug: 'andalusia-clinic',
    city: 'الرياض', district: 'الياسمين', hospital: 'مجمع الأندلسية الطبي',
    location: { lat: 24.8245, lng: 46.6712 },
    consultation_modes: ['clinic', 'video'],
    price_clinic: 200, price_online: 120, rating: 4.6, working_hours: EVENING_HOURS,
    bio: 'متخصص في علاج حب الشباب، الإكزيما، الصدفية، وعلاجات تجميلية بالليزر.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['tawuniya', 'rajhi_takaful', 'malath'] },
  // 4
  { full_name: 'د. نورة السبيعي', phone: '+966544000004', password: 'Doctor@123',
    name_ar: 'د. نورة السبيعي', name_en: 'Dr. Noura Al-Subaie',
    specialty: 'نساء وولادة', title: 'د.', license_number: 'KSA-MED-44444', years_experience: 14,
    academic_degree: 'professor', facility_slug: 'dallah-hospital',
    city: 'الرياض', district: 'النخيل', hospital: 'مستشفى دله',
    location: { lat: 24.7762, lng: 46.6378 },
    consultation_modes: ['clinic', 'video'],
    price_clinic: 350, price_online: 200, rating: 4.9, working_hours: STD_HOURS,
    bio: 'أستاذة وأستشارية أمراض النساء والولادة، خبرة 14 عاماً في متابعة الحمل والولادات.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf', 'walaa', 'arabian_shield'] },
  // 5
  { full_name: 'د. عبدالله الحربي', phone: '+966544000005', password: 'Doctor@123',
    name_ar: 'د. عبدالله الحربي', name_en: 'Dr. Abdullah Al-Harbi',
    specialty: 'قلب وأوعية', title: 'د.', license_number: 'KSA-MED-55555', years_experience: 18,
    academic_degree: 'professor', facility_slug: 'prince-sultan-cardiac',
    city: 'الرياض', district: 'العليا', hospital: 'مركز الأمير سلطان للقلب',
    location: { lat: 24.7218, lng: 46.6754 },
    consultation_modes: ['clinic', 'video', 'home'],
    price_clinic: 450, price_online: 250, price_home: 700, rating: 4.9, working_hours: STD_HOURS,
    bio: 'أستاذ وأستشاري أمراض القلب والقسطرة العلاجية. زميل الكلية الملكية البريطانية.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf', 'walaa', 'malath', 'salama'] },
  // 6
  { full_name: 'د. منى الفهد', phone: '+966544000006', password: 'Doctor@123',
    name_ar: 'د. منى الفهد', name_en: 'Dr. Mona Al-Fahad',
    specialty: 'أسنان', title: 'د.', license_number: 'KSA-DEN-66666', years_experience: 8,
    academic_degree: 'specialist', facility_slug: 'andalusia-clinic',
    city: 'الرياض', district: 'الياسمين', hospital: 'مجمع الأندلسية الطبي',
    location: { lat: 24.8245, lng: 46.6712 },
    consultation_modes: ['clinic'],
    price_clinic: 180, rating: 4.7, working_hours: MORNING_HOURS,
    bio: 'تجميل الأسنان، تركيبات الزيركون، تبييض الأسنان، وعلاجات اللثة.',
    languages: ['ar', 'en'],
    accepts_insurance: false, accepted_insurance: [] },
  // 7
  { full_name: 'د. أحمد الزهراني', phone: '+966544000007', password: 'Doctor@123',
    name_ar: 'د. أحمد الزهراني', name_en: 'Dr. Ahmed Al-Zahrani',
    specialty: 'عظام', title: 'د.', license_number: 'KSA-MED-77777', years_experience: 11,
    academic_degree: 'consultant', facility_slug: 'saudi-german-hospital',
    city: 'الرياض', district: 'الربوة', hospital: 'مستشفى السعودي الألماني',
    location: { lat: 24.7488, lng: 46.7227 },
    consultation_modes: ['clinic', 'home'],
    price_clinic: 280, price_home: 500, rating: 4.5, working_hours: STD_HOURS,
    bio: 'استشاري جراحة العظام والكسور والمفاصل، متخصص في إصابات الملاعب.',
    languages: ['ar'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf', 'gulf_union'] },
  // 8
  { full_name: 'د. ريم الدوسري', phone: '+966544000008', password: 'Doctor@123',
    name_ar: 'د. ريم الدوسري', name_en: 'Dr. Reem Al-Dossari',
    specialty: 'نفسي', title: 'د.', license_number: 'KSA-MED-88888', years_experience: 10,
    academic_degree: 'consultant', facility_slug: null,
    city: 'الرياض', district: 'الياسمين', hospital: 'عيادات الصحة النفسية',
    location: { lat: 24.8201, lng: 46.6488 },
    consultation_modes: ['video', 'clinic'],
    price_clinic: 320, price_online: 220, rating: 4.8, working_hours: EVENING_HOURS,
    bio: 'استشارية الطب النفسي للبالغين، علاج القلق والاكتئاب واضطرابات النوم.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya'] },
  // 9
  { full_name: 'د. ياسر الشمري', phone: '+966544000009', password: 'Doctor@123',
    name_ar: 'د. ياسر الشمري', name_en: 'Dr. Yasser Al-Shammari',
    specialty: 'أنف وأذن وحنجرة', title: 'د.', license_number: 'KSA-MED-99999', years_experience: 9,
    academic_degree: 'senior_specialist', facility_slug: 'kingdom-hospital',
    city: 'الرياض', district: 'العليا', hospital: 'مستشفى المملكة',
    location: { lat: 24.7045, lng: 46.6816 },
    consultation_modes: ['clinic', 'video'],
    price_clinic: 230, price_online: 140, rating: 4.6, working_hours: STD_HOURS,
    bio: 'أخصائي أول أنف وأذن وحنجرة، عمليات الجيوب الأنفية والتهابات الأذن المزمنة.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf_a', 'walaa', 'allianz'] },
  // 10
  { full_name: 'د. سارة المطيري', phone: '+966544000010', password: 'Doctor@123',
    name_ar: 'د. سارة المطيري', name_en: 'Dr. Sarah Al-Mutairi',
    specialty: 'عيون', title: 'د.', license_number: 'KSA-MED-10101', years_experience: 6,
    academic_degree: 'specialist', facility_slug: 'kingdom-hospital',
    city: 'الرياض', district: 'العليا', hospital: 'مستشفى المملكة',
    location: { lat: 24.7045, lng: 46.6816 },
    consultation_modes: ['clinic'],
    price_clinic: 270, rating: 4.7, working_hours: STD_HOURS,
    bio: 'فحص النظر، علاج جفاف العين، عمليات الليزك وتصحيح النظر.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'walaa', 'globemed'] },
  // 11
  { full_name: 'د. ماجد الغامدي', phone: '+966544000011', password: 'Doctor@123',
    name_ar: 'د. ماجد الغامدي', name_en: 'Dr. Majed Al-Ghamdi',
    specialty: 'مخ وأعصاب', title: 'د.', license_number: 'KSA-MED-11111', years_experience: 16,
    academic_degree: 'professor', facility_slug: 'king-faisal-specialist',
    city: 'الرياض', district: 'العليا', hospital: 'مستشفى الملك فيصل التخصصي',
    location: { lat: 24.7142, lng: 46.6859 },
    consultation_modes: ['clinic', 'video'],
    price_clinic: 400, price_online: 240, rating: 4.8, working_hours: STD_HOURS,
    bio: 'أستاذ وأستشاري المخ والأعصاب، تشخيص الصرع، الصداع النصفي، التصلب اللويحي.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf', 'axa', 'walaa'] },
  // 12
  { full_name: 'د. هند الرشيد', phone: '+966544000012', password: 'Doctor@123',
    name_ar: 'د. هند الرشيد', name_en: 'Dr. Hind Al-Rasheed',
    specialty: 'تغذية', title: 'د.', license_number: 'KSA-NUT-12121', years_experience: 5,
    academic_degree: 'specialist', facility_slug: 'andalusia-clinic',
    city: 'الرياض', district: 'النرجس', hospital: 'مجمع الأندلسية الطبي',
    location: { lat: 24.8245, lng: 46.6712 },
    consultation_modes: ['video', 'home'],
    price_online: 150, price_home: 350, rating: 4.7, working_hours: EVENING_HOURS,
    bio: 'أخصائية تغذية علاجية، برامج تخسيس صحية، تغذية مرضى السكري والكلى.',
    languages: ['ar', 'en'],
    accepts_insurance: false, accepted_insurance: [] },
  // 13
  { full_name: 'د. تركي العنزي', phone: '+966544000013', password: 'Doctor@123',
    name_ar: 'د. تركي العنزي', name_en: 'Dr. Turki Al-Anzi',
    specialty: 'مسالك بولية', title: 'د.', license_number: 'KSA-MED-13131', years_experience: 13,
    academic_degree: 'consultant', facility_slug: 'saudi-german-hospital',
    city: 'الرياض', district: 'الربوة', hospital: 'مستشفى السعودي الألماني',
    location: { lat: 24.7488, lng: 46.7227 },
    consultation_modes: ['clinic', 'video'],
    price_clinic: 320, price_online: 200, rating: 4.7, working_hours: STD_HOURS,
    bio: 'استشاري المسالك البولية، حصوات الكلى، تضخم البروستاتا.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf', 'arabian_shield'] },
  // 14
  { full_name: 'د. لمى الخالدي', phone: '+966544000014', password: 'Doctor@123',
    name_ar: 'د. لمى الخالدي', name_en: 'Dr. Lama Al-Khaledi',
    specialty: 'سكر وغدد', title: 'د.', license_number: 'KSA-MED-14141', years_experience: 11,
    academic_degree: 'consultant', facility_slug: 'king-faisal-specialist',
    city: 'الرياض', district: 'العليا', hospital: 'مستشفى الملك فيصل التخصصي',
    location: { lat: 24.7142, lng: 46.6859 },
    consultation_modes: ['clinic', 'video'],
    price_clinic: 340, price_online: 210, rating: 4.8, working_hours: STD_HOURS,
    bio: 'استشارية السكري والغدد الصماء، علاج اضطرابات الغدة الدرقية والهرمونات.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf', 'walaa', 'nextcare'] },
  // 15
  { full_name: 'د. فهد البلوي', phone: '+966544000015', password: 'Doctor@123',
    name_ar: 'د. فهد البلوي', name_en: 'Dr. Fahad Al-Balawi',
    specialty: 'علاج طبيعي', title: 'د.', license_number: 'KSA-PT-15151', years_experience: 6,
    academic_degree: 'specialist', facility_slug: null,
    city: 'الرياض', district: 'النرجس', hospital: 'مركز العلاج الطبيعي',
    location: { lat: 24.8401, lng: 46.6315 },
    consultation_modes: ['clinic', 'home'],
    price_clinic: 200, price_home: 380, rating: 4.6, working_hours: STD_HOURS,
    bio: 'أخصائي علاج طبيعي، تأهيل الإصابات الرياضية، إعادة تأهيل بعد الجراحة.',
    languages: ['ar'],
    accepts_insurance: true, accepted_insurance: ['tawuniya', 'walaa', 'malath'] },
  // 16
  { full_name: 'د. عائشة الزهراني', phone: '+966544000016', password: 'Doctor@123',
    name_ar: 'د. عائشة الزهراني', name_en: 'Dr. Aisha Al-Zahrani',
    specialty: 'طب الأسرة', title: 'د.', license_number: 'KSA-FM-16161', years_experience: 8,
    academic_degree: 'specialist', facility_slug: 'andalusia-clinic',
    city: 'الرياض', district: 'الياسمين', hospital: 'مجمع الأندلسية الطبي',
    location: { lat: 24.8245, lng: 46.6712 },
    consultation_modes: ['clinic', 'video', 'home'],
    price_clinic: 180, price_online: 100, price_home: 350, rating: 4.7, working_hours: STD_HOURS,
    bio: 'أخصائية طب الأسرة، الكشف الدوري، متابعة الأمراض المزمنة.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['tawuniya', 'rajhi_takaful', 'walaa', 'malath', 'salama'] },
  // 17
  { full_name: 'د. ناصر الدوسري', phone: '+966544000017', password: 'Doctor@123',
    name_ar: 'د. ناصر الدوسري', name_en: 'Dr. Nasser Al-Dossari',
    specialty: 'جراحة عامة', title: 'د.', license_number: 'KSA-SURG-17171', years_experience: 17,
    academic_degree: 'professor', facility_slug: 'saudi-german-hospital',
    city: 'الرياض', district: 'الربوة', hospital: 'مستشفى السعودي الألماني',
    location: { lat: 24.7488, lng: 46.7227 },
    consultation_modes: ['clinic'],
    price_clinic: 420, rating: 4.7, working_hours: STD_HOURS,
    bio: 'أستاذ وأستشاري الجراحة العامة، جراحات المرارة والفتق والمناظير.',
    languages: ['ar', 'en'],
    accepts_insurance: true, accepted_insurance: ['bupa', 'tawuniya', 'medgulf', 'arabian_shield'] },
];

export const SEED_DELIVERY = [
  { full_name: 'محمد الأحمدي (سائق توصيل)', phone: '+966577000001', password: 'Driver@123', city: 'الرياض' },
  { full_name: 'علي الشمري (سائق توصيل)', phone: '+966577000002', password: 'Driver@123', city: 'الرياض' },
];

export const SEED_MEDICINES = [
  { name_ar: 'بنادول 500مغ', name_en: 'Panadol 500mg', active_ingredient: 'Paracetamol', price: 12, category: 'medications', verified: true, manufacturer: 'GSK', requires_prescription: false },
  { name_ar: 'بروفين 400مغ', name_en: 'Brufen 400mg', active_ingredient: 'Ibuprofen', price: 18, category: 'medications', verified: true, manufacturer: 'Abbott', requires_prescription: false },
  { name_ar: 'فلاجيل 500مغ', name_en: 'Flagyl 500mg', active_ingredient: 'Metronidazole', price: 22, category: 'medications', verified: true, manufacturer: 'Sanofi', requires_prescription: true },
  { name_ar: 'أوجمنتين 625مغ', name_en: 'Augmentin 625mg', active_ingredient: 'Amoxicillin+Clavulanate', price: 45, category: 'medications', verified: true, manufacturer: 'GSK', requires_prescription: true },
  { name_ar: 'فيتامين D3 5000IU', name_en: 'Vitamin D3 5000IU', active_ingredient: 'Cholecalciferol', price: 35, category: 'vitamins', verified: true, manufacturer: 'Now', requires_prescription: false },
  { name_ar: 'لوستا 50مغ', name_en: 'Losta 50mg', active_ingredient: 'Losartan', price: 28, category: 'medications', verified: true, manufacturer: 'Sanofi', requires_prescription: true },
  { name_ar: 'غلوكوفاج 850مغ', name_en: 'Glucophage 850mg', active_ingredient: 'Metformin', price: 32, category: 'medications', verified: true, manufacturer: 'Merck', requires_prescription: true },
  { name_ar: 'سيتالوبرام 10مغ', name_en: 'Cipralex 10mg', active_ingredient: 'Escitalopram', price: 65, category: 'medications', verified: true, manufacturer: 'Lundbeck', requires_prescription: true },
  { name_ar: 'أوميغا 3 السمك', name_en: 'Omega 3 Fish Oil', active_ingredient: 'EPA+DHA', price: 55, category: 'vitamins', verified: true, manufacturer: 'Nordic Naturals' },
  { name_ar: 'حديد فيروفول', name_en: 'Ferrofol Iron', active_ingredient: 'Iron+Folic acid', price: 25, category: 'vitamins', verified: true, manufacturer: 'JPI' },
  { name_ar: 'بنادريل شراب أطفال', name_en: 'Panadrex Kids Syrup', active_ingredient: 'Paracetamol', price: 19, category: 'medications', verified: true, manufacturer: 'GSK' },
  { name_ar: 'مومي بوكو شراب', name_en: 'Mucosolvan Syrup', active_ingredient: 'Ambroxol', price: 27, category: 'medications', verified: true, manufacturer: 'Boehringer' },
  { name_ar: 'كريم مرطب فيشي', name_en: 'Vichy Hydrating Cream', active_ingredient: 'Thermal water', price: 95, category: 'skincare', verified: true, manufacturer: 'Vichy' },
  { name_ar: 'واقي شمس SPF50', name_en: 'Sunscreen SPF50', active_ingredient: '—', price: 110, category: 'skincare', verified: true, manufacturer: 'La Roche-Posay' },
  { name_ar: 'حفاضات بامبرز مقاس 4', name_en: 'Pampers Size 4', active_ingredient: '—', price: 65, category: 'baby', verified: true, manufacturer: 'P&G' },
  { name_ar: 'حليب أطفال S-26', name_en: 'S-26 Infant Formula', active_ingredient: '—', price: 88, category: 'baby', verified: true, manufacturer: 'Wyeth' },
  { name_ar: 'فرشاة أسنان أورال بي', name_en: 'Oral-B Brush', active_ingredient: '—', price: 18, category: 'personal_care', verified: true, manufacturer: 'P&G' },
  { name_ar: 'معجون أسنان سنسوداين', name_en: 'Sensodyne Toothpaste', active_ingredient: 'Potassium nitrate', price: 22, category: 'personal_care', verified: true, manufacturer: 'GSK' },
  { name_ar: 'متر سكر Accu-Chek', name_en: 'Accu-Chek Glucose Meter', active_ingredient: '—', price: 240, category: 'medical_devices', verified: true, manufacturer: 'Roche' },
  { name_ar: 'جهاز ضغط أومرون', name_en: 'Omron BP Monitor', active_ingredient: '—', price: 320, category: 'medical_devices', verified: true, manufacturer: 'Omron' },
  { name_ar: 'فولتارين جل', name_en: 'Voltaren Gel', active_ingredient: 'Diclofenac', price: 32, category: 'medications', verified: true, manufacturer: 'Novartis' },
  { name_ar: 'بردي 100', name_en: 'Bardez 100mg', active_ingredient: 'Sertraline', price: 70, category: 'medications', verified: true, manufacturer: 'Pfizer', requires_prescription: true },
  { name_ar: 'كرستور 5مغ', name_en: 'Crestor 5mg', active_ingredient: 'Rosuvastatin', price: 95, category: 'medications', verified: true, manufacturer: 'AstraZeneca', requires_prescription: true },
  { name_ar: 'كونكور 5مغ', name_en: 'Concor 5mg', active_ingredient: 'Bisoprolol', price: 38, category: 'medications', verified: true, manufacturer: 'Merck', requires_prescription: true },
  { name_ar: 'لاوبرول 30', name_en: 'Lansoprazole 30mg', active_ingredient: 'Lansoprazole', price: 42, category: 'medications', verified: true, manufacturer: 'Takeda' },
  // Analgesics & antipyretics
  { name_ar: 'كتافلام 50مغ', name_en: 'Cataflam 50mg', active_ingredient: 'Diclofenac', price: 24, category: 'medications', verified: true, manufacturer: 'Novartis', requires_prescription: false },
  { name_ar: 'أدول 500مغ', name_en: 'Adol 500mg', active_ingredient: 'Paracetamol', price: 9, category: 'medications', verified: true, manufacturer: 'JPI', requires_prescription: false },
  { name_ar: 'أسبرين 81مغ', name_en: 'Aspirin 81mg', active_ingredient: 'Acetylsalicylic acid', price: 14, category: 'medications', verified: true, manufacturer: 'Bayer', requires_prescription: false },
  { name_ar: 'ميجراليف', name_en: 'Migralief', active_ingredient: 'Paracetamol+Caffeine', price: 16, category: 'medications', verified: true, manufacturer: 'GSK', requires_prescription: false },
  { name_ar: 'سيتامول 500مغ', name_en: 'Setamol 500mg', active_ingredient: 'Paracetamol', price: 8, category: 'medications', verified: true, manufacturer: 'JPI', requires_prescription: false },
  // Antibiotics
  { name_ar: 'كلاسيد 500مغ', name_en: 'Klacid 500mg', active_ingredient: 'Clarithromycin', price: 78, category: 'medications', verified: true, manufacturer: 'Abbott', requires_prescription: true },
  { name_ar: 'سيبتاي 500مغ', name_en: 'Septaze 500mg', active_ingredient: 'Sulfamethoxazole+Trimethoprim', price: 38, category: 'medications', verified: true, manufacturer: 'Roche', requires_prescription: true },
  { name_ar: 'أزيثرومايسين 500مغ', name_en: 'Zithromax 500mg', active_ingredient: 'Azithromycin', price: 52, category: 'medications', verified: true, manufacturer: 'Pfizer', requires_prescription: true },
  { name_ar: 'سيفلكسين 500مغ', name_en: 'Keflex 500mg', active_ingredient: 'Cephalexin', price: 45, category: 'medications', verified: true, manufacturer: 'Lilly', requires_prescription: true },
  { name_ar: 'سيبروفلوكساسين 500مغ', name_en: 'Ciprofloxacin 500mg', active_ingredient: 'Ciprofloxacin', price: 36, category: 'medications', verified: true, manufacturer: 'Bayer', requires_prescription: true },
  // Antihistamines / cold & flu
  { name_ar: 'كلاريتين', name_en: 'Claritin', active_ingredient: 'Loratadine', price: 28, category: 'medications', verified: true, manufacturer: 'Bayer', requires_prescription: false },
  { name_ar: 'زيرتك', name_en: 'Zyrtec', active_ingredient: 'Cetirizine', price: 32, category: 'medications', verified: true, manufacturer: 'UCB', requires_prescription: false },
  { name_ar: 'كومتركس', name_en: 'Comtrex Cold', active_ingredient: 'Paracetamol+Pseudoephedrine', price: 26, category: 'medications', verified: true, manufacturer: 'Novartis', requires_prescription: false },
  { name_ar: 'ريفوكسي', name_en: 'Rivoxy', active_ingredient: 'Oxymetazoline', price: 20, category: 'medications', verified: true, manufacturer: 'Bayer', requires_prescription: false },
  { name_ar: 'فينترن 4مغ', name_en: 'Polaramine 4mg', active_ingredient: 'Dexchlorpheniramine', price: 18, category: 'medications', verified: true, manufacturer: 'MSD' },
  // GI / Acid
  { name_ar: 'أوميبرازول 20مغ', name_en: 'Omeprazole 20mg', active_ingredient: 'Omeprazole', price: 24, category: 'medications', verified: true, manufacturer: 'Sandoz' },
  { name_ar: 'نيكسيوم 40مغ', name_en: 'Nexium 40mg', active_ingredient: 'Esomeprazole', price: 88, category: 'medications', verified: true, manufacturer: 'AstraZeneca' },
  { name_ar: 'موتيليوم', name_en: 'Motilium', active_ingredient: 'Domperidone', price: 30, category: 'medications', verified: true, manufacturer: 'Janssen' },
  { name_ar: 'بوسكوبان', name_en: 'Buscopan', active_ingredient: 'Hyoscine butylbromide', price: 22, category: 'medications', verified: true, manufacturer: 'Boehringer' },
  { name_ar: 'إيموديوم', name_en: 'Imodium', active_ingredient: 'Loperamide', price: 26, category: 'medications', verified: true, manufacturer: 'Janssen' },
  // Diabetes & Endocrine
  { name_ar: 'جانوفيا 100مغ', name_en: 'Januvia 100mg', active_ingredient: 'Sitagliptin', price: 290, category: 'medications', verified: true, manufacturer: 'MSD', requires_prescription: true },
  { name_ar: 'لانتوس قلم', name_en: 'Lantus SoloStar', active_ingredient: 'Insulin Glargine', price: 180, category: 'medications', verified: true, manufacturer: 'Sanofi', requires_prescription: true, cold_chain: true },
  { name_ar: 'يوثيروكس 100', name_en: 'Euthyrox 100', active_ingredient: 'Levothyroxine', price: 18, category: 'medications', verified: true, manufacturer: 'Merck', requires_prescription: true },
  // Cardio / Hypertension
  { name_ar: 'كوزار 50مغ', name_en: 'Cozaar 50mg', active_ingredient: 'Losartan', price: 70, category: 'medications', verified: true, manufacturer: 'MSD', requires_prescription: true },
  { name_ar: 'أملور 5مغ', name_en: 'Amlor 5mg', active_ingredient: 'Amlodipine', price: 35, category: 'medications', verified: true, manufacturer: 'Pfizer', requires_prescription: true },
  { name_ar: 'بلافيكس 75مغ', name_en: 'Plavix 75mg', active_ingredient: 'Clopidogrel', price: 110, category: 'medications', verified: true, manufacturer: 'Sanofi', requires_prescription: true },
  { name_ar: 'كاردورا 4مغ', name_en: 'Cardura 4mg', active_ingredient: 'Doxazosin', price: 65, category: 'medications', verified: true, manufacturer: 'Pfizer', requires_prescription: true },
  // Vitamins & Supplements
  { name_ar: 'سنتروم نساء', name_en: 'Centrum Women', active_ingredient: 'Multivitamin', price: 78, category: 'vitamins', verified: true, manufacturer: 'Pfizer' },
  { name_ar: 'فيتامين C 1000مغ', name_en: 'Vitamin C 1000mg', active_ingredient: 'Ascorbic acid', price: 38, category: 'vitamins', verified: true, manufacturer: 'Nature Made' },
  { name_ar: 'مغنيسيوم 400مغ', name_en: 'Magnesium 400mg', active_ingredient: 'Magnesium oxide', price: 42, category: 'vitamins', verified: true, manufacturer: 'Now' },
  { name_ar: 'كالسيوم + D3', name_en: 'Calcium + D3', active_ingredient: 'Calcium carbonate+D3', price: 48, category: 'vitamins', verified: true, manufacturer: 'Nature Made' },
  { name_ar: 'بيوتين 10000', name_en: 'Biotin 10000', active_ingredient: 'Biotin', price: 65, category: 'vitamins', verified: true, manufacturer: 'Sports Research' },
  { name_ar: 'زنك 50مغ', name_en: 'Zinc 50mg', active_ingredient: 'Zinc gluconate', price: 28, category: 'vitamins', verified: true, manufacturer: 'Now' },
  { name_ar: 'فيتامين B12 ميثيل', name_en: 'Vitamin B12 Methyl', active_ingredient: 'Methylcobalamin', price: 55, category: 'vitamins', verified: true, manufacturer: 'Solgar' },
  // Skincare
  { name_ar: 'سيتافيل غسول', name_en: 'Cetaphil Cleanser', active_ingredient: 'Gentle surfactants', price: 68, category: 'skincare', verified: true, manufacturer: 'Galderma' },
  { name_ar: 'بيوديرما سيبيوم', name_en: 'Bioderma Sebium', active_ingredient: 'Niacinamide+Zinc', price: 95, category: 'skincare', verified: true, manufacturer: 'Bioderma' },
  { name_ar: 'إيوسرين كريم', name_en: 'Eucerin Cream', active_ingredient: 'Urea 5%', price: 78, category: 'skincare', verified: true, manufacturer: 'Beiersdorf' },
  { name_ar: 'أفينو لوشن', name_en: 'Aveeno Lotion', active_ingredient: 'Colloidal oatmeal', price: 88, category: 'skincare', verified: true, manufacturer: 'J&J' },
  { name_ar: 'ريتين-أ كريم', name_en: 'Retin-A Cream', active_ingredient: 'Tretinoin', price: 65, category: 'skincare', verified: true, manufacturer: 'Janssen', requires_prescription: true },
  // Baby
  { name_ar: 'كاندريل أطفال', name_en: 'Calpol Kids', active_ingredient: 'Paracetamol', price: 18, category: 'baby', verified: true, manufacturer: 'GSK' },
  { name_ar: 'ديساتين كريم', name_en: 'Desitin Cream', active_ingredient: 'Zinc oxide', price: 35, category: 'baby', verified: true, manufacturer: 'J&J' },
  { name_ar: 'ميرسي حفاضات M', name_en: 'Mercy Diapers M', active_ingredient: '—', price: 58, category: 'baby', verified: true, manufacturer: 'Mercy' },
  { name_ar: 'حليب نيدو 1+', name_en: 'Nido 1+', active_ingredient: '—', price: 72, category: 'baby', verified: true, manufacturer: 'Nestle' },
  { name_ar: 'مضغة تسنين', name_en: 'Teething Gel', active_ingredient: 'Lidocaine', price: 28, category: 'baby', verified: true, manufacturer: 'Nelson' },
  // Personal care
  { name_ar: 'هيد آند شولدرز', name_en: 'Head & Shoulders', active_ingredient: 'Pyrithione zinc', price: 32, category: 'personal_care', verified: true, manufacturer: 'P&G' },
  { name_ar: 'لايف بوي', name_en: 'Lifebuoy Soap', active_ingredient: 'Triclosan', price: 6, category: 'personal_care', verified: true, manufacturer: 'Unilever' },
  { name_ar: 'ديتول مطهر', name_en: 'Dettol Antiseptic', active_ingredient: 'Chloroxylenol', price: 28, category: 'personal_care', verified: true, manufacturer: 'Reckitt' },
  { name_ar: 'كولجيت توتال', name_en: 'Colgate Total', active_ingredient: 'Fluoride+Zinc', price: 19, category: 'personal_care', verified: true, manufacturer: 'Colgate' },
  // Medical devices
  { name_ar: 'ترمومتر رقمي', name_en: 'Digital Thermometer', active_ingredient: '—', price: 35, category: 'medical_devices', verified: true, manufacturer: 'Omron' },
  { name_ar: 'بخاخ ربو ميكروفينت', name_en: 'Microvent Inhaler', active_ingredient: '—', price: 55, category: 'medical_devices', verified: true, manufacturer: 'OneMed' },
  { name_ar: 'ضمادة جروح Tegaderm', name_en: 'Tegaderm Dressing', active_ingredient: '—', price: 24, category: 'medical_devices', verified: true, manufacturer: '3M' },
  { name_ar: 'كمامات طبية 50 قطعة', name_en: 'Medical Masks x50', active_ingredient: '—', price: 45, category: 'medical_devices', verified: true, manufacturer: 'Medico' },
  { name_ar: 'محلول رغوي يدين', name_en: 'Hand Sanitizer 500ml', active_ingredient: 'Ethanol 70%', price: 22, category: 'medical_devices', verified: true, manufacturer: 'Septol' },
];
