import { renderToStaticMarkup } from "react-dom/server"; import { beforeEach,describe,expect,it,vi } from "vitest";
const state=vi.hoisted(()=>({get:vi.fn()})); vi.mock("next-intl/server",()=>({getTranslations:async()=> (k:string)=>k,setRequestLocale:vi.fn()})); vi.mock("@/lib/i18n",()=>({isLocale:()=>true})); vi.mock("@/lib/api/doctors-server",()=>({getPublicDoctors:state.get})); vi.mock("next-intl",()=>({useTranslations:()=> (k:string)=>k})); vi.mock("next/navigation",()=>({notFound:vi.fn(),useRouter:()=>({refresh:vi.fn()})})); vi.mock("@/components-next/core/core-shell", async () => {
  const { createElement } = await import("react");
  return { CoreShell: ({ children, backHref }: { children: unknown; backHref?: string }) => createElement("div", { "data-shell": true }, createElement("a", { href: backHref }, "back"), children as never) };
});
import DoctorsPage from "./page";
describe("doctors SSR",()=>{beforeEach(()=>state.get.mockReset());it("renders public doctor fields without private data",async()=>{state.get.mockResolvedValue(new Response(JSON.stringify([{id:"doc-1",name_en:"Verified Doctor",patient_id:"private"}]),{status:200}));const html=renderToStaticMarkup(await DoctorsPage({params:Promise.resolve({locale:"en"})}));expect(html).toContain("Verified Doctor");expect(html).not.toContain("private");});it("passes the quick filters from the URL to the API and keeps q",async()=>{state.get.mockResolvedValue(new Response(JSON.stringify([{id:"doc-2",name_en:"Nearby Doctor"}]),{status:200}));const html=renderToStaticMarkup(await DoctorsPage({params:Promise.resolve({locale:"en"}),searchParams:Promise.resolve({q:"heart",type:"clinic",nearest:"1",lat:"24.7136",lng:"46.6753"})}));expect(state.get).toHaveBeenCalledWith(expect.objectContaining({search:"heart",filters:expect.objectContaining({type:"clinic",nearest:true,place:{kind:"coords",lat:24.7136,lng:46.6753}})}));expect(html).toContain("Nearby Doctor");expect(html).toContain("availableNow");expect(html).toContain("nearest");expect(html).toContain("q=heart");});
it("shows the error state with a retry when the API fails",async()=>{state.get.mockResolvedValue(new Response("{}",{status:400}));const html=renderToStaticMarkup(await DoctorsPage({params:Promise.resolve({locale:"en"}),searchParams:Promise.resolve({available:"1"})}));expect(html).toContain("unavailableTitle");expect(html).toContain("retry");});
});
