import { notFound, redirect } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { ShieldCheck } from "lucide-react";
import { getPatientInsuranceBenefits, getPatientInsurancePolicy } from "@/lib/api/insurance-server";
import { parseInsuranceSummary } from "@/lib/api/insurance";
import { requirePatientAccess } from "@/lib/auth/session";
import { isLocale } from "@/lib/i18n";
import styles from "./insurance.module.css";
type Props = { params: Promise<{ locale: string }> };
export default async function InsurancePage({ params }: Props) { const { locale } = await params; if (!isLocale(locale)) notFound(); setRequestLocale(locale); const t = await getTranslations("Insurance"); const token = await requirePatientAccess(locale); const [policyResponse, benefitsResponse] = await Promise.all([getPatientInsurancePolicy(token), getPatientInsuranceBenefits(token)]); if ([policyResponse, benefitsResponse].some((r) => r.status === 401)) redirect(`/${locale}/login`); if ([policyResponse, benefitsResponse].some((r) => r.status === 403 || r.status === 404)) notFound(); if (!policyResponse.ok || !benefitsResponse.ok) return <main className="main"><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p></section></main>; const summary = parseInsuranceSummary(await policyResponse.json().catch(() => null)); if (!summary) return <main className="main"><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p></section></main>; return <main className="main"><section className={styles.hero}><p className={styles.eyebrow}><ShieldCheck size={15} aria-hidden="true" />{t("eyebrow")}</p><h1>{t("title")}</h1><p>{t("notice")}</p></section><section className={styles.grid}><div className={styles.card}><span>{t("policyStatus")}</span><strong>{summary.hasPolicy ? t("active") : t("none")}</strong></div>{summary.companyName ? <div className={styles.card}><span>{t("company")}</span><strong>{summary.companyName}</strong></div> : null}{summary.planClass ? <div className={styles.card}><span>{t("plan")}</span><strong>{summary.planClass}</strong></div> : null}</section></main>; }
