// @ts-nocheck
// app/maternity/fetus-data.ts

export interface FetusWeekData {
  week: number;
  size_name: string;
  weight_g: number;
  length_cm: number;
  description: string;
  image_path: any; // React Native require() path
}

export const FETUS_DATA: Record<number, FetusWeekData> = {
  1: {
    week: 1,
    size_name: "خلية واحدة",
    weight_g: 0,
    length_cm: 0,
    description: "في الأسبوع الأول، تبدأ البويضة المخصبة بالانقسام السريع وتتحرك نحو الرحم.",
    image_path: require('../../assets/images/maternity/fetus/week_1.jpg'),
  },
  2: {
    week: 2,
    size_name: "مجموعة خلايا (علقة)",
    weight_g: 0,
    length_cm: 0.1,
    description: "تتكاثر الخلايا وتزرع نفسها في بطانة الرحم السميكة.",
    image_path: require('../../assets/images/maternity/fetus/week_2.jpg'),
  },
  3: {
    week: 3,
    size_name: "بذرة الخشخاش",
    weight_g: 0,
    length_cm: 0.2,
    description: "يبدأ الأنبوب العصبي بالتكون، وهو الذي سيصبح لاحقاً الدماغ والحبل الشوكي.",
    image_path: require('../../assets/images/maternity/fetus/week_3.jpg'),
  },
  4: {
    week: 4,
    size_name: "بذرة السمسم",
    weight_g: 0,
    length_cm: 0.5,
    description: "يبدأ القلب الصغير بالتشكل والنبض، وتتكون براعم الأطراف الأولى.",
    image_path: require('../../assets/images/maternity/fetus/week_4.jpg'),
  },
  5: {
    week: 5,
    size_name: "حبة فلفل أسود",
    weight_g: 0,
    length_cm: 0.8,
    description: "يأخذ الجنين شكل حرف C، وتبدأ ملامح الوجه الأساسية بالظهور.",
    image_path: require('../../assets/images/maternity/fetus/week_5.jpg'),
  },
  6: {
    week: 6,
    size_name: "حبة عدس",
    weight_g: 0,
    length_cm: 1.2,
    description: "تتطور براعم الأطراف لتصبح أذرع وسيقان صغيرة، وتبدأ العينان بالتكون.",
    image_path: require('../../assets/images/maternity/fetus/week_6.jpg'),
  },
  7: {
    week: 7,
    size_name: "حبة توت أزرق",
    weight_g: 0,
    length_cm: 1.5,
    description: "يتطور الدماغ بسرعة مذهلة، وتبدأ الأعضاء الداخلية بالنمو.",
    image_path: require('../../assets/images/maternity/fetus/week_7.jpg'),
  },
  8: {
    week: 8,
    size_name: "حبة فاصوليا",
    weight_g: 1,
    length_cm: 2.5,
    description: "تتكون أصابع اليدين والقدمين الصغيرة، وتستمر الملامح بالتشكل.",
    image_path: require('../../assets/images/maternity/fetus/week_8.jpg'),
  },
  9: {
    week: 9,
    size_name: "حبة عنب",
    weight_g: 2,
    length_cm: 3.0,
    description: "تكتمل الأساسيات الجسدية للجنين ويبدأ بالتحرك بنشاط داخل الرحم.",
    image_path: require('../../assets/images/maternity/fetus/week_9.jpg'),
  },
  10: {
    week: 10,
    size_name: "برقوق مجفف",
    weight_g: 4,
    length_cm: 4.0,
    description: "ينتهي طور المضغة ويبدأ طور الجنين، وتصبح الأطراف والوجه أكثر وضوحاً.",
    image_path: require('../../assets/images/maternity/fetus/week_17.jpg'),
  },
  11: {
    week: 11,
    size_name: "حبة ليمون خضراء",
    weight_g: 7,
    length_cm: 5.0,
    description: "تتكون ملامح الوجه والأذنين بشكل أفضل، وتنمو بصيلات الشعر.",
    image_path: require('../../assets/images/maternity/fetus/week_17.jpg'),
  },
  12: {
    week: 12,
    size_name: "حبة برقوق",
    weight_g: 14,
    length_cm: 6.5,
    description: "تتكون الأظافر الرقيقة وتصبح ردود أفعال الجنين أكثر وضوحاً.",
    image_path: require('../../assets/images/maternity/fetus/week_12.jpg'),
  },
  13: {
    week: 13,
    size_name: "حبة خوخ",
    weight_g: 23,
    length_cm: 8.0,
    description: "تبدأ بصمات الأصابع الفريدة بالتشكل على أطراف الأصابع.",
    image_path: require('../../assets/images/maternity/fetus/week_13.jpg'),
  },
  14: {
    week: 14,
    size_name: "حبة ليمون",
    weight_g: 43,
    length_cm: 10.0,
    description: "يستطيع الجنين الآن تغيير تعابير وجهه والقيام بحركات بسيطة.",
    image_path: require('../../assets/images/maternity/fetus/week_14.jpg'),
  },
  15: {
    week: 15,
    size_name: "حبة تفاح",
    weight_g: 70,
    length_cm: 12.0,
    description: "يبدأ الشعر بالنمو على الرأس وتتصلب العظام تدريجياً.",
    image_path: require('../../assets/images/maternity/fetus/week_15.jpg'),
  },
  16: {
    week: 16,
    size_name: "حبة أفوكادو",
    weight_g: 100,
    length_cm: 14.0,
    description: "الهيكل العظمي يتضح أكثر، وتصبح العضلات أقوى للقيام بحركات واضحة.",
    image_path: require("../../assets/images/maternity/fetus/week_16.png"),
  },
  17: {
    week: 17,
    size_name: "حبة لفت",
    weight_g: 140,
    length_cm: 16.0,
    description: "يبدأ تكون الدهون تحت الجلد للحفاظ على درجة حرارة الجنين.",
    image_path: require("../../assets/images/maternity/fetus/week_17.png"),
  },
  18: { week: 18, size_name: "حبة فلفل حلو", weight_g: 190, length_cm: 18.0, description: "الأذنان تأخذان مكانهما النهائي، وقد تبدأين بالشعور بحركته.", image_path: require("../../assets/images/maternity/fetus/week_18.png") },
  19: { week: 19, size_name: "حبة طماطم", weight_g: 240, length_cm: 20.0, description: "يغطي جسم الجنين مادة بيضاء دهنية تحمي بشرته في السائل الأمينوسي.", image_path: require("../../assets/images/maternity/fetus/week_19.png") },
  20: { week: 20, size_name: "موزة", weight_g: 300, length_cm: 22.0, description: "في منتصف رحلة الحمل، يكسو جسمه شعر دقيق (الزغب) للحماية.", image_path: require("../../assets/images/maternity/fetus/week_20.png") },
  21: { week: 21, size_name: "حبة جزر", weight_g: 360, length_cm: 24.0, description: "يستمر الجنين بابتلاع السائل الأمينوسي لتدريب جهازه الهضمي.", image_path: require("../../assets/images/maternity/fetus/week_21.png") },
  22: { week: 22, size_name: "قرع صيفي", weight_g: 430, length_cm: 26.0, description: "تتطور حواسه بشكل ملحوظ، وتصبح ملامح وجهه واضحة ومكتملة.", image_path: require("../../assets/images/maternity/fetus/week_22.png") },
  23: { week: 23, size_name: "مانجو", weight_g: 500, length_cm: 28.0, description: "يبدأ بالاستجابة للأصوات الخارجية ويسمع نبضات قلبك بوضوح.", image_path: require("../../assets/images/maternity/fetus/week_23.png") },
  24: { week: 24, size_name: "كوز ذرة", weight_g: 600, length_cm: 30.0, description: "تنمو رئتيه وتستعدان للعمل، وتصبح بشرته مجعدة وتكتسب لوناً.", image_path: require("../../assets/images/maternity/fetus/week_24.png") },
  25: { week: 25, size_name: "قرنبيط", weight_g: 660, length_cm: 32.0, description: "تتصلب عظام الجنين تدريجياً، ويبدأ بتخزين الدهون تحت الجلد.", image_path: require("../../assets/images/maternity/fetus/week_25.png") },
  26: { week: 26, size_name: "خس أيسبرغ", weight_g: 760, length_cm: 34.0, description: "يستطيع الجنين الآن فتح وإغلاق عينيه والتمييز بين الضوء والظلام.", image_path: require("../../assets/images/maternity/fetus/week_26.png") },
  27: { week: 27, size_name: "رأس قرنبيط", weight_g: 875, length_cm: 36.0, description: "يستمر في التدرب على التنفس من خلال استنشاق السائل الأمينوسي.", image_path: require("../../assets/images/maternity/fetus/week_27.png") },
  28: { week: 28, size_name: "باذنجان كبير", weight_g: 1000, length_cm: 38.0, description: "يصل الجنين لكيلوغرام واحد تقريباً، وتزداد حركته قوة ووضوحاً.", image_path: require("../../assets/images/maternity/fetus/week_28.png") },
  29: { week: 29, size_name: "قرع الجوز", weight_g: 1150, length_cm: 40.0, description: "تنمو عضلاته بقوة ويصبح الدماغ أكثر تعقيداً لاستيعاب الحواس.", image_path: require("../../assets/images/maternity/fetus/week_29.png") },
  30: { week: 30, size_name: "ملفوف صغير", weight_g: 1300, length_cm: 42.0, description: "يتناقص الزغب الذي يغطي جسمه، وتستمر الدهون بالتراكم للحماية.", image_path: require("../../assets/images/maternity/fetus/week_30.png") },
  31: { week: 31, size_name: "حبة جوز الهند", weight_g: 1500, length_cm: 44.0, description: "يبدأ الجنين باتخاذ وضعية الولادة المقلوبة تدريجياً استعداداً.", image_path: require("../../assets/images/maternity/fetus/week_31.png") },
  32: { week: 32, size_name: "بطيخ أصفر", weight_g: 1700, length_cm: 46.0, description: "تكتمل معظم الأعضاء الحيوية، عدا الرئتين اللتين تستمران بالنضوج.", image_path: require("../../assets/images/maternity/fetus/week_32.png") },
  33: { week: 33, size_name: "أناناس", weight_g: 1900, length_cm: 48.0, description: "جهازه المناعي يصبح أقوى بفضل الأجسام المضادة التي تصله منكِ.", image_path: require("../../assets/images/maternity/fetus/week_33.png") },
  34: { week: 34, size_name: "شمام", weight_g: 2100, length_cm: 49.0, description: "يضيق المساحة داخل الرحم وتصبح حركاته أكثر كتداً بدلاً من الركل.", image_path: require("../../assets/images/maternity/fetus/week_34.png") },
  35: { week: 35, size_name: "بطيخة صغيرة", weight_g: 2400, length_cm: 50.0, description: "يكتسب المزيد من الوزن بسرعة، ويصل الكبد والكلى لعملهما الكامل.", image_path: require("../../assets/images/maternity/fetus/week_35.png") },
  36: { week: 36, size_name: "رأس خس روماني", weight_g: 2600, length_cm: 51.0, description: "يستقر في وضعية الولادة النهائية أسفل الحوض، ويستعد للقائك.", image_path: require("../../assets/images/maternity/fetus/week_36.png") },
  37: { week: 37, size_name: "سلق سويسري", weight_g: 2850, length_cm: 52.0, description: "يعتبر الحمل كاملاً الآن، وتكون الرئتان مستعدتين للتنفس الخارجي.", image_path: require("../../assets/images/maternity/fetus/week_37.png") },
  38: { week: 38, size_name: "قرع شتوي", weight_g: 3100, length_cm: 53.0, description: "تنمو أظافره لتصل إلى حافة أصابعه، وتتساقط معظم مادة الطلاء الدهني.", image_path: require("../../assets/images/maternity/fetus/week_38.png") },
  39: { week: 39, size_name: "بطيخة حمراء", weight_g: 3300, length_cm: 54.0, description: "جسمه مكتمل ومستعد للحياة خارج الرحم، ويبني طبقات الدهون النهائية.", image_path: require("../../assets/images/maternity/fetus/week_39.png") },
  40: { week: 40, size_name: "يقطينة صغيرة", weight_g: 3500, length_cm: 55.0, description: "اكتمل نمو جنينك تماماً! وهو الآن مستعد للخروج ورؤية العالم.", image_path: require("../../assets/images/maternity/fetus/week_40.png") },
};

export default function DummyFetusRoute() { return null; }
