import React from 'react';
import { View, StyleSheet, ScrollView, StatusBar, ActivityIndicator } from 'react-native';
import { router } from 'expo-router';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useApp } from '../../src/context/AppContext';
import { Icon } from '../../src/components/Icon';
import { AppText, Badge, Button, Card, IconButton } from '../../src/components/ui';
import { apiFetch } from '../../src/utils/api';
import { maternityT } from '../../src/i18n/maternity';

type Profile = { profile_ready?: boolean; tracking_mode?: 'pregnancy' | 'cycle' | null; is_pregnant?: boolean; current_week?: number | null; due_date?: string; last_period_date?: string; cycle_length?: number; is_regular?: boolean; estimate_notice?: string };
const addDays = (date: Date, days: number) => { const copy = new Date(date); copy.setDate(copy.getDate() + days); return copy; };
export default function MaternityHubScreen() {
  const insets = useSafeAreaInsets(); const { colors, isDark, lang } = useApp(); const t = (key: any, vars?: any) => maternityT(lang, key, vars);
  const [profile, setProfile] = React.useState<Profile | null>(null); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null);
  const load = React.useCallback(async () => { setLoading(true); setError(null); try { const response: any = await apiFetch('/maternity/profile'); setProfile(response?.data || response); } catch { setError(t('error')); setProfile(null); } finally { setLoading(false); } }, [lang]); React.useEffect(() => { load(); }, [load]);
  const format = (value?: string | Date) => value ? new Date(value).toLocaleDateString(lang === 'ar' ? 'ar' : lang, { day:'numeric', month:'short', year:'numeric' }) : '—';
  const cycle = !profile?.is_pregnant && profile?.last_period_date && profile?.cycle_length ? (() => { const last = new Date(profile.last_period_date!); const ovulation = addDays(last, profile.cycle_length! - 14); return { ovulation, start:addDays(ovulation, -5), end:addDays(ovulation, 1), next:addDays(last, profile.cycle_length!) }; })() : null;
  return <View style={[styles.container, { backgroundColor: colors.background }]}><StatusBar barStyle={isDark ? 'light-content' : 'dark-content'} /><View style={[styles.header, { paddingTop: insets.top + 16, backgroundColor: colors.secondary }]}><View style={{ width:44 }} /><View style={styles.titleWrap}><AppText variant="h3" color="#fff">{t('title')}</AppText><AppText variant="caption" color="rgba(255,255,255,0.82)">{t('subtitle')}</AppText></View><IconButton icon="back" bg="rgba(255,255,255,0.16)" color="#fff" onPress={() => router.back()} /></View>{loading ? <View style={styles.center}><ActivityIndicator color={colors.secondary} /><AppText variant="bodySM" color={colors.textTertiary}>{t('loading')}</AppText></View> : <ScrollView contentContainerStyle={[styles.content, { paddingBottom:insets.bottom + 32 }]}>{error && <Card style={styles.error}><AppText variant="bodySM" color="#B91C1C" align="right">{error}</AppText><Button label={t('retry')} size="sm" variant="outline" full={false} onPress={load} /></Card>}{!profile?.profile_ready ? <Animated.View entering={FadeInDown.duration(300)}><Card style={styles.empty}><Icon name="calendar_today" size={36} color={colors.secondary} /><AppText variant="h5">{t('profileRequired')}</AppText><AppText variant="bodySM" color={colors.textSecondary} align="right">{t('choosePath')}</AppText><Button label={t('openSetup')} variant="gradient" onPress={() => router.push('/maternity/maternity-setup')} /></Card></Animated.View> : profile.is_pregnant ? <PregnancyCard profile={profile} t={t} format={format} colors={colors} /> : <CycleCard profile={profile} cycle={cycle} t={t} format={format} colors={colors} />}{profile?.profile_ready && <><Animated.View entering={FadeInDown.delay(180).duration(300)}><Card style={[styles.notice, { backgroundColor: colors.warningSurface, borderColor: colors.warning + '55' }]}><AppText variant="bodySM" color={colors.textSecondary} align="right">{profile.is_pregnant ? t('pregnancyNotice') : t('cycleNotice')}</AppText><AppText variant="caption" color={colors.textTertiary} align="right">{t('safetyNotice')}</AppText></Card></Animated.View><Animated.View entering={FadeInDown.delay(240).duration(300)}><Button label={t('update')} variant="outline" icon="edit" onPress={() => router.push('/maternity/maternity-setup')} /></Animated.View></>}</ScrollView>}</View>;
}
function PregnancyCard({ profile, t, format, colors }: any) { return <Animated.View entering={FadeInDown.duration(300)}><Card style={[styles.hero, { backgroundColor: colors.secondarySurface, borderColor: colors.secondary + '33' }]}><View style={styles.heroTop}><View style={[styles.iconCircle, { backgroundColor: colors.secondary }]}><Icon name="calendar_today" size={25} color="#fff" /></View><View style={{ flex:1, alignItems:'flex-end', gap:3 }}><AppText variant="caption" color={colors.textTertiary}>{t('currentWeek')}</AppText><AppText variant="displayMD" color={colors.secondary}>{profile.current_week ?? '—'}</AppText></View></View><Divider colors={colors} /><Row label={t('estimatedDueDate')} value={format(profile.due_date)} colors={colors} /><Badge label={t('estimate')} color={colors.secondary} /></Card></Animated.View>; }
function CycleCard({ profile, cycle, t, format, colors }: any) { return <Animated.View entering={FadeInDown.duration(300)}><Card style={[styles.hero, { backgroundColor: colors.secondarySurface, borderColor: colors.secondary + '33' }]}><View style={styles.heroTop}><View style={[styles.iconCircle, { backgroundColor: colors.secondary }]}><Icon name="event_available" size={25} color="#fff" /></View><View style={{ flex:1, alignItems:'flex-end', gap:3 }}><AppText variant="h5">{t('cycle')}</AppText><AppText variant="caption" color={colors.textTertiary}>{profile.is_regular ? t('regular') : t('irregular')}</AppText></View></View>{cycle ? <><Divider colors={colors} /><Row label={t('estimatedOvulation')} value={format(cycle.ovulation)} colors={colors} /><Row label={t('fertileWindow')} value={`${format(cycle.start)} — ${format(cycle.end)}`} colors={colors} /><Row label={t('nextPeriod')} value={format(cycle.next)} colors={colors} /><Badge label={t('estimate')} color={colors.secondary} /></> : <AppText variant="bodySM" color={colors.textTertiary} align="right">{t('noData')}</AppText>}</Card></Animated.View>; }
function Row({ label, value, colors }: any) { return <View style={styles.row}><AppText variant="bodySM" color={colors.textSecondary}>{value}</AppText><AppText variant="labelMD">{label}</AppText></View>; } function Divider({ colors }: any) { return <View style={[styles.divider, { backgroundColor: colors.borderLight }]} />; }
const styles = StyleSheet.create({ container:{flex:1}, header:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,paddingBottom:20,borderBottomLeftRadius:28,borderBottomRightRadius:28}, titleWrap:{flex:1,alignItems:'center',gap:2}, content:{padding:16,gap:14}, center:{flex:1,alignItems:'center',justifyContent:'center',gap:12}, error:{backgroundColor:'#FEE2E2',alignItems:'flex-end',gap:8}, empty:{alignItems:'center',gap:12,paddingVertical:28}, hero:{gap:14,borderWidth:1}, heroTop:{flexDirection:'row-reverse',alignItems:'center',gap:12}, iconCircle:{width:54,height:54,borderRadius:18,alignItems:'center',justifyContent:'center'}, divider:{height:1,width:'100%'}, row:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center',gap:10}, notice:{gap:8,borderWidth:1} });
