import React from 'react';
import { View, StyleSheet, ScrollView, StatusBar } from 'react-native';
import { router } from 'expo-router';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useApp } from '../../src/context/AppContext';
import { AppText, Button, Card, IconButton, Input, SegmentedControl } from '../../src/components/ui';
import { apiFetch } from '../../src/utils/api';
import { maternityT } from '../../src/i18n/maternity';

type Mode = 'pregnancy' | 'cycle';
export default function MaternitySetupScreen() {
  const insets = useSafeAreaInsets(); const { colors, isDark, lang } = useApp(); const t = (key: any, vars?: any) => maternityT(lang, key, vars);
  const [mode, setMode] = React.useState<Mode>('cycle'); const [lmp, setLmp] = React.useState(''); const [dueDate, setDueDate] = React.useState(''); const [cycleLength, setCycleLength] = React.useState(''); const [regular, setRegular] = React.useState('true'); const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  const save = async () => { if (!lmp.trim() || (mode === 'cycle' && !cycleLength.trim())) { setError(t('profileRequired')); return; } setSaving(true); setError(null); try { await apiFetch('/maternity/profile', { method: 'POST', body: JSON.stringify(mode === 'pregnancy' ? { is_pregnant: true, lmp_date: lmp.trim(), ...(dueDate.trim() ? { due_date: dueDate.trim() } : {}) } : { is_pregnant: false, last_period_date: lmp.trim(), cycle_length: Number(cycleLength), is_regular: regular === 'true' }) }); router.replace('/maternity/hub'); } catch { setError(t('saveError')); } finally { setSaving(false); } };
  return <View style={[styles.container, { backgroundColor: colors.background }]}><StatusBar barStyle={isDark ? 'light-content' : 'dark-content'} /><View style={[styles.header, { paddingTop: insets.top + 16 }]}><View style={{ width: 44 }} /><View style={styles.titleWrap}><AppText variant="h3">{t('setup')}</AppText><AppText variant="caption" color={colors.textTertiary}>{t('choosePath')}</AppText></View><IconButton icon="back" bg={colors.surfaceSecondary} color={colors.textPrimary} onPress={() => router.back()} /></View><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 32 }]}>{error && <Card style={styles.error}><AppText variant="bodySM" color="#B91C1C" align="right">{error}</AppText></Card>}<Animated.View entering={FadeInDown.duration(300)}><Card style={styles.section}><SegmentedControl value={mode} onChange={(value) => setMode(value as Mode)} options={[{ key:'cycle', label:t('cycle') }, { key:'pregnancy', label:t('pregnancy') }]} /><AppText variant="bodySM" color={colors.textSecondary} align="right">{mode === 'pregnancy' ? t('pregnantSetup') : t('cycleSetup')}</AppText></Card></Animated.View><Animated.View entering={FadeInDown.delay(80).duration(300)}><Card style={styles.section}><Input value={lmp} onChangeText={setLmp} placeholder={t('lmp')} autoCapitalize="none" /><AppText variant="caption" color={colors.textTertiary} align="right">{t('dateFormat')}</AppText>{mode === 'pregnancy' ? <Input value={dueDate} onChangeText={setDueDate} placeholder={t('dueDate')} autoCapitalize="none" /> : <><Input value={cycleLength} onChangeText={setCycleLength} placeholder={t('cycleLength')} keyboardType="numeric" /><SegmentedControl value={regular} onChange={setRegular} options={[{ key:'true', label:t('regular') }, { key:'false', label:t('irregular') }]} /></>}</Card></Animated.View><Animated.View entering={FadeInDown.delay(150).duration(300)}><Card style={[styles.notice, { backgroundColor: colors.warningSurface, borderColor: colors.warning + '55' }]}><AppText variant="bodySM" color={colors.textSecondary} align="right">{mode === 'pregnancy' ? t('pregnancyNotice') : t('cycleNotice')}</AppText><AppText variant="caption" color={colors.textTertiary} align="right">{t('notContraception')}</AppText></Card></Animated.View><Animated.View entering={FadeInDown.delay(220).duration(300)}><Button label={saving ? t('saving') : t('save')} variant="gradient" icon="check_circle" loading={saving} onPress={save} /></Animated.View></ScrollView></View>;
}
const styles = StyleSheet.create({ container:{ flex:1 }, header:{ flexDirection:'row-reverse', alignItems:'center', justifyContent:'space-between', paddingHorizontal:16, paddingBottom:10 }, titleWrap:{ flex:1, alignItems:'center', gap:2 }, content:{ padding:16, gap:14 }, section:{ gap:12 }, notice:{ gap:8, borderWidth:1 }, error:{ backgroundColor:'#FEE2E2', alignItems:'flex-end' } });
