/**
 * 13.R11 — SYNTHETIC fixtures ONLY. NOT real Saudi geography.
 *
 * Fake names ("Test Region …", "Test City …", "Test District …") exist solely
 * to prove parent→child traversal + alias resolution in the R11 spec.
 * A real Region→City→District import requires the owner's dataset and is
 * explicitly OUT OF SCOPE for R11 — DO NOT treat these rows as seed data.
 *
 * Shape: 3 regions, 5 cities, 8 districts (16 nodes total).
 */
import type { R11HierarchyNode } from './geo-hierarchy-r11';

export const R11_SYNTHETIC_FIXTURES: R11HierarchyNode[] = [
  // ── Regions (3) ──────────────────────────────────────────────
  {
    code: 'r11-test-region-alpha',
    name_ar: 'منطقة الاختبار ألفا',
    name_en: 'Test Region Alpha',
    type: 'region',
    parent_code: null,
    aliases: ['Alpha Test Region'],
    transliterations: ['mintaqat al-ikhtibar alfa'],
    coordinates: { lat: 24.7136, lng: 46.6753 },
    is_active: true,
  },
  {
    code: 'r11-test-region-beta',
    name_ar: 'منطقة الاختبار بيتا',
    name_en: 'Test Region Beta',
    type: 'region',
    parent_code: null,
    aliases: ['Beta Test Region'],
    transliterations: ['mintaqat al-ikhtibar bita'],
    coordinates: { lat: 21.4858, lng: 39.1925 },
    is_active: true,
  },
  {
    code: 'r11-test-region-gamma',
    name_ar: 'منطقة الاختبار غاما',
    name_en: 'Test Region Gamma',
    type: 'region',
    parent_code: null,
    aliases: [],
    transliterations: ['mintaqat al-ikhtibar ghama'],
    coordinates: { lat: 26.4207, lng: 50.0888 },
    is_active: true,
  },

  // ── Cities (5) ───────────────────────────────────────────────
  {
    code: 'r11-test-city-one',
    name_ar: 'مدينة الاختبار الأولى',
    name_en: 'Test City One',
    type: 'city',
    parent_code: 'r11-test-region-alpha',
    aliases: ['First Test City'],
    transliterations: ['madinat al-ikhtibar al-ula'],
    coordinates: { lat: 24.72, lng: 46.68 },
    is_active: true,
  },
  {
    code: 'r11-test-city-two',
    name_ar: 'مدينة الاختبار الثانية',
    name_en: 'Test City Two',
    type: 'city',
    parent_code: 'r11-test-region-alpha',
    aliases: [],
    transliterations: ['madinat al-ikhtibar al-thaniya'],
    coordinates: { lat: 24.63, lng: 46.7 },
    is_active: true,
  },
  {
    code: 'r11-test-city-three',
    name_ar: 'مدينة الاختبار الثالثة',
    name_en: 'Test City Three',
    type: 'city',
    parent_code: 'r11-test-region-beta',
    aliases: ['Third Test City'],
    transliterations: ['madinat al-ikhtibar al-thalitha'],
    coordinates: { lat: 21.49, lng: 39.19 },
    is_active: true,
  },
  {
    code: 'r11-test-city-four',
    name_ar: 'مدينة الاختبار الرابعة',
    name_en: 'Test City Four',
    type: 'city',
    parent_code: 'r11-test-region-beta',
    aliases: [],
    transliterations: ['madinat al-ikhtibar al-rabia'],
    coordinates: { lat: 21.54, lng: 39.17 },
    is_active: true,
  },
  {
    code: 'r11-test-city-five',
    name_ar: 'مدينة الاختبار الخامسة',
    name_en: 'Test City Five',
    type: 'city',
    parent_code: 'r11-test-region-gamma',
    aliases: [],
    transliterations: ['madinat al-ikhtibar al-khamisa'],
    coordinates: { lat: 26.42, lng: 50.09 },
    is_active: true,
  },

  // ── Districts (8) ────────────────────────────────────────────
  {
    code: 'r11-test-district-a1',
    name_ar: 'حي الاختبار أ1',
    name_en: 'Test District A1',
    type: 'district',
    parent_code: 'r11-test-city-one',
    aliases: ['A1 Test District'],
    transliterations: ['hayy al-ikhtibar a1'],
    coordinates: { lat: 24.721, lng: 46.681 },
    is_active: true,
  },
  {
    code: 'r11-test-district-a2',
    name_ar: 'حي الاختبار أ2',
    name_en: 'Test District A2',
    type: 'district',
    parent_code: 'r11-test-city-one',
    aliases: [],
    transliterations: ['hayy al-ikhtibar a2'],
    coordinates: { lat: 24.722, lng: 46.682 },
    is_active: true,
  },
  {
    code: 'r11-test-district-b1',
    name_ar: 'حي الاختبار ب1',
    name_en: 'Test District B1',
    type: 'district',
    parent_code: 'r11-test-city-two',
    aliases: [],
    transliterations: ['hayy al-ikhtibar b1'],
    coordinates: { lat: 24.631, lng: 46.701 },
    is_active: true,
  },
  {
    code: 'r11-test-district-c1',
    name_ar: 'حي الاختبار ج1',
    name_en: 'Test District C1',
    type: 'district',
    parent_code: 'r11-test-city-three',
    aliases: ['C1 Test District'],
    transliterations: ['hayy al-ikhtibar c1'],
    coordinates: { lat: 21.491, lng: 39.191 },
    is_active: true,
  },
  {
    code: 'r11-test-district-c2',
    name_ar: 'حي الاختبار ج2',
    name_en: 'Test District C2',
    type: 'district',
    parent_code: 'r11-test-city-three',
    aliases: [],
    transliterations: ['hayy al-ikhtibar c2'],
    coordinates: { lat: 21.492, lng: 39.192 },
    is_active: true,
  },
  {
    code: 'r11-test-district-d1',
    name_ar: 'حي الاختبار د1',
    name_en: 'Test District D1',
    type: 'district',
    parent_code: 'r11-test-city-four',
    aliases: [],
    transliterations: ['hayy al-ikhtibar d1'],
    coordinates: { lat: 21.541, lng: 39.171 },
    is_active: true,
  },
  {
    code: 'r11-test-district-e1',
    name_ar: 'حي الاختبار هـ1',
    name_en: 'Test District E1',
    type: 'district',
    parent_code: 'r11-test-city-five',
    aliases: [],
    transliterations: ['hayy al-ikhtibar e1'],
    coordinates: { lat: 26.421, lng: 50.091 },
    is_active: true,
  },
  {
    code: 'r11-test-district-e2',
    name_ar: 'حي الاختبار هـ2',
    name_en: 'Test District E2',
    type: 'district',
    parent_code: 'r11-test-city-five',
    aliases: ['E2 Test District'],
    transliterations: ['hayy al-ikhtibar e2'],
    coordinates: { lat: 26.422, lng: 50.092 },
    is_active: true,
  },
];
