import type { SupportedLanguage } from './LanguageManager';

type Vars = Record<string, string | number>;
type Copy = Record<string, string>;

export const nutritionTranslations: Record<SupportedLanguage, Copy> = {
  ar: {
    title: 'تغذيتي', subtitle: 'وجباتك وأهدافك كما سجلتها', loading: 'جارٍ تحميل بيانات التغذية…', retry: 'إعادة المحاولة', error: 'تعذر تحميل بيانات التغذية.',
    setup: 'إعداد أهداف التغذية', setupTitle: 'ابدأ بأهدافك المسجلة', setupHint: 'لا تظهر أي سعرة أو ماء مستهدف قبل أن تدخلها بنفسك. هذا ليس بديلاً عن نصيحة اختصاصي تغذية.', save: 'حفظ الأهداف', saving: 'جارٍ الحفظ…',
    goal: 'الهدف', weightLoss: 'خفض الوزن', maintain: 'المحافظة على الوزن', muscleGain: 'زيادة الكتلة العضلية', healthy: 'نمط صحي', height: 'الطول (سم)', weight: 'الوزن الحالي (كجم)', targetWeight: 'الوزن المستهدف (كجم)', calorieTarget: 'هدف السعرات اليومي', waterTarget: 'هدف الماء اليومي (مل)', activity: 'مستوى النشاط', sedentary: 'قليل الحركة', light: 'خفيف', moderate: 'متوسط', active: 'نشط', veryActive: 'نشط جداً', dietaryRestrictions: 'قيود غذائية مفصولة بفاصلة (اختياري)', allergies: 'حساسية غذائية مفصولة بفاصلة (اختياري)',
    dailyTracker: 'المتابعة اليومية', logMeal: 'تسجيل وجبة', logWater: 'تسجيل ماء', waterAmount: 'الكمية (مل)', addWater: 'إضافة ماء', bodyGoals: 'أهداف الجسم والتغذية',
    summary: 'ملخص اليوم', calories: 'السعرات', protein: 'البروتين', carbs: 'الكربوهيدرات', fat: 'الدهون', fiber: 'الألياف', consumed: 'المسجل', target: 'الهدف', remaining: 'المتبقي', noTarget: 'لم تحدد هدفاً بعد', mealsLogged: '{count} وجبة مسجلة اليوم', noMeals: 'لا توجد وجبات مسجلة لهذا اليوم.', addMeal: 'أضف وجبة', mealHistory: 'وجبات اليوم', waterLog: 'ماء اليوم', exercise: 'النشاط المسجل',
    breakfast: 'الإفطار', lunch: 'الغداء', dinner: 'العشاء', snack: 'وجبة خفيفة', mealType: 'نوع الوجبة', mealName: 'اسم الوجبة كما أكلتها', mealNameHint: 'مثال: شوربة خضار', caloriesInput: 'السعرات الفعلية أو المقدرة', proteinInput: 'البروتين (جم، اختياري)', carbsInput: 'الكربوهيدرات (جم، اختياري)', fatInput: 'الدهون (جم، اختياري)', fiberInput: 'الألياف (جم، اختياري)', saveMeal: 'حفظ الوجبة', mealSaved: 'تم حفظ الوجبة.', formRequired: 'أدخل اسم الوجبة والسعرات.', formInvalid: 'تحقق من الأرقام قبل الحفظ.', saveError: 'تعذر حفظ السجل. لم تتغير بياناتك.', nutritionSafety: 'تسجيل الوجبات يساعد على المتابعة فقط. لا يضع نَبْض تشخيصاً أو حمية علاجية أو بديلاً عن اختصاصي التغذية.', profileSaved: 'تم حفظ أهداف التغذية.',
    today: 'اليوم', netCalories: 'الصافي بعد النشاط', waterProgress: '{value} مل مسجلة', noData: 'لا توجد بيانات كافية بعد.',
  },
  en: {
    title: 'My nutrition', subtitle: 'Your logged meals and goals', loading: 'Loading nutrition data…', retry: 'Try again', error: 'Nutrition data could not be loaded.',
    setup: 'Set nutrition goals', setupTitle: 'Start with your recorded goals', setupHint: 'No calorie or water target is shown until you enter it. This is not a substitute for dietitian advice.', save: 'Save goals', saving: 'Saving…',
    goal: 'Goal', weightLoss: 'Weight loss', maintain: 'Maintain weight', muscleGain: 'Build muscle', healthy: 'Healthy lifestyle', height: 'Height (cm)', weight: 'Current weight (kg)', targetWeight: 'Target weight (kg)', calorieTarget: 'Daily calorie target', waterTarget: 'Daily water target (ml)', activity: 'Activity level', sedentary: 'Sedentary', light: 'Light', moderate: 'Moderate', active: 'Active', veryActive: 'Very active', dietaryRestrictions: 'Dietary restrictions, comma separated (optional)', allergies: 'Food allergies, comma separated (optional)',
    dailyTracker: 'Daily tracker', logMeal: 'Log meal', logWater: 'Log water', waterAmount: 'Amount (ml)', addWater: 'Add water', bodyGoals: 'Body & nutrition goals',
    summary: 'Today’s summary', calories: 'Calories', protein: 'Protein', carbs: 'Carbohydrates', fat: 'Fat', fiber: 'Fiber', consumed: 'Logged', target: 'Target', remaining: 'Remaining', noTarget: 'No target set yet', mealsLogged: '{count} meals logged today', noMeals: 'No meals have been logged for this day.', addMeal: 'Add meal', mealHistory: 'Today’s meals', waterLog: 'Today’s water', exercise: 'Logged activity',
    breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner', snack: 'Snack', mealType: 'Meal type', mealName: 'Meal name as you ate it', mealNameHint: 'Example: vegetable soup', caloriesInput: 'Actual or estimated calories', proteinInput: 'Protein (g, optional)', carbsInput: 'Carbohydrates (g, optional)', fatInput: 'Fat (g, optional)', fiberInput: 'Fiber (g, optional)', saveMeal: 'Save meal', mealSaved: 'Meal saved.', formRequired: 'Enter a meal name and calories.', formInvalid: 'Check the numbers before saving.', saveError: 'The record could not be saved. Your data has not changed.', nutritionSafety: 'Meal logging supports tracking only. Nabdah does not diagnose, prescribe a therapeutic diet, or replace a dietitian.', profileSaved: 'Nutrition goals saved.',
    today: 'Today', netCalories: 'Net after activity', waterProgress: '{value} ml logged', noData: 'Not enough data yet.',
  },
  ur: {
    title: 'میری غذائیت', subtitle: 'آپ کے درج شدہ کھانے اور اہداف', loading: 'غذائیت کا ڈیٹا لوڈ ہو رہا ہے…', retry: 'دوبارہ کوشش', error: 'غذائیت کا ڈیٹا لوڈ نہیں ہو سکا۔',
    setup: 'غذائیت کے اہداف مقرر کریں', setupTitle: 'اپنے درج شدہ اہداف سے شروع کریں', setupHint: 'جب تک آپ خود درج نہ کریں کیلوریز یا پانی کا ہدف نہیں دکھایا جاتا۔ یہ غذائی ماہر کے مشورے کا متبادل نہیں۔', save: 'اہداف محفوظ کریں', saving: 'محفوظ ہو رہا ہے…',
    goal: 'ہدف', weightLoss: 'وزن کم کرنا', maintain: 'وزن برقرار رکھنا', muscleGain: 'عضلات بڑھانا', healthy: 'صحت مند طرز زندگی', height: 'قد (سینٹی میٹر)', weight: 'موجودہ وزن (کلو)', targetWeight: 'مطلوبہ وزن (کلو)', calorieTarget: 'روزانہ کیلوری ہدف', waterTarget: 'روزانہ پانی ہدف (ملی)', activity: 'سرگرمی کی سطح', sedentary: 'کم حرکت', light: 'ہلکی', moderate: 'درمیانی', active: 'فعال', veryActive: 'بہت فعال', dietaryRestrictions: 'غذائی پابندیاں، کاما سے الگ (اختیاری)', allergies: 'غذائی الرجی، کاما سے الگ (اختیاری)',
    dailyTracker: 'روزانہ ٹریکر', logMeal: 'کھانا درج کریں', logWater: 'پانی درج کریں', waterAmount: 'مقدار (ملی)', addWater: 'پانی شامل کریں', bodyGoals: 'جسم اور غذائیت کے اہداف',
    summary: 'آج کا خلاصہ', calories: 'کیلوریز', protein: 'پروٹین', carbs: 'کاربوہائیڈریٹس', fat: 'چکنائی', fiber: 'فائبر', consumed: 'درج شدہ', target: 'ہدف', remaining: 'باقی', noTarget: 'ابھی ہدف مقرر نہیں', mealsLogged: 'آج {count} کھانے درج ہوئے', noMeals: 'اس دن کوئی کھانا درج نہیں۔', addMeal: 'کھانا شامل کریں', mealHistory: 'آج کے کھانے', waterLog: 'آج کا پانی', exercise: 'درج سرگرمی',
    breakfast: 'ناشتہ', lunch: 'دوپہر کا کھانا', dinner: 'رات کا کھانا', snack: 'ہلکی غذا', mealType: 'کھانے کی قسم', mealName: 'کھانے کا نام جیسا آپ نے کھایا', mealNameHint: 'مثال: سبزی کا سوپ', caloriesInput: 'حقیقی یا اندازاً کیلوریز', proteinInput: 'پروٹین (گرام، اختیاری)', carbsInput: 'کاربوہائیڈریٹس (گرام، اختیاری)', fatInput: 'چکنائی (گرام، اختیاری)', fiberInput: 'فائبر (گرام، اختیاری)', saveMeal: 'کھانا محفوظ کریں', mealSaved: 'کھانا محفوظ ہو گیا۔', formRequired: 'کھانے کا نام اور کیلوریز درج کریں۔', formInvalid: 'محفوظ کرنے سے پہلے اعداد دیکھیں۔', saveError: 'ریکارڈ محفوظ نہیں ہوا۔ ڈیٹا تبدیل نہیں ہوا۔', nutritionSafety: 'کھانا درج کرنا صرف نگرانی میں مدد دیتا ہے۔ نَبْض تشخیص یا علاجی غذا تجویز نہیں کرتا۔', profileSaved: 'غذائیت کے اہداف محفوظ ہو گئے۔',
    today: 'آج', netCalories: 'سرگرمی کے بعد خالص', waterProgress: '{value} ملی درج', noData: 'ابھی کافی ڈیٹا نہیں۔',
  },
  hi: {
    title: 'मेरा पोषण', subtitle: 'आपके दर्ज भोजन और लक्ष्य', loading: 'पोषण डेटा लोड हो रहा है…', retry: 'फिर प्रयास करें', error: 'पोषण डेटा लोड नहीं हो सका।',
    setup: 'पोषण लक्ष्य सेट करें', setupTitle: 'अपने दर्ज लक्ष्यों से शुरू करें', setupHint: 'जब तक आप स्वयं दर्ज न करें, कोई कैलोरी या पानी लक्ष्य नहीं दिखता। यह आहार विशेषज्ञ की सलाह का विकल्प नहीं है।', save: 'लक्ष्य सहेजें', saving: 'सहेजा जा रहा है…',
    goal: 'लक्ष्य', weightLoss: 'वजन घटाना', maintain: 'वजन बनाए रखना', muscleGain: 'मांसपेशी बढ़ाना', healthy: 'स्वस्थ जीवनशैली', height: 'लंबाई (सेमी)', weight: 'वर्तमान वजन (किग्रा)', targetWeight: 'लक्ष्य वजन (किग्रा)', calorieTarget: 'दैनिक कैलोरी लक्ष्य', waterTarget: 'दैनिक पानी लक्ष्य (मिली)', activity: 'गतिविधि स्तर', sedentary: 'निष्क्रिय', light: 'हल्का', moderate: 'मध्यम', active: 'सक्रिय', veryActive: 'बहुत सक्रिय', dietaryRestrictions: 'आहार प्रतिबंध, कॉमा से अलग (वैकल्पिक)', allergies: 'खाद्य एलर्जी, कॉमा से अलग (वैकल्पिक)',
    dailyTracker: 'दैनिक ट्रैकर', logMeal: 'भोजन दर्ज करें', logWater: 'पानी दर्ज करें', waterAmount: 'मात्रा (मिली)', addWater: 'पानी जोड़ें', bodyGoals: 'शरीर और पोषण लक्ष्य',
    summary: 'आज का सारांश', calories: 'कैलोरी', protein: 'प्रोटीन', carbs: 'कार्बोहाइड्रेट', fat: 'वसा', fiber: 'फाइबर', consumed: 'दर्ज', target: 'लक्ष्य', remaining: 'शेष', noTarget: 'अभी लक्ष्य सेट नहीं', mealsLogged: 'आज {count} भोजन दर्ज', noMeals: 'इस दिन कोई भोजन दर्ज नहीं है।', addMeal: 'भोजन जोड़ें', mealHistory: 'आज के भोजन', waterLog: 'आज का पानी', exercise: 'दर्ज गतिविधि',
    breakfast: 'नाश्ता', lunch: 'दोपहर का भोजन', dinner: 'रात का भोजन', snack: 'नाश्ता', mealType: 'भोजन प्रकार', mealName: 'भोजन का नाम जैसा आपने खाया', mealNameHint: 'उदाहरण: सब्ज़ी सूप', caloriesInput: 'वास्तविक या अनुमानित कैलोरी', proteinInput: 'प्रोटीन (ग्राम, वैकल्पिक)', carbsInput: 'कार्बोहाइड्रेट (ग्राम, वैकल्पिक)', fatInput: 'वसा (ग्राम, वैकल्पिक)', fiberInput: 'फाइबर (ग्राम, वैकल्पिक)', saveMeal: 'भोजन सहेजें', mealSaved: 'भोजन सहेज दिया गया।', formRequired: 'भोजन नाम और कैलोरी दर्ज करें।', formInvalid: 'सहेजने से पहले अंक जाँचें।', saveError: 'रिकॉर्ड सहेजा नहीं गया। डेटा नहीं बदला।', nutritionSafety: 'भोजन लॉगिंग केवल ट्रैकिंग में मदद करती है। नबदह निदान या चिकित्सीय आहार नहीं देता।', profileSaved: 'पोषण लक्ष्य सहेजे गए।',
    today: 'आज', netCalories: 'गतिविधि के बाद शुद्ध', waterProgress: '{value} मिली दर्ज', noData: 'अभी पर्याप्त डेटा नहीं।',
  },
  bn: {
    title: 'আমার পুষ্টি', subtitle: 'আপনার নথিভুক্ত খাবার ও লক্ষ্য', loading: 'পুষ্টির তথ্য লোড হচ্ছে…', retry: 'আবার চেষ্টা করুন', error: 'পুষ্টির তথ্য লোড করা যায়নি।',
    setup: 'পুষ্টির লক্ষ্য নির্ধারণ করুন', setupTitle: 'আপনার নথিভুক্ত লক্ষ্য দিয়ে শুরু করুন', setupHint: 'আপনি নিজে না দিলে ক্যালরি বা পানির লক্ষ্য দেখানো হয় না। এটি পুষ্টিবিদের পরামর্শের বিকল্প নয়।', save: 'লক্ষ্য সংরক্ষণ করুন', saving: 'সংরক্ষণ হচ্ছে…',
    goal: 'লক্ষ্য', weightLoss: 'ওজন কমানো', maintain: 'ওজন বজায় রাখা', muscleGain: 'পেশি বাড়ানো', healthy: 'স্বাস্থ্যকর জীবনধারা', height: 'উচ্চতা (সেমি)', weight: 'বর্তমান ওজন (কেজি)', targetWeight: 'লক্ষ্য ওজন (কেজি)', calorieTarget: 'দৈনিক ক্যালরি লক্ষ্য', waterTarget: 'দৈনিক পানি লক্ষ্য (মিলি)', activity: 'কার্যকলাপের মাত্রা', sedentary: 'নিষ্ক্রিয়', light: 'হালকা', moderate: 'মাঝারি', active: 'সক্রিয়', veryActive: 'খুব সক্রিয়', dietaryRestrictions: 'খাদ্য সীমাবদ্ধতা, কমা দিয়ে আলাদা (ঐচ্ছিক)', allergies: 'খাদ্য অ্যালার্জি, কমা দিয়ে আলাদা (ঐচ্ছিক)',
    dailyTracker: 'দৈনিক ট্র্যাকার', logMeal: 'খাবার নথিভুক্ত করুন', logWater: 'পানি নথিভুক্ত করুন', waterAmount: 'পরিমাণ (মিলি)', addWater: 'পানি যোগ করুন', bodyGoals: 'শরীর ও পুষ্টি লক্ষ্য',
    summary: 'আজকের সারাংশ', calories: 'ক্যালরি', protein: 'প্রোটিন', carbs: 'কার্বোহাইড্রেট', fat: 'চর্বি', fiber: 'ফাইবার', consumed: 'নথিভুক্ত', target: 'লক্ষ্য', remaining: 'বাকি', noTarget: 'এখনও লক্ষ্য নির্ধারিত নয়', mealsLogged: 'আজ {count}টি খাবার নথিভুক্ত', noMeals: 'এই দিনে কোনো খাবার নথিভুক্ত নেই।', addMeal: 'খাবার যোগ করুন', mealHistory: 'আজকের খাবার', waterLog: 'আজকের পানি', exercise: 'নথিভুক্ত কার্যকলাপ',
    breakfast: 'সকালের নাশতা', lunch: 'দুপুরের খাবার', dinner: 'রাতের খাবার', snack: 'হালকা খাবার', mealType: 'খাবারের ধরন', mealName: 'আপনি যে নামের খাবার খেয়েছেন', mealNameHint: 'উদাহরণ: সবজির স্যুপ', caloriesInput: 'প্রকৃত বা অনুমিত ক্যালরি', proteinInput: 'প্রোটিন (গ্রাম, ঐচ্ছিক)', carbsInput: 'কার্বোহাইড্রেট (গ্রাম, ঐচ্ছিক)', fatInput: 'চর্বি (গ্রাম, ঐচ্ছিক)', fiberInput: 'ফাইবার (গ্রাম, ঐচ্ছিক)', saveMeal: 'খাবার সংরক্ষণ করুন', mealSaved: 'খাবার সংরক্ষিত হয়েছে।', formRequired: 'খাবারের নাম ও ক্যালরি দিন।', formInvalid: 'সংরক্ষণের আগে সংখ্যা যাচাই করুন।', saveError: 'রেকর্ড সংরক্ষণ করা যায়নি। তথ্য বদলায়নি।', nutritionSafety: 'খাবার নথিভুক্ত করা শুধু ট্র্যাকিংয়ে সহায়তা করে। নাবদাহ রোগনির্ণয় বা চিকিৎসামূলক খাদ্য দেয় না।', profileSaved: 'পুষ্টির লক্ষ্য সংরক্ষিত হয়েছে।',
    today: 'আজ', netCalories: 'কার্যকলাপের পরে নেট', waterProgress: '{value} মিলি নথিভুক্ত', noData: 'এখনও যথেষ্ট তথ্য নেই।',
  },
  fil: {
    title: 'Aking nutrisyon', subtitle: 'Iyong mga naitalang pagkain at layunin', loading: 'Nilo-load ang datos sa nutrisyon…', retry: 'Subukan muli', error: 'Hindi ma-load ang datos sa nutrisyon.',
    setup: 'Itakda ang mga layunin sa nutrisyon', setupTitle: 'Magsimula sa iyong naitalang layunin', setupHint: 'Walang calorie o water target na ipinapakita hanggang ikaw mismo ang maglagay. Hindi ito kapalit ng payo ng dietitian.', save: 'I-save ang layunin', saving: 'Sine-save…',
    goal: 'Layunin', weightLoss: 'Magbawas ng timbang', maintain: 'Panatilihin ang timbang', muscleGain: 'Magdagdag ng muscle', healthy: 'Malusog na pamumuhay', height: 'Taas (cm)', weight: 'Kasalukuyang timbang (kg)', targetWeight: 'Target na timbang (kg)', calorieTarget: 'Arawang calorie target', waterTarget: 'Arawang water target (ml)', activity: 'Antas ng aktibidad', sedentary: 'Hindi aktibo', light: 'Magaan', moderate: 'Katamtaman', active: 'Aktibo', veryActive: 'Napakaaktibo', dietaryRestrictions: 'Dietary restrictions, hiwalay ng kuwit (opsyonal)', allergies: 'Food allergies, hiwalay ng kuwit (opsyonal)',
    dailyTracker: 'Arawang tracker', logMeal: 'Itala ang pagkain', logWater: 'Itala ang tubig', waterAmount: 'Dami (ml)', addWater: 'Magdagdag ng tubig', bodyGoals: 'Mga layunin sa katawan at nutrisyon',
    summary: 'Buod ngayong araw', calories: 'Calories', protein: 'Protina', carbs: 'Carbohydrates', fat: 'Taba', fiber: 'Fiber', consumed: 'Naitala', target: 'Target', remaining: 'Natitira', noTarget: 'Wala pang target', mealsLogged: '{count} pagkain ang naitala ngayon', noMeals: 'Walang pagkain na naitala sa araw na ito.', addMeal: 'Magdagdag ng pagkain', mealHistory: 'Pagkain ngayon', waterLog: 'Tubig ngayon', exercise: 'Naitalang aktibidad',
    breakfast: 'Almusal', lunch: 'Tanghalian', dinner: 'Hapunan', snack: 'Meryenda', mealType: 'Uri ng pagkain', mealName: 'Pangalan ng pagkaing kinain mo', mealNameHint: 'Halimbawa: vegetable soup', caloriesInput: 'Tunay o tinatayang calories', proteinInput: 'Protina (g, opsyonal)', carbsInput: 'Carbohydrates (g, opsyonal)', fatInput: 'Taba (g, opsyonal)', fiberInput: 'Fiber (g, opsyonal)', saveMeal: 'I-save ang pagkain', mealSaved: 'Na-save ang pagkain.', formRequired: 'Ilagay ang pangalan ng pagkain at calories.', formInvalid: 'Suriin ang mga numero bago i-save.', saveError: 'Hindi na-save ang record. Hindi nabago ang datos.', nutritionSafety: 'Ang pag-log ng pagkain ay para sa pagsubaybay lamang. Hindi nagdi-diagnose o nagbibigay ng therapeutic diet ang Nabdah.', profileSaved: 'Na-save ang nutrition goals.',
    today: 'Ngayon', netCalories: 'Net matapos ang aktibidad', waterProgress: '{value} ml naitala', noData: 'Wala pang sapat na datos.',
  },
};

export type NutritionCopyKey = keyof typeof nutritionTranslations.ar;
export function nutritionT(lang: SupportedLanguage | string, key: NutritionCopyKey, vars: Vars = {}): string {
  const template = (nutritionTranslations[lang as SupportedLanguage] || nutritionTranslations.ar)[key] || nutritionTranslations.ar[key];
  return template.replace(/\{(\w+)\}/g, (_, variable) => String(vars[variable] ?? `{${variable}}`));
}
