import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CalendarDays, ChevronLeft, FileText, MessageCircle, ShieldCheck } from "lucide-react";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { extractChatMessageSummaries, extractChatThreadSummaries } from "@/lib/api/chat";
import { getPatientChatMessages, getPatientChatThread } from "@/lib/api/chat-server";
import { requirePatientAccess } from "@/lib/auth/session";
import { isLocale } from "@/lib/i18n";
import { RetryButton } from "@/components-next/retry-button";
import styles from "../chat.module.css";
type Props={params:Promise<{locale:string;threadId:string}>};
export default async function ChatThreadPage({params}:Props){const {locale,threadId}=await params;if(!isLocale(locale)||!/^[0-9a-f-]{36}$/i.test(threadId))notFound();setRequestLocale(locale);const t=await getTranslations("ChatDetail");const token=await requirePatientAccess(locale);let threadResponse:Response;let messagesResponse:Response;try{[threadResponse,messagesResponse]=await Promise.all([getPatientChatThread(token,threadId),getPatientChatMessages(token,threadId)]);}catch{return <main className={`main ${styles.page}`}><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;}if([threadResponse,messagesResponse].some((response)=>response.status===401))redirect(`/${locale}/login`);if([threadResponse,messagesResponse].some((response)=>response.status===403||response.status===404))notFound();if([threadResponse,messagesResponse].some((response)=>!response.ok))return <main className={`main ${styles.page}`}><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;const thread=extractChatThreadSummaries({data:[await threadResponse.json().catch(()=>null)]})[0];const messages=extractChatMessageSummaries(await messagesResponse.json().catch(()=>null));return <main className={`main ${styles.page}`}><Link className={styles.activity} href={`/${locale}/chat`}><ChevronLeft size={17} aria-hidden="true"/>{t("back")}</Link><section className={styles.intro}><div className={styles.introText}><p className={styles.eyebrow}><ShieldCheck size={15} aria-hidden="true"/>{t("eyebrow")}</p><h1>{thread?t(`types.${thread.type}`):t("thread")}</h1></div><span className={styles.introIcon}><MessageCircle size={27} aria-hidden="true"/></span></section><section className={styles.grid} aria-label={t("messagesTitle")}>{messages.length?messages.map((message)=><article className={styles.card} key={message.id}><span className={styles.cardIcon}>{message.hasAttachment?<FileText size={19} aria-hidden="true"/>:<MessageCircle size={19} aria-hidden="true"/>}</span><div className={styles.cardBody}><strong className={styles.type}>{message.deleted?t("deleted"):t(`messageTypes.${message.type}`)}</strong><span className={styles.activity}><CalendarDays size={14} aria-hidden="true"/>{message.createdAt?new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(message.createdAt)):t("timeUnavailable")}</span>{message.hasAttachment?<span className={styles.activity}>{t("attachmentHidden")}</span>:null}</div></article>):<section className={styles.state}><MessageCircle size={25} aria-hidden="true"/><p>{t("empty")}</p></section>}</section><p className={styles.notice}>{t("bodyHidden")}</p></main>}
