import Link from "next/link";
import { MessageCircle, RefreshCw } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import { requirePatientAccess } from "@/lib/auth/session";
import { isLocale } from "@/lib/i18n";
import { callPatientApi } from "@/lib/api/upstream";
import { extractPatientPharmacyThreads } from "@/lib/api/pharmacy-negotiation";
import styles from "../offers.module.css";

type Props = { params: Promise<{ locale: string; orderId: string }> };
export default async function PharmacyNegotiationListPage({ params }: Props) { const { locale, orderId } = await params; if (!isLocale(locale) || !/^[0-9a-f-]{36}$/i.test(orderId)) notFound(); setRequestLocale(locale); const ar = locale === "ar"; const token = await requirePatientAccess(locale); const response = await callPatientApi(`/pharmacy/chat/threads?order_id=${encodeURIComponent(orderId)}`, {}, token); if (response.status === 401) redirect(`/${locale}/login`); if ([403, 404].includes(response.status)) notFound(); const threads = response.ok ? extractPatientPharmacyThreads(await response.json().catch(() => null)) : []; return <main className={`main ${styles.page}`}><Link className={styles.back} href={`/${locale}/orders/${orderId}/offers`}>{ar ? "العودة إلى العروض" : "Back to offers"}</Link><header className={styles.hero}><span className={styles.icon}><MessageCircle aria-hidden="true" /></span><div><p>{ar ? "تفاوض البدائل" : "Substitute negotiation"}</p><h1>{ar ? "محادثات الصيدلية" : "Pharmacy conversations"}</h1><span>{ar ? "القرار يسجل بانتظار سعر نهائي جديد من الصيدلية؛ لا ينشأ دفع داخل المحادثة." : "A decision is recorded pending a revised pharmacy final quote; no payment is created in chat."}</span></div></header>{threads.length ? <section className={styles.list}>{threads.map((thread) => <article key={thread.id} className={styles.offer}><h2>{ar ? `بند الطلب: ${thread.orderItemId ?? "—"}` : `Order item: ${thread.orderItemId ?? "—"}`}</h2><p>{thread.status ?? "—"}{thread.resolution ? ` · ${thread.resolution}` : ""}</p><Link className={styles.back} href={`/${locale}/orders/${orderId}/offers/negotiation/${thread.id}`}>{ar ? "فتح المحادثة" : "Open conversation"}</Link></article>)}</section> : <section className={styles.state}><MessageCircle aria-hidden="true" /><h2>{ar ? "لا توجد محادثات تفاوض مفتوحة" : "No open negotiation conversations"}</h2><Link className={styles.back} href={`/${locale}/orders/${orderId}/offers/negotiation`}><RefreshCw size={16} aria-hidden="true" />{ar ? "تحديث يدوياً" : "Refresh manually"}</Link></section>}</main>; }
