version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: nabdah-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.0-alpine
    container_name: nabdah-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  coturn:
    image: coturn/coturn:latest
    container_name: nabdah-coturn
    restart: always
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf

  livekit:
    image: livekit/livekit-server:latest
    container_name: nabdah-livekit
    restart: always
    network_mode: host
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    command: --config /etc/livekit.yaml

volumes:
  mongodb_data:
  redis_data:
