import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Activity, CalendarDays, ChevronLeft, Clock3, ShieldCheck } from "lucide-react";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { parseMeditationHistory } from "@/lib/api/meditation";
import { getPatientMeditationHistory } from "@/lib/api/meditation-server";
import { requirePatientAccess } from "@/lib/auth/session";
import { isLocale } from "@/lib/i18n";
import { RetryButton } from "@/components-next/retry-button";
import { SessionLogForm } from "@/components-next/session-log-form";
import styles from "../mental-health.module.css";
type Props={params:Promise<{locale:string}>};
export default async function MeditationHistoryPage({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();setRequestLocale(locale);const t=await getTranslations("MentalHealth");const token=await requirePatientAccess(locale);const response=await getPatientMeditationHistory(token);if(response.status===401)redirect(`/${locale}/login`);if(response.status===403||response.status===404)notFound();if(!response.ok)return <main className="main"><section className={styles.state} role="alert"><h1>{t("meditationHistoryUnavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;const entries=parseMeditationHistory(await response.json().catch(()=>null));return <main className="main"><Link className={styles.back} href={`/${locale}/mental-health`}><ChevronLeft size={17} aria-hidden="true"/>{t("meditationBack")}</Link><section className={styles.hero}><p className={styles.eyebrow}><ShieldCheck size={15} aria-hidden="true"/>{t("meditationEyebrow")}</p><h1>{t("meditationHistoryTitle")}</h1><p>{t("meditationHistoryNotice")}</p></section>{entries.length?<section className={styles.grid} aria-label={t("meditationHistoryTitle")}>{entries.map((entry)=><article className={styles.card} key={entry.id}><Activity size={21} aria-hidden="true"/><strong>{entry.type||t("meditationUnavailable")}</strong>{entry.durationMinutes!==undefined?<span><Clock3 size={13} aria-hidden="true"/> {entry.durationMinutes} {t("minutes")}</span>:null}{entry.completed!==undefined?<span>{entry.completed?t("completed"):t("notCompleted")}</span>:null}{entry.loggedAt?<span><CalendarDays size={13} aria-hidden="true"/> {new Intl.DateTimeFormat(locale,{dateStyle:"medium"}).format(new Date(entry.loggedAt))}</span>:null}</article>)}</section>:<section className={styles.state}><Activity size={25} aria-hidden="true"/><p>{t("meditationHistoryEmpty")}</p></section>}<SessionLogForm kind="meditation"/></main>}
