"""List every screen and control that the live QA did NOT prove, so each one gets a code-level check.

  python3 tools/audit/unverified_controls.py   -> docs/review/UNVERIFIED_CONTROLS.{json,md}

Sources (latest file per screen wins, by mtime): the crawl evidence in docs/review/evidence and
docs/review/coverage_matrix.json. A control is "unverified" when its crawl result is one of UNPROVEN below;
a screen is listed when its matrix status is not PASSED. Each screen carries its source file from
docs/review/inventory/screens.json so the check starts at the right place.
"""
import collections, glob, json, os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
EV = os.path.join(ROOT, 'docs/review/evidence')
UNPROVEN = {'NO_EFFECT', 'TAP_FAILED', 'CRAWLER_TARGET_MISSING', 'NOT_TESTED', 'SKIPPED_DESTRUCTIVE', 'JS_ERROR'}
SOURCES = {
    'patient-web': ('web_crawl_2026-10-02*.json', 'pages'),
    'admin': ('admin_crawl_2026-10-02*.json', 'pages'),
    'patient-app': ('rn_web_patient-app_2026-10-02*.json', 'routes'),
    'provider-app': ('rn_nav2_provider-app_*_2026-10-02.json', 'screens'),
}


def files_for(inv):
    out = {}
    for x in inv['patient-app']:
        out[('patient-app', x['route'].lstrip('/'))] = x['file']
    for a in ('patient-web', 'admin'):
        for x in inv[a]['pages']:
            out[(a, x['route'])] = x['file']
    for x in inv['provider-app']['registered_screens']:
        out.setdefault(('provider-app', x['name']), x['navigator_file'])
    return out


def main():
    inv = json.load(open(os.path.join(ROOT, 'docs/review/inventory/screens.json')))
    src = files_for(inv)
    screens = {}
    for app, (pat, key) in SOURCES.items():
        for f in sorted(glob.glob(os.path.join(EV, pat)), key=os.path.getmtime):
            d = json.load(open(f))
            group = os.path.basename(f).split('provider-app_')[1].split('_2026')[0] if app == 'provider-app' else ''
            for p in d.get(key) or []:
                route = p.get('route') or p.get('url')
                if app == 'patient-app':
                    route = (route or '').lstrip('/')
                bad = [{'label': (e.get('label') or '')[:60], 'result': e.get('result')}
                       for e in p.get('elements') or [] if isinstance(e, dict) and e.get('result') in UNPROVEN]
                screens[(app, group, route)] = {'controls': bad, 'evidence': os.path.basename(f)}
    matrix = json.load(open(os.path.join(ROOT, 'docs/review/coverage_matrix.json')))['rows']
    rows = []
    for r in matrix:
        if r['status'] == 'PASSED':
            continue
        app = {'website': 'patient-web'}.get(r['app'], r['app'])
        route = r['item'][4:] if r['item'].startswith('app:/') else r['item']
        if app == 'patient-app':
            route = route.lstrip('/')
        s = screens.get((app, r.get('group') or '', route)) or screens.get((app, '', route)) or {'controls': [], 'evidence': r.get('evidence')}
        rows.append({'app': app, 'group': r.get('group') or '', 'screen': route, 'status': r['status'], 'detail': r.get('detail', ''),
                     'file': src.get((app, route)), 'unverified_controls': s['controls'],
                     'evidence': s['evidence']})
    json.dump({'rows': rows}, open(os.path.join(ROOT, 'docs/review/UNVERIFIED_CONTROLS.json'), 'w'), ensure_ascii=False, indent=1)
    tot = collections.Counter()
    for r in rows:
        for c in r['unverified_controls']:
            tot[(r['app'], c['result'])] += 1
    lines = ['# Unverified screens and controls (code-level check required)', '',
             'Generated by `tools/audit/unverified_controls.py` from the 2026-10-02 crawl evidence and the coverage matrix.',
             'Every row is a screen that is not PASSED; its controls are the ones the crawler could not prove.', '',
             '| App | Result | Controls |', '|---|---|---|']
    lines += [f'| {a} | {k} | {n} |' for (a, k), n in sorted(tot.items())]
    lines += ['', '| App | Group | Screen | Status | Source | Unverified controls |', '|---|---|---|---|---|---|']
    for r in rows:
        ctl = '; '.join(f"{c['label'] or '(no label)'}={c['result']}" for c in r['unverified_controls'][:12])
        more = len(r['unverified_controls']) - 12
        ctl += f' (+{more})' if more > 0 else ''
        lines.append(f"| {r['app']} | {r['group']} | `{r['screen']}` | {r['status']} | `{r['file'] or '?'}` | {ctl.replace('|', '/')} |")
    open(os.path.join(ROOT, 'docs/review/UNVERIFIED_CONTROLS.md'), 'w').write('\n'.join(lines) + '\n')
    print(f'{len(rows)} screens, {sum(tot.values())} unverified controls')
    for k, n in sorted(tot.items()):
        print(' ', k, n)


if __name__ == '__main__':
    main()
