from __future__ import annotations
import csv
from pathlib import Path

ROOT=Path('/home/ubuntu/nabdah_impl/repo'); OUT=ROOT/'audit-artifacts/comprehensive-audit-20260823'
rows=list(csv.DictReader((OUT/'mobile_web_screen_gap_matrix.tsv').open(encoding='utf-8'),delimiter='\t'))
priority={
 '(auth)':('P0','Web + Backend','Identity, OTP, registration, guest/session parity'), '(onboarding)':('P1','Web','Onboarding, language, permissions'), '(tabs)':('P0','Web','Primary patient navigation and dashboard'),
 'consultations':('P0','Web + Backend','Booking, payment, cancel, reschedule, call room'), 'diagnostics':('P0','Web + Backend','Lab/radiology booking, cart, uploads, results'), 'pharmacy':('P0','Web + Backend','Cart, checkout, prescription, fulfillment, returns'), 'orders':('P0','Web + Backend','Order confirmation, tracking, reorder, refund'), 'home-care':('P0','Web + Backend','Service/provider/address/visit booking and tracking'), 'nursing':('P0','Web + Backend','Visit booking, broadcast, GPS, reports'),
 'family':('P1','Web + Backend','Members, permissions, ownership'), 'profile':('P1','Web + Backend','Profile edit, addresses, insurance'), 'insurance':('P1','Web + Backend','Policies, OCR, claims, approvals'), 'health':('P1','Web + Backend','Authoritative history, vitals, reports'), 'reports':('P1','Web + Backend','Reports, timeline, downloads, AI analysis'), 'mental-health':('P1','Web','Mood, meditation, breathing, crisis'), 'nutrition':('P1','Web + Backend','Meal log and plans'), 'settings':('P1','Web','Security, privacy, language, support'), 'notifications':('P1','Web + Backend','Read state, settings, realtime'), 'support':('P1','Web + Backend','Chat/tickets'),
 'ai':('P2','Backend + Medical/Safety','AI contracts, guardrails, auditability'), 'ai-assistant.tsx':('P2','Backend + Medical/Safety','AI triage/chat safety'), 'community':('P2','Web + Backend','Posts, votes, moderation'), 'loyalty':('P2','Web + Backend','Points, offers, redemption'), 'wallet':('P0','Backend + Finance/Security','Cards, topup, transfer, transactions'), 'payments':('P0','Backend + Finance/Security','Payment methods and reconciliation'), 'emergency':('P0','Web + Backend + Medical','SOS/call routing and escalation'), 'maternity':('P2','Backend + Medical','Programs and dashboards'), 'voice':('P2','Backend + Privacy','Voice contract and consent'), 'wearables':('P2','Backend + Privacy','Device permissions and sync'), 'returns':('P1','Web + Backend','Return request, status, refund'), 'drug-scanner':('P1','Web + Backend','Scan/upload and medicine resolution'), 'offers':('P2','Web + Backend','Offers and eligibility'), 'reviews':('P2','Web + Backend','Review submission/moderation'), 'delivery':('P1','Web + Backend','Delivery tracking'), 'search':('P1','Web + Backend','Search contract and filters'), 'articles':('P1','Web + Backend','Article detail, bookmarks, related content'), 'programs':('P2','Web + Backend','Program enrollment and progress'), 'map':('P1','Web + Backend','Location picker and privacy'), 'room':('P0','Web + Realtime Backend','Call room and token lifecycle'), 'shared':('P1','Web','Reusable patient components'), 'services':('P1','Web + Backend','Service discovery'), 'settings':('P1','Web','Settings and policies'),
}
with (OUT/'gap_owner_priority_matrix.tsv').open('w',encoding='utf-8',newline='') as f:
    fields=['mobile_file','domain','status','priority','owner','scope','action_markers','navigation_markers','web_route_candidates','evidence_required']
    w=csv.DictWriter(f,fieldnames=fields,delimiter='\t'); w.writeheader()
    for r in rows:
        p,o,s=priority.get(r['domain'],('P2','Web + Backend','Needs capability review'))
        w.writerow({'mobile_file':r['mobile_file'],'domain':r['domain'],'status':r['status'],'priority':p,'owner':o,'scope':s,'action_markers':r['mobile_action_markers'],'navigation_markers':r['mobile_navigation_markers'],'web_route_candidates':r['web_route_candidates'],'evidence_required':r['evidence_required']})
print({'rows':len(rows),'p0':sum(priority.get(r['domain'],('P2','',''))[0]=='P0' for r in rows),'p1':sum(priority.get(r['domain'],('P2','',''))[0]=='P1' for r in rows),'p2':sum(priority.get(r['domain'],('P2','',''))[0]=='P2' for r in rows)})
