/var/log/nabdah-*.log /var/log/nginx/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su root root
}

/var/lib/docker/containers/*/*.log {
    daily
    rotate 5
    compress
    missingok
    copytruncate
    maxsize 50M
}
