/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Written by tools/design/sync-client-tokens.mjs from
 * packages/design-tokens/tokens.json. Run `npm run sync-client-tokens` in
 * packages/design-tokens after a token change; `--check` in CI fails if this
 * file drifts.
 *
 * Client: provider-app
 */

export const light = {
  green50: "var(--nabd-status.success.bg-light)",
  green100: "var(--nabd-status.success.bg-light)",
  green200: "var(--nabd-status.success.bg-light)",
  green500: "var(--nabd-status.success.fg-light)",
  green600: "var(--nabd-status.success.fg-light)",
  green700: "var(--nabd-status.success.fg-light)",
  green800: "var(--nabd-status.success.fg-light)",
  greenNeon: "var(--nabd-status.success.fill-light)",
  blue500: "var(--nabd-status.info.fg-light)",
  blueLight: "var(--nabd-status.info.bg-light)",
  orange500: "var(--nabd-status.warning.fg-light)",
  orangeLight: "var(--nabd-status.warning.bg-light)",
  red500: "var(--nabd-status.danger.fg-light)",
  redLight: "var(--nabd-status.danger.bg-light)",
  yellow500: "var(--nabd-text.link-dark)",
  yellowLight: "rgba(215,255,0,0.16)",
  purple500: "var(--nabd-service.radiology.glyph-dark)",
  purpleLight: "var(--nabd-status.info.bg-light)",
  teal500: "var(--nabd-status.success.fg-light)",
  tealLight: "var(--nabd-status.success.bg-light)",
  pink500: "var(--nabd-service.mind.glyph-dark)",
  pinkLight: "var(--nabd-status.danger.bg-light)",
  white: "var(--nabd-bg.surface-light)",
  black: "var(--nabd-bg.canvas-dark)",
  g50: "var(--nabd-bg.sunken-light)",
  g100: "var(--nabd-bg.sunken-light)",
  g150: "var(--nabd-bg.surface-light)",
  g200: "var(--nabd-border.subtle-light)",
  g300: "var(--nabd-border.strong-light)",
  g400: "var(--nabd-text.tertiary-light)",
  g500: "var(--nabd-text.secondary-light)",
  g600: "var(--nabd-text.secondary-light)",
  g700: "var(--nabd-bg.canvas-dark)",
  g800: "var(--nabd-bg.canvas-dark)",
  g900: "var(--nabd-bg.canvas-dark)",
  d900: "var(--nabd-bg.canvas-dark)",
  d800: "var(--nabd-bg.canvas-dark)",
  d750: "var(--nabd-bg.canvas-dark)",
  d700: "var(--nabd-bg.canvas-dark)",
  d650: "var(--nabd-bg.surface-light)",
  d600: "var(--nabd-bg.surface-light)",
  d500: "var(--nabd-border.strong-light)",
  dBdr: "var(--nabd-border.strong-light)",
} as const;

export const dark = {
  green50: "rgba(111,224,184,0.14)",
  green100: "rgba(111,224,184,0.14)",
  green200: "rgba(111,224,184,0.14)",
  green500: "var(--nabd-status.success.fg-dark)",
  green600: "var(--nabd-status.success.fg-dark)",
  green700: "var(--nabd-status.success.fg-dark)",
  green800: "var(--nabd-status.success.fg-dark)",
  greenNeon: "var(--nabd-status.success.fill-light)",
  blue500: "var(--nabd-status.info.fg-dark)",
  blueLight: "rgba(110,139,255,0.16)",
  orange500: "var(--nabd-status.warning.fg-dark)",
  orangeLight: "rgba(255,209,102,0.14)",
  red500: "var(--nabd-status.danger.fg-dark)",
  redLight: "rgba(255,107,115,0.14)",
  yellow500: "var(--nabd-text.link-dark)",
  yellowLight: "rgba(215,255,0,0.16)",
  purple500: "var(--nabd-service.radiology.glyph-dark)",
  purpleLight: "rgba(110,139,255,0.16)",
  teal500: "var(--nabd-status.success.fg-dark)",
  tealLight: "rgba(111,224,184,0.14)",
  pink500: "var(--nabd-service.mind.glyph-dark)",
  pinkLight: "rgba(255,107,115,0.14)",
  white: "var(--nabd-bg.surface-dark)",
  black: "var(--nabd-bg.canvas-dark)",
  g50: "var(--nabd-bg.sunken-dark)",
  g100: "var(--nabd-bg.sunken-dark)",
  g150: "var(--nabd-bg.elevated-dark)",
  g200: "rgba(255,255,255,0.10)",
  g300: "rgba(255,255,255,0.20)",
  g400: "var(--nabd-text.tertiary-dark)",
  g500: "var(--nabd-text.secondary-dark)",
  g600: "var(--nabd-text.secondary-dark)",
  g700: "var(--nabd-bg.canvas-light)",
  g800: "var(--nabd-bg.canvas-light)",
  g900: "var(--nabd-bg.canvas-dark)",
  d900: "var(--nabd-bg.surface-dark)",
  d800: "var(--nabd-bg.surface-dark)",
  d750: "var(--nabd-bg.surface-dark)",
  d700: "var(--nabd-bg.surface-dark)",
  d650: "var(--nabd-bg.elevated-dark)",
  d600: "var(--nabd-bg.elevated-dark)",
  d500: "rgba(255,255,255,0.20)",
  dBdr: "rgba(255,255,255,0.20)",
} as const;

export type Palette = typeof light;
export type PaletteName = keyof Palette;
