import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FileText, ChevronLeft, ChevronRight, Search } from "lucide-react";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { getPublicArticleCategories, getPublicArticles } from "@/lib/api/articles-server";
import { parseArticleCategories, parseArticleList } from "@/lib/api/articles";
import { isLocale, locales } from "@/lib/i18n";
import { RetryButton } from "@/components-next/retry-button";
import styles from "./articles.module.css";
type Props={params:Promise<{locale:string}>;searchParams?:Promise<{q?:string;category?:string}>};
export async function generateMetadata({ params }: Omit<Props, "searchParams">): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; const t = await getTranslations({ locale, namespace: "Articles" }); const origin = process.env.NEXT_PUBLIC_SITE_ORIGIN || "https://nabd.plus"; return { title: t("title"), description: t("notice"), alternates: { canonical: `${origin}/${locale}/articles`, languages: Object.fromEntries(locales.map((supportedLocale) => [supportedLocale, `${origin}/${supportedLocale}/articles`])) }, robots: { index: true, follow: true } }; }
export default async function ArticlesPage({params,searchParams}:Props){const {locale}=await params;if(!isLocale(locale))notFound();setRequestLocale(locale);const t=await getTranslations("Articles");const Chevron=locale==="ar"||locale==="ur"?ChevronLeft:ChevronRight;const query=searchParams?await searchParams:{};const [response,categoriesResponse]=await Promise.all([getPublicArticles({q:query.q,category:query.category}),getPublicArticleCategories()]);if(!response||!response.ok)return <main className="main"><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;const articles=parseArticleList(await response.json().catch(()=>null));const categories=categoriesResponse?.ok?parseArticleCategories(await categoriesResponse.json().catch(()=>null)):[];return <main className={`main ${styles.page}`}><section className={styles.hero}><p className={styles.eyebrow}><FileText size={15} aria-hidden="true"/>{t("eyebrow")}</p><h1>{t("title")}</h1><p>{t("notice")}</p><form className={styles.search} method="get"><Search size={18} aria-hidden="true"/><input name="q" defaultValue={query.q||""} maxLength={80} placeholder={t("searchPlaceholder")} aria-label={t("searchPlaceholder")}/><button type="submit">{t("search")}</button></form>{categories.length?<nav className={styles.chips} aria-label={t("categories")}>{categories.map((category)=><Link className={query.category===category?styles.chipActive:styles.chip} key={category} href={`/${locale}/articles?category=${encodeURIComponent(category)}`}><span dir="auto">{category}</span></Link>)}</nav>:null}</section>{articles.length?<section className={styles.list}>{articles.map((article)=><Link className={styles.card} key={article.slug} href={`/${locale}/articles/${article.slug}`}><span className={styles.icon}><FileText size={20} aria-hidden="true"/></span><span className={styles.copy}><strong dir="auto">{locale==="ar"?article.titleAr||article.titleEn:article.titleEn||article.titleAr||t("untitled")}</strong><span dir="auto">{article.category||t("categoryUnavailable")}</span></span><Chevron className={styles.arrow} size={18} aria-hidden="true"/></Link>)}</section>:<section className={styles.empty}><FileText size={34} aria-hidden="true"/><h2>{t("noResultsTitle")}</h2><p>{query.q||query.category?t("noResults"):t("empty")}</p></section>}</main>}
