import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Icon } from "@/components-next/ui-generated/src/Icon";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { getPatientEmergencyContacts } from "@/lib/api/emergency-contacts-server";
import { parseEmergencyContacts } from "@/lib/api/emergency-contacts";
import { requirePatientAccess } from "@/lib/auth/session";
import { isLocale } from "@/lib/i18n";
import { RetryButton } from "@/components-next/retry-button";
import { VectorEmergency } from "@/components-next/vector-illustrations";
import styles from "../health.module.css";
type Props={params:Promise<{locale:string}>};
export default async function EmergencyContactsPage({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();setRequestLocale(locale);const t=await getTranslations("EmergencyContacts");const token=await requirePatientAccess(locale);let response:Response;try{response=await getPatientEmergencyContacts(token);}catch{return <main className={`main ${styles.page}`}><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;}if(response.status===401)redirect(`/${locale}/login`);if(response.status===403||response.status===404)notFound();if(!response.ok)return <main className={`main ${styles.page}`}><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;const contacts=parseEmergencyContacts(await response.json().catch(()=>null));return <main className={`main ${styles.page}`}><Link className={styles.back} href={`/${locale}/health`}><Icon name="caret-left" size={17} />{t("back")}</Link><section className={styles.hero}><div><p className={styles.eyebrow}><Icon name="shield-check" size={15} />{t("eyebrow")}</p><h1>{t("title")}</h1></div><span className={styles.heroIcon}><VectorEmergency size={38} aria-hidden="true"/></span></section>{contacts.length?<section className={styles.grid} aria-label={t("title")}>{contacts.map((contact,index)=><article className={styles.card} key={contact.id||`${contact.name}-${index}`}><div className={styles.cardTop}><span>{contact.isPrimary?t("primary"):t("contact")}</span><span className={styles.glyph}><Icon name="user-round" size={18} /></span></div><p className={styles.value}>{contact.name}</p>{contact.relation?<p className={styles.date}>{contact.relation}</p>:null}<p className={styles.date}><Icon name="phone" size={14} />{contact.maskedPhone}</p></article>)}</section>:<section className={styles.state}><Icon name="phone" size={25} /><p>{t("empty")}</p></section>}<p className={styles.notice}>{t("notice")}</p></main>}
