export enum ProcurementStatus {
  DRAFT = 'DRAFT',
  PENDING_ADMIN_REVIEW = 'PENDING_ADMIN_REVIEW',
  QUOTATION_ISSUED = 'QUOTATION_ISSUED',
  APPROVED_BY_PHARMACY = 'APPROVED_BY_PHARMACY',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}
