import Link from "next/link";
import type { Metadata } from "next";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { JsonLd } from "@/components-next/json-ld";
import { isLocale } from "@/lib/i18n";
import { localizedUrl, siteOrigin } from "@/lib/seo";
type Props = { params: Promise<{ locale: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; const t = await getTranslations({ locale, namespace: "Metadata" }); const canonical = localizedUrl(locale); return { title: t("portalTitle"), description: t("publicDescription"), alternates: { canonical, languages: { ar: localizedUrl("ar"), en: localizedUrl("en"), "x-default": localizedUrl("ar") } }, robots: { index: true, follow: true } }; }
export default async function LandingPage({ params }: Props) { const { locale } = await params; if (!isLocale(locale)) return null; setRequestLocale(locale); const t = await getTranslations("Home"); const metadata = await getTranslations("Metadata"); const url = localizedUrl(locale); return <main className="main"><JsonLd data={[{ "@context": "https://schema.org", "@type": "WebSite", name: metadata("siteTitle"), url: siteOrigin(), inLanguage: locale }, { "@context": "https://schema.org", "@type": "MedicalOrganization", name: metadata("siteTitle"), url: siteOrigin() }, { "@context": "https://schema.org", "@type": "MedicalWebPage", name: metadata("portalTitle"), url, inLanguage: locale, isPartOf: { "@type": "WebSite", url: siteOrigin() } }]} /><section className="hero"><div><div className="eyebrow">{t("eyebrow")}</div><h1>{t("title")}</h1><p>{t("body")}</p><div className="hero-actions"><Link className="button button-primary" href={`/${locale}/login`}>{t("signIn")}</Link><Link className="button button-secondary" href={`/${locale}/medicine-catalog`}>{t("medicineCatalog")}</Link></div></div><aside className="trust-card"><h2>{t("safeguards")}</h2><p>{t("safeBody")}</p><ul className="trust-list"><li><span>01</span>{t("safetyOne")}</li><li><span>02</span>{t("safetyTwo")}</li><li><span>03</span>{t("safetyThree")}</li></ul></aside></section></main>; }
