import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CalendarDays, ChevronLeft, Clock3, Pill, ShieldCheck } from "lucide-react";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { getPatientChronicMedications } from "@/lib/api/chronic-meds-server";
import { parseChronicMedications } from "@/lib/api/chronic-meds";
import { requirePatientAccess } from "@/lib/auth/session";
import { isLocale } from "@/lib/i18n";
import { RetryButton } from "@/components-next/retry-button";
import styles from "../health.module.css";
type Props={params:Promise<{locale:string}>};
export default async function ChronicMedicationsPage({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();setRequestLocale(locale);const t=await getTranslations("ChronicMedications");const token=await requirePatientAccess(locale);let response:Response;try{response=await getPatientChronicMedications(token);}catch{return <main className={`main ${styles.page}`}><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;}if(response.status===401)redirect(`/${locale}/login`);if(response.status===403||response.status===404)notFound();if(!response.ok)return <main className={`main ${styles.page}`}><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;const meds=parseChronicMedications(await response.json().catch(()=>null));return <main className={`main ${styles.page}`}><Link className={styles.back} href={`/${locale}/health`}><ChevronLeft size={17} aria-hidden="true"/>{t("back")}</Link><section className={styles.hero}><div><p className={styles.eyebrow}><ShieldCheck size={15} aria-hidden="true"/>{t("eyebrow")}</p><h1>{t("title")}</h1></div><span className={styles.heroIcon}><Pill size={27} aria-hidden="true"/></span></section>{meds.length?<section className={styles.grid} aria-label={t("title")}>{meds.map((med)=><article className={styles.card} key={med.id}><div className={styles.cardTop}><span>{med.active?t("active"):t("inactive")}</span><span className={styles.glyph}><Pill size={18} aria-hidden="true"/></span></div><p className={styles.value}>{med.name||t("unnamed")}</p>{med.dose?<p className={styles.date}>{med.dose}</p>:null}{med.frequency?<p className={styles.date}><Clock3 size={14} aria-hidden="true"/>{med.frequency}{med.times.length?` · ${med.times.join(", ")}`:""}</p>:null}{med.refillDate?<p className={styles.date}><CalendarDays size={14} aria-hidden="true"/>{t("refillDate")}: {med.refillDate}{med.daysUntilRefill!==undefined?` · ${med.daysUntilRefill} ${t("days")}`:""}</p>:null}{med.pillsRemaining!==undefined?<p className={styles.date}>{t("remaining")}: {med.pillsRemaining}</p>:null}</article>)}</section>:<section className={styles.state}><Pill size={25} aria-hidden="true"/><p>{t("empty")}</p></section>}<p className={styles.notice}>{t("notice")}</p></main>}
