import { Injectable } from '@nestjs/common';
const PdfPrinter = require('pdfmake/js/printer').default;

@Injectable()
export class LabPdfService {
  private fonts = {
    Roboto: {
      normal: 'Helvetica',
      bold: 'Helvetica-Bold',
      italics: 'Helvetica-Oblique',
      bolditalics: 'Helvetica-BoldOblique'
    }
  };

  private printer = new PdfPrinter(this.fonts);

  async generateReport(booking: any, structuredData: any[]): Promise<string> {
    return new Promise((resolve, reject) => {
      const docDefinition = {
        content: [
          { text: 'Nabdah Medical Laboratory', style: 'header' },
          { text: `Patient: ${booking.patient_name || 'Unknown Patient'}`, style: 'subheader' },
          { text: `Date: ${new Date().toLocaleDateString()}`, style: 'subheader' },
          { text: '\n' },
          {
            table: {
              headerRows: 1,
              widths: ['*', 'auto', 'auto', 'auto'],
              body: [
                ['Test (Analyte)', 'Result', 'Unit', 'Ref. Range'],
                ...structuredData.map(entry => [
                  entry.analyte,
                  { text: entry.value, color: entry.isCritical ? 'red' : 'black', bold: entry.isCritical },
                  entry.unit,
                  entry.range
                ])
              ]
            }
          },
          { text: '\n\n** Electronically generated by Nabdah Plus Platform **', alignment: 'center', fontSize: 10, color: 'gray' }
        ],
        styles: {
          header: { fontSize: 22, bold: true, alignment: 'center', margin: [0, 0, 0, 10] },
          subheader: { fontSize: 14, margin: [0, 5, 0, 5] }
        },
        defaultStyle: { font: 'Roboto' }
      };

      try {
        const pdfDoc = this.printer.createPdfKitDocument(docDefinition as any);
        const chunks: Buffer[] = [];
        pdfDoc.on('data', chunk => chunks.push(chunk));
        pdfDoc.on('end', () => {
          const result = Buffer.concat(chunks);
          const base64 = result.toString('base64');
          resolve(`data:application/pdf;base64,${base64}`);
        });
        pdfDoc.on('error', (err) => reject(err));
        pdfDoc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}
