import { Injectable } from '@nestjs/common';

// pdfkit is a direct dependency (pdfmake wraps it); using it directly avoids
// pdfmake's font/url resolver path which both mis-rendered and crashed the
// process with an unhandled exception (production incident class).
const PDFDocument = require('pdfkit');

@Injectable()
export class LabPdfService {
  /**
   * Generate a structured lab report PDF and return it as a data-URI base64 string.
   * Never throws into the event loop: all errors reject the returned promise.
   */
  async generateReport(booking: any, structuredData: any[]): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const chunks: Buffer[] = [];
        doc.on('data', (chunk: Buffer) => chunks.push(chunk));
        doc.on('end', () => {
          resolve(`data:application/pdf;base64,${Buffer.concat(chunks).toString('base64')}`);
        });
        doc.on('error', (err: any) => reject(err));

        // Header
        doc.fontSize(20).font('Helvetica-Bold').text('Nabdah Medical Laboratory', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(12).font('Helvetica')
          .text(`Patient: ${booking.patient_name || 'Unknown Patient'}`)
          .text(`Booking: ${booking.id || ''}`)
          .text(`Date: ${new Date().toISOString().slice(0, 10)}`);
        doc.moveDown(1);

        // Results table (simple columnar layout)
        const colX = [50, 250, 330, 430];
        const headers = ['Test (Analyte)', 'Result', 'Unit', 'Ref. Range'];
        doc.font('Helvetica-Bold').fontSize(11);
        headers.forEach((h, i) => doc.text(h, colX[i], doc.y, { continued: i < headers.length - 1, width: colX[i + 1] ? colX[i + 1] - colX[i] - 10 : 120 }));
        doc.moveDown(0.3);
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown(0.3);
        doc.font('Helvetica').fontSize(10);

        for (const entry of structuredData || []) {
          const y = doc.y;
          if (y > 750) doc.addPage();
          doc.text(String(entry.analyte ?? ''), colX[0], doc.y, { width: 190 });
          const resultColor = entry.isCritical ? 'red' : 'black';
          doc.fillColor(resultColor).text(String(entry.value ?? ''), colX[1], y, { width: 70 });
          doc.fillColor('black');
          doc.text(String(entry.unit ?? ''), colX[2], y, { width: 90 });
          doc.text(String(entry.range ?? entry.reference ?? ''), colX[3], y, { width: 110 });
          doc.moveDown(0.4);
        }

        doc.moveDown(2);
        doc.fontSize(9).fillColor('gray')
          .text('** Electronically generated by Nabdah Plus Platform **', { align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}
