"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { CreditCard, ExternalLink, LoaderCircle, RefreshCw, ShieldCheck } from "lucide-react";
import type { InsuranceRequest } from "@/lib/api/insurance-request";
import { isHttpsCheckoutUrl } from "@/lib/api/checkout-url";
import styles from "./appointment-booking-form.module.css";

type Method = "card" | "apple-pay" | "google-pay";
type Mode = "copay" | "self-pay";
type Capabilities = { booking_id: string; amount: number; currency: "SAR"; purpose: "insurance_copay" | "insurance_self_pay"; methods: Array<{ id: Method; kind: "online" }> };
function methodLabel(method: Method) { return method === "apple-pay" ? "Apple Pay" : method === "google-pay" ? "Google Pay" : "بطاقة"; }

export function ConsultationInsuranceDecision({ request }: { request: InsuranceRequest }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [capabilities, setCapabilities] = useState<Capabilities | null>(null); const [mode, setMode] = useState<Mode | null>(null);
  const refresh = () => router.refresh();
  async function loadCapabilities(nextMode: Mode) { if (loading) return; setLoading(true); setMessage(null); setCapabilities(null); try { const response = await fetch(`/api/insurance/requests/${request.id}/payment-capabilities?mode=${nextMode}`, { cache: "no-store" }); const data = await response.json().catch(() => null); if (!response.ok || !data) { setMessage("لا توجد عملية دفع إلكترونية متاحة لهذه الحالة حالياً."); return; } setCapabilities(data as Capabilities); setMode(nextMode); } catch { setMessage("تعذر جلب خيارات الدفع. أعد التحديث يدوياً."); } finally { setLoading(false); } }
  async function acceptSelfPay() { if (loading) return; setLoading(true); setMessage(null); try { const response = await fetch(`/api/insurance/requests/${request.id}/accept-self-pay`, { method: "POST", headers: { "idempotency-key": crypto.randomUUID() } }); if (!response.ok) { setMessage("تعذر تسجيل اختيار الدفع الذاتي. لم يتم إنشاء أي عملية دفع."); return; } refresh(); } catch { setMessage("تعذر تسجيل اختيار الدفع الذاتي. أعد المحاولة يدوياً."); } finally { setLoading(false); } }
  async function begin(method: Method) { if (loading || !mode || !capabilities?.methods.some((item) => item.id === method)) return; setLoading(true); setMessage(null); try { const response = await fetch(`/api/insurance/requests/${request.id}/payment-intent`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ method }) }); const data = await response.json().catch(() => null); if (!response.ok || !isHttpsCheckoutUrl(data?.checkoutUrl)) { setMessage("تعذر بدء الدفع الإلكتروني بأمان. لم يتم تأكيد أي دفع."); return; } window.location.assign(data.checkoutUrl); } catch { setMessage("تعذر بدء الدفع الإلكتروني. لم يتم تأكيد أي دفع."); } finally { setLoading(false); } }
  const showCapabilities = request.state === "COPAY_PENDING" ? () => loadCapabilities("copay") : request.state === "SELF_PAY_PENDING" ? () => loadCapabilities("self-pay") : null;
  return <section className={styles.panel} aria-labelledby="insurance-decision-title"><div className={styles.heading}><div><p className={styles.eyebrow}><ShieldCheck size={15} aria-hidden="true" />قرار التأمين</p><h2 id="insurance-decision-title">{request.state}</h2></div><button type="button" className={styles.slot} onClick={refresh} disabled={loading}><RefreshCw size={16} aria-hidden="true" />تحديث الحالة</button></div>{request.state === "APPROVED_FULL" ? <p className={styles.muted}>التغطية كاملة وفق القرار الخادمي. لا تُنشأ عملية دفع.</p> : null}{request.state === "PENDING_PROVIDER_REVIEW" ? <p className={styles.muted}>الطلب قيد مراجعة مزود الخدمة. لا توجد عملية دفع أو تأكيد قبل القرار الخادمي.</p> : null}{request.state === "REJECTED" ? <><p className={styles.error}>رُفض طلب التأمين: {request.rejectionReason || "لم يحدد مزود الخدمة سبباً عاماً."}</p><button type="button" className={styles.submit} onClick={acceptSelfPay} disabled={loading}>{loading ? <LoaderCircle className={styles.spinner} size={18} aria-hidden="true" /> : <CreditCard size={18} aria-hidden="true" />}قبول الدفع الذاتي</button></> : null}{showCapabilities ? <><p className={styles.muted}>{request.state === "COPAY_PENDING" ? "يُعرض فقط مبلغ التحمل المحدد من الخادم." : "يُعرض فقط مبلغ الدفع الذاتي المقبول خادمياً."}</p><button type="button" className={styles.submit} onClick={showCapabilities} disabled={loading}>{loading ? <LoaderCircle className={styles.spinner} size={18} aria-hidden="true" /> : <CreditCard size={18} aria-hidden="true" />}عرض خيارات الدفع الآمنة</button></> : null}{capabilities ? <><p className={styles.muted}>المبلغ المحدد من الخادم: {capabilities.amount} {capabilities.currency}</p><div className={styles.slotGrid}>{capabilities.methods.map((item) => <button type="button" className={styles.slot} key={item.id} onClick={() => begin(item.id)} disabled={loading}>{loading ? <LoaderCircle className={styles.spinner} size={16} aria-hidden="true" /> : <ExternalLink size={16} aria-hidden="true" />}{methodLabel(item.id)}</button>)}</div>{capabilities.methods.length === 0 ? <p className={styles.muted}>لا توجد وسيلة إلكترونية مفعّلة لهذه البوابة والجهاز.</p> : null}</> : null}{message ? <p className={styles.error} role="alert">{message}</p> : null}</section>;
}
