"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, MailCheck, LoaderCircle } from "lucide-react";
import type { Locale } from "@/lib/i18n";
import styles from "./login-form.module.css";

const copy: Record<Locale,{title:string;body:string;identifier:string;submit:string;busy:string;success:string;failed:string;back:string}>={
 ar:{title:"استعادة كلمة المرور",body:"أدخل بريدك الإلكتروني أو رقم جوالك. إذا كان الحساب مسجلاً، ستصلك تعليمات الاستعادة.",identifier:"البريد الإلكتروني أو رقم الجوال",submit:"إرسال التعليمات",busy:"جارٍ الإرسال…",success:"تم طلب التعليمات. تحقق من وسيلة التواصل المسجلة.",failed:"تعذر إرسال الطلب. لم يتم تغيير كلمة المرور.",back:"العودة إلى الدخول"},
 en:{title:"Reset your password",body:"Enter your email or mobile number. If an account exists, recovery instructions will be sent.",identifier:"Email or mobile number",submit:"Send instructions",busy:"Sending…",success:"Recovery requested. Check your registered contact method.",failed:"The request could not be sent. Your password was not changed.",back:"Back to sign in"},
 fil:{title:"I-reset ang password",body:"Ilagay ang email o mobile. Kung may account, ipapadala ang instructions.",identifier:"Email o mobile number",submit:"Ipadala ang instructions",busy:"Ipinapadala…",success:"Na-request ang recovery. Suriin ang registered contact.",failed:"Hindi naipadala ang request. Hindi nabago ang password.",back:"Bumalik sa login"},
 hi:{title:"पासवर्ड रीसेट करें",body:"ईमेल या मोबाइल नंबर दर्ज करें। खाता होने पर निर्देश भेजे जाएंगे।",identifier:"ईमेल या मोबाइल नंबर",submit:"निर्देश भेजें",busy:"भेजा जा रहा है…",success:"रिकवरी का अनुरोध किया गया। पंजीकृत संपर्क जांचें।",failed:"अनुरोध नहीं भेजा जा सका। पासवर्ड नहीं बदला गया।",back:"लॉगिन पर लौटें"},
 ur:{title:"پاس ورڈ ری سیٹ",body:"ای میل یا موبائل نمبر درج کریں۔ اکاؤنٹ موجود ہونے پر ہدایات بھیجی جائیں گی۔",identifier:"ای میل یا موبائل نمبر",submit:"ہدایات بھیجیں",busy:"بھیجا جا رہا ہے…",success:"ریکوری کی درخواست ہو گئی۔ رجسٹرڈ رابطہ دیکھیں۔",failed:"درخواست نہیں بھیجی جا سکی۔ پاس ورڈ تبدیل نہیں ہوا۔",back:"لاگ اِن پر واپس جائیں"},
 bn:{title:"পাসওয়ার্ড রিসেট",body:"ইমেল বা মোবাইল নম্বর দিন। অ্যাকাউন্ট থাকলে নির্দেশনা পাঠানো হবে।",identifier:"ইমেল বা মোবাইল নম্বর",submit:"নির্দেশনা পাঠান",busy:"পাঠানো হচ্ছে…",success:"রিকভারি অনুরোধ করা হয়েছে। নিবন্ধিত যোগাযোগ দেখুন।",failed:"অনুরোধ পাঠানো যায়নি। পাসওয়ার্ড পরিবর্তন হয়নি।",back:"লগইনে ফিরুন"}
};
export function ForgotPasswordForm({locale}:{locale:Locale}){const t=copy[locale];const router=useRouter();const [identifier,setIdentifier]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);async function submit(event:FormEvent){event.preventDefault();if(identifier.trim().length<3){setMessage(t.failed);return;}setBusy(true);setMessage(null);try{const response=await fetch("/api/auth/password/forgot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identifier})});setMessage(response.ok?t.success:t.failed);}catch{setMessage(t.failed)}finally{setBusy(false)}}return <div className={styles.shell}><button className={styles.textLink} type="button" onClick={()=>router.push(`/${locale}/login`)}><ArrowLeft size={15}/>{t.back}</button><div className={styles.brandHero}><MailCheck size={26}/><div><span className={styles.brandName}>{t.title}</span><span className={styles.brandTagline}>Nabd Plus</span></div></div><p className={styles.description}>{t.body}</p><form className={styles.form} onSubmit={submit} aria-busy={busy}><label className={styles.field}><span>{t.identifier}</span><input required value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username" /></label>{message?<p className={styles.error} role="status">{message}</p>:null}<button className={styles.submit} disabled={busy}>{busy?<LoaderCircle className={styles.spinner} size={18}/>:null}{busy?t.busy:t.submit}</button></form></div>}
