import { useCallback, useEffect, useRef, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { adminFetch, apiErrorMessage } from '@/lib/admin-client';

type Snapshot = { ts: string; tiles: { orders_active: number; labs_active: number; radiology_active: number; nursing_active: number; appointments_today: number; sos_open: number; tickets_open: number; revenue_24h_sar: number; payments_24h: number; sla_breach_total: number } };
const tileInfo: Array<{ key: keyof Snapshot['tiles']; label: string; href?: string; accent: string }> = [
  { key: 'orders_active', label: 'طلبات نشطة', href: '/admin/orders', accent: 'border-teal-500' }, { key: 'labs_active', label: 'تحاليل نشطة', href: '/admin/orders?kind=lab', accent: 'border-sky-500' }, { key: 'radiology_active', label: 'أشعة نشطة', href: '/admin/orders?kind=radiology', accent: 'border-violet-500' }, { key: 'nursing_active', label: 'تمريض نشط', href: '/admin/orders?kind=nursing', accent: 'border-amber-500' }, { key: 'appointments_today', label: 'مواعيد اليوم', href: '/admin/orders?kind=consultation', accent: 'border-cyan-500' }, { key: 'sos_open', label: 'حالات SOS مفتوحة', href: '/admin/sos-monitor', accent: 'border-rose-600' }, { key: 'tickets_open', label: 'تذاكر دعم مفتوحة', href: '/admin/support-tickets', accent: 'border-orange-500' }, { key: 'revenue_24h_sar', label: 'إيراد 24 ساعة (ر.س)', href: '/admin/finance-suite', accent: 'border-emerald-500' }, { key: 'payments_24h', label: 'دفعات 24 ساعة', href: '/admin/finance-suite', accent: 'border-indigo-500' }, { key: 'sla_breach_total', label: 'تجاوزات SLA', href: '/admin/orders?status=sla_breached', accent: 'border-rose-500' },
];

export default function CommandCenterPage() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [streamState, setStreamState] = useState<'connecting' | 'live' | 'offline'>('connecting'); const eventSource = useRef<EventSource | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setSnapshot(await adminFetch<Snapshot>('/command-center-v2')); } catch (cause) { setError(apiErrorMessage(cause, 'تعذر تحميل مركز القيادة.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const source = new EventSource('/api/admin/stream'); eventSource.current = source; source.onopen = () => setStreamState('live'); source.onmessage = (event) => { try { const parsed = JSON.parse(event.data); if (parsed?.tiles) setSnapshot(parsed as Snapshot); } catch { /* ignore heartbeat frames */ } }; source.onerror = () => setStreamState('offline'); return () => { source.close(); eventSource.current = null; }; }, []);
  return <><Head><title>مركز القيادة الحي | نبض</title></Head><section dir="rtl" className="space-y-6 p-6 md:p-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">مركز القيادة الحي</h1><p className="mt-1 text-sm text-slate-500">البلاطات تجمع العدادات الفعلية من Mongo وتتحدث تلقائياً كل 15 ثانية.</p></div><div className={`rounded-full px-3 py-1 text-xs font-bold ${streamState === 'live' ? 'bg-teal-100 text-teal-800' : streamState === 'connecting' ? 'bg-amber-100 text-amber-800' : 'bg-rose-100 text-rose-800'}`}>{streamState === 'live' ? 'تحديث حي متصل' : streamState === 'connecting' ? 'جارٍ الاتصال بالتحديث الحي' : 'التحديث الحي غير متصل'}</div></header>{error ? <p role="alert" className="rounded-lg bg-rose-50 p-3 text-rose-700">{error}</p> : null}<div className="flex justify-between text-xs text-slate-500"><span>آخر لقطة: {snapshot?.ts ? new Date(snapshot.ts).toLocaleString('ar-SA') : '—'}</span><button onClick={() => void load()} className="rounded border px-3 py-1">تحديث فوري</button></div>{loading ? <p className="rounded-2xl border bg-white p-10 text-center text-slate-500">جارٍ تحميل اللقطة التشغيلية…</p> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{tileInfo.map((tile) => { const content = <article className={`rounded-2xl border-r-4 ${tile.accent} bg-white p-5 shadow-sm transition hover:-translate-y-0.5`}><p className="text-sm text-slate-500">{tile.label}</p><p className="mt-3 text-3xl font-bold">{snapshot?.tiles[tile.key] ?? 0}</p></article>; return tile.href ? <Link href={tile.href} key={tile.key}>{content}</Link> : <div key={tile.key}>{content}</div>; })}</div>}<article className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">مسارات المتابعة السريعة</h2><div className="mt-4 flex flex-wrap gap-3"><Link href="/admin/orders" className="rounded-lg border px-4 py-2 text-sm">إدارة دورة الطلبات</Link><Link href="/admin/finance-suite" className="rounded-lg border px-4 py-2 text-sm">التسوية والدفعات</Link><Link href="/admin/system-ops" className="rounded-lg border px-4 py-2 text-sm">الطوابير والتشغيل</Link><Link href="/admin/disputes" className="rounded-lg border px-4 py-2 text-sm">النزاعات المالية</Link></div></article></section></>;
}
