import Link from "next/link";
import { MessageCircle } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import { requirePatientAccess } from "@/lib/auth/session";
import { isLocale } from "@/lib/i18n";
import { callPatientApi } from "@/lib/api/upstream";
import { extractPatientPharmacyMessages } from "@/lib/api/pharmacy-negotiation";
import { NegotiationActions } from "../actions";
import styles from "../../offers.module.css";

type Props = { params: Promise<{ locale: string; orderId: string; threadId: string }> };
export default async function PharmacyNegotiationThreadPage({ params }: Props) { const { locale, orderId, threadId } = await params; if (!isLocale(locale) || !/^[0-9a-f-]{36}$/i.test(orderId) || !/^[0-9a-f-]{36}$/i.test(threadId)) notFound(); setRequestLocale(locale); const ar = locale === "ar"; const token = await requirePatientAccess(locale); const response = await callPatientApi(`/pharmacy/chat/threads/${threadId}/messages`, {}, token); if (response.status === 401) redirect(`/${locale}/login`); if ([403, 404].includes(response.status)) notFound(); const messages = response.ok ? extractPatientPharmacyMessages(await response.json().catch(() => null)) : []; const labels = ar ? { send: "إرسال الرسالة", accept: "قبول البديل بانتظار السعر النهائي", reject: "رفض البديل", remove: "طلب حذف البند", loading: "جارٍ تسجيل القرار…", error: "تعذر تنفيذ الإجراء. لم يتغير السعر أو الدفع.", success: "سُجل القرار بانتظار سعر نهائي جديد من الصيدلية." } : { send: "Send message", accept: "Accept substitute pending final quote", reject: "Reject substitute", remove: "Request item removal", loading: "Recording decision…", error: "The action could not be completed. No price or payment changed.", success: "The decision was recorded pending a revised pharmacy final quote." }; return <main className={`main ${styles.page}`}><Link className={styles.back} href={`/${locale}/orders/${orderId}/offers/negotiation`}>{ar ? "العودة إلى المحادثات" : "Back to conversations"}</Link><header className={styles.hero}><span className={styles.icon}><MessageCircle aria-hidden="true" /></span><div><p>{ar ? "تفاوض البديل" : "Substitute negotiation"}</p><h1>{ar ? "محادثة الصيدلية" : "Pharmacy conversation"}</h1><span>{ar ? "كل قبول أو رفض ينتظر عرضاً نهائياً جديداً من الصيدلية." : "Every accept or rejection awaits a revised final quote from the pharmacy."}</span></div></header><section className={styles.messages}>{messages.length ? messages.map((message) => <article className={styles.message} key={message.id}><strong>{message.senderRole ?? "—"}</strong><p>{message.text ?? "—"}</p>{message.substitute && <aside><b>{ar ? "بديل مقترح" : "Suggested substitute"}</b><span>{message.substitute.name ?? message.substitute.sku ?? "—"}{message.substitute.price !== undefined ? ` · ${message.substitute.price} SAR` : ""}{message.substitute.notes ? ` · ${message.substitute.notes}` : ""}</span></aside>}</article>) : <section className={styles.state}><p>{ar ? "لا توجد رسائل ظاهرة." : "No messages are available."}</p></section>}</section><NegotiationActions threadId={threadId} messages={messages} labels={labels} /></main>; }
