#!/usr/bin/env python3
from pathlib import Path
import hashlib
R=Path(__file__).resolve().parents[3];T=R/'audit-artifacts/gap-closure-audit/PATIENT_WEB_TO_MOBILE_PARITY_REGISTER_2026-08-26.tsv';W=R/'audit-work/source/nabd-patient-web';E='audit-artifacts/gap-closure-audit/patient-web-manual-evidence/FINAL_ONBOARDING_DIAGNOSTICS_HEALTH_ROOT_MANUAL_REVIEW_2026-08-26.md'
def partial(path,route,lines,note):
 p=W/path
 return {'web_source_path':path,'web_route_candidate':route,'web_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'web_line_count':str(len(p.read_text().splitlines())),'web_action_signal_lines':lines,'mapping_status':'MANUAL_MAPPING_COMPLETE__STATIC_MATCHED_PARTIAL','mapping_note':note+' Evidence: '+E,'visual_parity_status':'NOT_REVIEWED__SOURCE_ONLY','cta_parity_status':'STATIC_MATCHED_PARTIAL','scenario_parity_status':'MISSING_CAPABILITY','contract_parity_status':'INSUFFICIENT_EVIDENCE','approved_exception_reason':'NONE'}
def missing(note):return {'web_source_path':'NONE__FINAL_ROUTE_TREE_AND_CTA_SCAN','web_route_candidate':'NONE','web_sha256':'NONE','web_line_count':'0','web_action_signal_lines':'NONE','mapping_status':'MANUAL_MAPPING_COMPLETE__MISSING_CAPABILITY','mapping_note':note+' Evidence: '+E,'visual_parity_status':'NOT_REVIEWED__SOURCE_ONLY','cta_parity_status':'MISSING_CAPABILITY','scenario_parity_status':'MISSING_CAPABILITY','contract_parity_status':'INSUFFICIENT_EVIDENCE__NO_WEB_SURFACE','approved_exception_reason':'NONE'}
U={
'PM-010':partial('app/[locale]/page.tsx','/{locale}','10-11','Public landing exists but is not Mobile onboarding state machine.'),'PM-011':missing('No onboarding language surface/control found.'),'PM-012':missing('No onboarding permissions/consent surface found.'),'PM-016':partial('app/[locale]/dashboard/page.tsx','/{locale}/dashboard','45-75','Protected navigation hub exists but does not prove Mobile tab aggregate behavior.'),'PM-019':missing('No general services-directory route/CTA found.'),'PM-029':partial('app/[locale]/articles/bookmarks/page.tsx','/{locale}/articles/bookmarks','12','Protected bookmark list/detail handoff exists but no bookmark mutation/note/share CTA.'),'PM-069':missing('No diagnostic comparison route/CTA found.'),'PM-071':partial('app/[locale]/diagnostics/page.tsx','/{locale}/diagnostics','19-47','Diagnostic booking dashboard exposes state/schedule/report-ready badge only; no result content/download.'),'PM-073':partial('app/[locale]/diagnostics/page.tsx','/{locale}/diagnostics','19-47','Diagnostic booking dashboard exposes read-only states; no order action workflow.'),'PM-074':partial('app/[locale]/diagnostics/packages/[packageId]/page.tsx','/{locale}/diagnostics/packages/{packageId}','12-40','Public package detail is catalog-only with no booking/payment/insurance CTA.'),'PM-076':partial('app/[locale]/diagnostics/page.tsx','/{locale}/diagnostics','19-47','Diagnostic booking dashboard exposes report-ready badge only; no result-history/content/download.'),'PM-099':missing('No health actionable-order surface found.'),'PM-103':missing('No health conditions/allergies management surface found.'),'PM-104':missing('Profile is display-only; no health edit profile mutation surface found.'),'PM-110':missing('No health-ID surface found.'),'PM-113':partial('app/[locale]/health/chronic-medications/page.tsx','/{locale}/health/chronic-medications','12','Read-only chronic medication subset exists; no full medication management/prescribing workflow.'),'PM-114':partial('app/[locale]/prescriptions/page.tsx','/{locale}/prescriptions','13-43','Protected prescription summaries exist but no detail/refill/share/pharmacy handoff CTA.'),'PM-120':missing('No smart-reminder management surface found.'),'PM-125':partial('app/[locale]/page.tsx','/{locale}','10-11','Public landing exists but not authenticated patient home parity.'),'PM-160':partial('app/[locale]/notifications/page.tsx','/{locale}/notifications','14-25','Protected inbox/settings link exists but no mark-read/delete/deep-link action.')}
lines=T.read_text().splitlines();h=lines[0].split('\t');c={x:i for i,x in enumerate(h)};out=[lines[0]];seen=set()
for raw in lines[1:]:
 f=raw.split('\t');id=f[c['screen_id']]
 if id in U:
  for k,v in U[id].items():f[c[k]]=v
  seen.add(id)
 out.append('\t'.join(f))
if set(U)!=seen:raise SystemExit('missing '+str(set(U)-seen))
T.write_text('\n'.join(out)+'\n');print('updated='+','.join(sorted(seen)))
