import Link from "next/link";
import type { Metadata } from "next";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { JsonLd } from "@/components-next/json-ld";
import { PremiumHealthIllustration } from "@/components-next/premium-health-illustration";
import { ArrowUpLeft, LockKeyhole, ShieldCheck, Sparkles } from "lucide-react";
import { isLocale, locales } from "@/lib/i18n";
import { localizedUrl, siteOrigin } from "@/lib/seo";
type Props = { params: Promise<{ locale: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; const t = await getTranslations({ locale, namespace: "Metadata" }); const canonical = localizedUrl(locale); const title = t("portalTitle"); const description = t("publicDescription"); return { title, description, alternates: { canonical, languages: { ...Object.fromEntries(locales.map((supportedLocale) => [supportedLocale, localizedUrl(supportedLocale)])), "x-default": localizedUrl("ar") } }, openGraph: { type: "website", url: canonical, title, description, siteName: t("siteTitle") }, twitter: { card: "summary", title, description }, robots: { index: true, follow: true } }; }
export default async function LandingPage({ params }: Props) { const { locale } = await params; if (!isLocale(locale)) return null; setRequestLocale(locale); const t = await getTranslations("Home"); const metadata = await getTranslations("Metadata"); const url = localizedUrl(locale); return <main className="main premium-landing"><JsonLd data={[{ "@context": "https://schema.org", "@type": "WebSite", name: metadata("siteTitle"), url: siteOrigin(), inLanguage: locale }, { "@context": "https://schema.org", "@type": "MedicalOrganization", name: metadata("siteTitle"), url: siteOrigin() }, { "@context": "https://schema.org", "@type": "MedicalWebPage", name: metadata("portalTitle"), url, inLanguage: locale, isPartOf: { "@type": "WebSite", url: siteOrigin() } }]} /><section className="hero premium-hero"><div className="premium-hero-copy"><div className="eyebrow"><Sparkles size={14} aria-hidden="true" />{t("eyebrow")}</div><h1>{t("title")}</h1><p>{t("body")}</p><div className="hero-actions"><Link className="button button-primary" href={`/${locale}/login`}><ShieldCheck size={18} aria-hidden="true" />{t("signIn")}</Link><Link className="button button-secondary" href={`/${locale}/medicine-catalog`}>{t("medicineCatalog")}<ArrowUpLeft size={17} aria-hidden="true" /></Link></div></div><aside className="trust-card premium-trust-card"><PremiumHealthIllustration /><div className="trust-content"><span className="trust-kicker"><LockKeyhole size={15} aria-hidden="true" />{t("safeguards")}</span><h2>{t("safeguards")}</h2><p>{t("safeBody")}</p><ul className="trust-list"><li><ShieldCheck size={18} aria-hidden="true" />{t("safetyOne")}</li><li><ShieldCheck size={18} aria-hidden="true" />{t("safetyTwo")}</li><li><ShieldCheck size={18} aria-hidden="true" />{t("safetyThree")}</li></ul></div></aside></section></main>; }
