import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, TextInput, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useApp } from '../../src/context/AppContext';
import { darkColors, lightColors } from '../../src/theme/colors';
import { apiFetch } from '../../src/utils/api';
import { buildPatientPharmacyDraft, extractPatientPharmacyOrderId } from '../../src/utils/pharmacy-draft';
import { LocalizedText } from '../../src/components/LocalizedText';
import { showLocalizedAlert } from '../../src/components/LocalizedAlert';

const key = () => `mobile-pharmacy-manual-${Date.now()}-${Math.random().toString(36).slice(2)}`;
export default function ManualPharmacyOrderScreen() {
  const insets = useSafeAreaInsets(); const { isDark, lang } = useApp() as any; const colors = isDark ? darkColors : lightColors; const isRTL = lang === 'ar' || lang === 'ur'; const requestKey = useRef(key());
  const [name, setName] = useState(''); const [details, setDetails] = useState(''); const [address, setAddress] = useState<any>(null); const [loadingAddress, setLoadingAddress] = useState(true); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { let active = true; void (async () => { try { const profile: any = await apiFetch('/users/me/profile'); const addresses = profile?.addresses || []; if (active) setAddress(addresses.find((entry: any) => entry.is_default) || addresses[0] || null); } finally { if (active) setLoadingAddress(false); } })(); return () => { active = false; }; }, []);
  async function submit() { const medicine = name.trim(); if (medicine.length < 3) return; if (!Number.isFinite(Number(address?.lat)) || !Number.isFinite(Number(address?.lng))) return showLocalizedAlert('حدد موقع الاستلام', 'يلزم عنوان ذو موقع حقيقي قبل بث طلب الدواء اليدوي.'); const rawName = details.trim() ? `${medicine} — ${details.trim()}` : medicine; setSubmitting(true); try { const draft = buildPatientPharmacyDraft([{ name: rawName, qty: 1, intake_source: 'manual' }], address); const created: any = await apiFetch('/patient/pharmacy/orders', { method: 'POST', headers: { 'Idempotency-Key': requestKey.current }, body: JSON.stringify(draft) }); const orderId = extractPatientPharmacyOrderId(created); if (!orderId) throw new Error('governed_pharmacy_order_id_missing'); await apiFetch(`/patient/pharmacy/orders/${orderId}/submit`, { method: 'POST', headers: { 'Idempotency-Key': `${requestKey.current}-submit` }, body: JSON.stringify({}) }); router.replace({ pathname: '/pharmacy/broadcast-status', params: { orderId } }); } catch (reason: any) { showLocalizedAlert('تعذر بث الطلب', reason?.message || 'لم يُنشأ طلب مكتمل. أعد المحاولة يدوياً.'); } finally { setSubmitting(false); } }
  return <View style={[styles.container, { backgroundColor: colors.bg, paddingTop: insets.top + 16 }]}><View style={[styles.header, { flexDirection: isRTL ? 'row-reverse' : 'row' }]}><TouchableOpacity onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.s }]}><LocalizedText style={{ color: colors.n, fontFamily: 'MaterialSymbolsRounded', fontSize: 25 }}>{isRTL ? 'arrow_forward' : 'arrow_back'}</LocalizedText></TouchableOpacity><LocalizedText style={[styles.title, { color: colors.n }]}>طلب دواء غير متوفر</LocalizedText><View style={{ width: 44 }} /></View><ScrollView contentContainerStyle={{ padding: 20, gap: 14, paddingBottom: insets.bottom + 28 }}><LocalizedText style={[styles.copy, { color: colors.t2 }]}>اكتب الاسم والتفاصيل ليُبث الطلب إلى الصيدليات. لا تدخل سعراً أو وسيلة دفع، ولا تُرسل صورة محلية غير محفوظة في هذا المسار.</LocalizedText><LocalizedText style={{ color: colors.n, fontFamily: 'Cairo-Bold' }}>اسم الدواء</LocalizedText><TextInput value={name} onChangeText={setName} placeholder="مثال: كونجستال أقراص" placeholderTextColor={colors.t3} style={[styles.input, { backgroundColor: colors.s, borderColor: colors.bd, color: colors.n, textAlign: isRTL ? 'right' : 'left' }]} /><LocalizedText style={{ color: colors.n, fontFamily: 'Cairo-Bold' }}>تفاصيل تساعد الصيدلية (اختياري)</LocalizedText><TextInput value={details} onChangeText={setDetails} multiline placeholder="تركيز الدواء أو الشكل أو ملاحظة" placeholderTextColor={colors.t3} style={[styles.input, styles.details, { backgroundColor: colors.s, borderColor: colors.bd, color: colors.n, textAlign: isRTL ? 'right' : 'left' }]} /><View style={[styles.address, { backgroundColor: colors.s, borderColor: colors.bd }]}><LocalizedText style={{ color: colors.n, fontFamily: 'Cairo-Bold' }}>{loadingAddress ? 'جاري تحميل العنوان…' : address?.label || 'لا يوجد عنوان صالح'}</LocalizedText><LocalizedText style={{ color: colors.t2 }}>{address ? 'يستخدم البث عنوان ملفك الحالي.' : 'أضف عنواناً بموقع حقيقي قبل البث.'}</LocalizedText><TouchableOpacity onPress={() => router.push('/shared/location-picker')}><LocalizedText style={{ color: colors.p, fontFamily: 'Cairo-Bold' }}>تغيير الموقع</LocalizedText></TouchableOpacity></View><TouchableOpacity disabled={submitting || loadingAddress || name.trim().length < 3} onPress={() => void submit()} style={[styles.submit, { backgroundColor: submitting || loadingAddress || name.trim().length < 3 ? colors.bd : colors.p }]}>{submitting ? <ActivityIndicator color="#fff" /> : <LocalizedText style={styles.submitText}>بث الطلب وطلب عروض</LocalizedText>}</TouchableOpacity></ScrollView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1 }, header: { alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingBottom: 16 }, back: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, title: { fontFamily: 'Cairo-Black', fontSize: 18 }, copy: { fontFamily: 'Cairo-Regular', lineHeight: 21, textAlign: 'center' }, input: { borderWidth: 1, borderRadius: 14, padding: 14, fontFamily: 'Cairo-Regular' }, details: { minHeight: 110, textAlignVertical: 'top' }, address: { gap: 5, borderWidth: 1, borderRadius: 14, padding: 14 }, submit: { minWidth: '100%', alignItems: 'center', borderRadius: 14, paddingVertical: 16 }, submitText: { color: '#fff', fontFamily: 'Cairo-Bold' } });
