// @ts-nocheck
import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useApp } from '../../src/context/AppContext';
import { apiFetch } from '../../src/utils/api';
import { lightColors, darkColors } from '../../src/theme/colors';
import { LocalizedText } from '../../src/components/LocalizedText';
import { dateLocale } from '@/utils/dates';

const labels: Record<string, string> = { CART_DRAFT: 'مسودة', ORDER_BROADCASTING: 'قيد بث العروض', OFFERS_READY: 'العروض جاهزة', OFFER_SELECTED: 'بانتظار السعر النهائي', FINAL_QUOTE_READY: 'السعر النهائي جاهز', FINAL_QUOTE_ACCEPTED: 'بانتظار الدفع', INSURANCE_PROCESSING: 'قيد معالجة التأمين', INSURANCE_DECISION_READY: 'قرار التأمين جاهز', CO_PAY_PENDING: 'بانتظار نسبة التحمل', COD_REGISTERED: 'الدفع عند الاستلام مسجل', CONFIRMED: 'مؤكد', CANCELLED: 'ملغي' };
function destination(order: any) { const id = order.id; const state = order.governed_state; if (['ORDER_BROADCASTING', 'OFFERS_READY'].includes(state)) return { pathname: '/pharmacy/broadcast-status', params: { orderId: id } }; if (['OFFER_SELECTED', 'FINAL_QUOTE_READY', 'FINAL_QUOTE_ACCEPTED', 'COD_REGISTERED'].includes(state)) return { pathname: '/pharmacy/final-quote', params: { orderId: id } }; if (['INSURANCE_PROCESSING', 'INSURANCE_DECISION_READY', 'CO_PAY_PENDING'].includes(state)) return { pathname: '/pharmacy/insurance-decision', params: { orderId: id } }; return { pathname: '/pharmacy/order-tracking', params: { orderId: id } }; }
export default function PharmacyOrderHistoryScreen() {
  const insets = useSafeAreaInsets(); const { isDark, lang } = useApp() as any; const colors = isDark ? darkColors : lightColors; const isRTL = lang === 'ar' || lang === 'ur'; const [orders, setOrders] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async (manual = false) => { manual ? setRefreshing(true) : setLoading(true); setError(''); try { const response: any = await apiFetch('/patient/pharmacy/orders'); const list = response?.data || response; setOrders(Array.isArray(list) ? list : []); } catch (reason: any) { setOrders([]); setError(reason?.message || 'تعذر تحميل سجل الطلبات'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <View style={[styles.container, { backgroundColor: colors.bg }]}><View style={[styles.header, { paddingTop: insets.top + 12, flexDirection: isRTL ? 'row-reverse' : 'row' }]}><TouchableOpacity onPress={() => router.back()} style={styles.back}><LocalizedText style={{ color: colors.n, fontFamily: 'MaterialSymbolsRounded', fontSize: 27 }}>{isRTL ? 'arrow_forward' : 'arrow_back'}</LocalizedText></TouchableOpacity><LocalizedText style={[styles.title, { color: colors.n }]}>سجل طلبات الصيدلية</LocalizedText><View style={{ width: 40 }} /></View><FlatList data={orders} keyExtractor={(order) => order.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.p} />} contentContainerStyle={{ padding: 20, gap: 12, paddingBottom: insets.bottom + 30, flexGrow: 1 }} ListEmptyComponent={loading ? <ActivityIndicator color={colors.p} /> : <View style={styles.empty}><LocalizedText style={{ color: error ? colors.cr : colors.t2, textAlign: 'center' }}>{error || 'لا توجد طلبات صيدلية بعد.'}</LocalizedText>{error && <TouchableOpacity onPress={() => void load(true)} style={[styles.retry, { backgroundColor: colors.p }]}><LocalizedText style={styles.retryText}>تحديث يدوياً</LocalizedText></TouchableOpacity>}</View>} renderItem={({ item }) => <TouchableOpacity onPress={() => router.push(destination(item))} style={[styles.card, { backgroundColor: colors.s, borderColor: colors.bd }]}><View style={[styles.row, { flexDirection: isRTL ? 'row-reverse' : 'row' }]}><LocalizedText style={{ color: colors.n, fontFamily: 'Cairo-Bold' }}>طلب #{String(item.id).slice(-6).toUpperCase()}</LocalizedText><LocalizedText style={{ color: colors.p, fontFamily: 'Cairo-Bold' }}>{labels[item.governed_state] || item.governed_state || 'الحالة غير متاحة'}</LocalizedText></View><LocalizedText style={{ color: colors.t2 }}>{Array.isArray(item.items) ? item.items.map((line: any) => `${line.raw_name || line.name_ar || 'صنف'} × ${line.qty || 1}`).join(' • ') : 'تفاصيل الأصناف من الخادم'}</LocalizedText><LocalizedText style={{ color: colors.t3, fontSize: 12 }}>{item.createdAt ? new Date(item.createdAt).toLocaleDateString(dateLocale()) : ''}</LocalizedText></TouchableOpacity>} /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1 }, header: { alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingBottom: 16 }, back: { width: 40, alignItems: 'center' }, title: { fontFamily: 'Cairo-Black', fontSize: 18 }, card: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 8 }, row: { alignItems: 'center', justifyContent: 'space-between', gap: 12 }, empty: { flex: 1, gap: 14, justifyContent: 'center', alignItems: 'center' }, retry: { borderRadius: 12, paddingHorizontal: 18, paddingVertical: 11 }, retryText: { color: '#fff', fontFamily: 'Cairo-Bold' } });
