// @ts-nocheck
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useApp } from '../../src/context/AppContext';
import { apiFetch } from '../../src/utils/api';
import { buildPatientPharmacyDraft, extractPatientPharmacyOrderId } from '../../src/utils/pharmacy-draft';
import { lightColors, darkColors } from '../../src/theme/colors';
import { LocalizedText } from '../../src/components/LocalizedText';

const key = () => `mobile-pharmacy-reorder-${Date.now()}-${Math.random().toString(36).slice(2)}`;
export default function PharmacyReorderScreen() {
  const insets = useSafeAreaInsets(); const { isDark } = useApp() as any; const colors = isDark ? darkColors : lightColors; const { orderId } = useLocalSearchParams<{ orderId: string }>(); const id = Array.isArray(orderId) ? orderId[0] : orderId; const requestKey = useRef(key());
  const [items, setItems] = useState<any[]>([]); const [address, setAddress] = useState<any>(null); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!id) { setLoading(false); return; } setLoading(true); setError(''); try { const [orderResponse, profileResponse]: any = await Promise.all([apiFetch(`/patient/pharmacy/orders/${id}`), apiFetch('/users/me/profile')]); const order = orderResponse?.data || orderResponse; const addresses = profileResponse?.addresses || []; setAddress(addresses.find((entry: any) => entry.is_default) || addresses[0] || null); setItems((order?.items || []).map((item: any) => ({ id: item.matched_sku || item.id, sku: item.matched_sku, name: item.raw_name || item.name_ar || item.name_en, qty: Math.max(1, Number(item.qty) || 1), selected: true }))); } catch (reason: any) { setError(reason?.message || 'تعذر تحميل طلبك السابق'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const selected = items.filter((item) => item.selected && item.name); function toggle(itemId: string) { setItems((current) => current.map((item) => item.id === itemId ? { ...item, selected: !item.selected } : item)); } function adjust(itemId: string, delta: number) { setItems((current) => current.map((item) => item.id === itemId ? { ...item, qty: Math.max(1, item.qty + delta) } : item)); }
  async function submit() { if (!selected.length) return setError('اختر صنفاً واحداً على الأقل.'); if (!Number.isFinite(Number(address?.lat)) || !Number.isFinite(Number(address?.lng))) return setError('حدّث عنوانك إلى موقع حقيقي قبل إعادة البث.'); setSubmitting(true); setError(''); try { const created: any = await apiFetch('/patient/pharmacy/orders', { method: 'POST', headers: { 'Idempotency-Key': requestKey.current }, body: JSON.stringify(buildPatientPharmacyDraft(selected, address)) }); const nextId = extractPatientPharmacyOrderId(created); if (!nextId) throw new Error('governed_pharmacy_order_id_missing'); await apiFetch(`/patient/pharmacy/orders/${nextId}/submit`, { method: 'POST', headers: { 'Idempotency-Key': `${requestKey.current}-submit` }, body: JSON.stringify({}) }); router.replace({ pathname: '/pharmacy/broadcast-status', params: { orderId: nextId } }); } catch (reason: any) { setError(reason?.message || 'تعذر بث إعادة الطلب.'); } finally { setSubmitting(false); } }
  return <View style={[styles.container, { backgroundColor: colors.bg, paddingTop: insets.top + 16 }]}><View style={styles.header}><TouchableOpacity onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.s }]}><LocalizedText style={{ fontFamily: 'MaterialSymbolsRounded', color: colors.n, fontSize: 25 }}>arrow_forward</LocalizedText></TouchableOpacity><LocalizedText style={[styles.title, { color: colors.n }]}>إعادة طلب الصيدلية</LocalizedText><View style={{ width: 44 }} /></View><ScrollView contentContainerStyle={{ padding: 20, gap: 12, paddingBottom: insets.bottom + 28 }}>{loading ? <ActivityIndicator color={colors.p} /> : error && !items.length ? <><LocalizedText style={{ color: colors.cr, textAlign: 'center' }}>{error}</LocalizedText><TouchableOpacity onPress={() => void load()} style={[styles.primary, { backgroundColor: colors.p }]}><LocalizedText style={styles.primaryText}>تحديث يدوياً</LocalizedText></TouchableOpacity></> : <><LocalizedText style={[styles.copy, { color: colors.t2 }]}>ستنشئ إعادة الطلب draft جديداً وتطلب عروضاً حديثة. لا تُعاد الأسعار أو وسيلة الدفع أو التأمين السابق.</LocalizedText>{items.map((item) => <View key={item.id} style={[styles.card, { backgroundColor: colors.s, borderColor: colors.bd }]}><TouchableOpacity onPress={() => toggle(item.id)} style={styles.line}><LocalizedText style={{ color: item.selected ? colors.p : colors.t2, fontFamily: 'MaterialSymbolsRounded', fontSize: 24 }}>{item.selected ? 'check_circle' : 'radio_button_unchecked'}</LocalizedText><LocalizedText style={{ color: colors.n, fontFamily: 'Cairo-Bold', flex: 1, textAlign: 'right' }}>{item.name}</LocalizedText></TouchableOpacity>{item.selected && <View style={styles.line}><TouchableOpacity onPress={() => adjust(item.id, -1)} style={[styles.qty, { backgroundColor: colors.bg }]}><LocalizedText style={{ color: colors.p, fontFamily: 'MaterialSymbolsRounded' }}>remove</LocalizedText></TouchableOpacity><LocalizedText style={{ color: colors.n, fontFamily: 'Cairo-Bold' }}>الكمية: {item.qty}</LocalizedText><TouchableOpacity onPress={() => adjust(item.id, 1)} style={[styles.qty, { backgroundColor: colors.bg }]}><LocalizedText style={{ color: colors.p, fontFamily: 'MaterialSymbolsRounded' }}>add</LocalizedText></TouchableOpacity></View>}</View>)}<LocalizedText style={{ color: colors.t2, textAlign: 'center' }}>{address ? `سيُستخدم عنوان ملفك الحالي: ${address.label || address.city || 'عنوان محفوظ'}` : 'يلزم عنوان محفوظ بموقع حقيقي قبل البث.'}</LocalizedText>{error && <LocalizedText style={{ color: colors.cr, textAlign: 'center' }}>{error}</LocalizedText>}<TouchableOpacity disabled={submitting || !selected.length} onPress={() => void submit()} style={[styles.primary, { backgroundColor: submitting || !selected.length ? colors.bd : colors.p }]}>{submitting ? <ActivityIndicator color="#fff" /> : <LocalizedText style={styles.primaryText}>إنشاء طلب جديد وطلب عروض</LocalizedText>}</TouchableOpacity></>}</ScrollView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1 }, header: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingBottom: 16 }, back: { width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' }, title: { fontFamily: 'Cairo-Black', fontSize: 18 }, copy: { fontFamily: 'Cairo-Regular', lineHeight: 20, textAlign: 'center' }, card: { gap: 12, padding: 15, borderWidth: 1, borderRadius: 16 }, line: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12 }, qty: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, primary: { minWidth: '100%', alignItems: 'center', borderRadius: 14, paddingVertical: 15, marginTop: 6 }, primaryText: { color: '#fff', fontFamily: 'Cairo-Bold' } });
