import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useApp } from '../../src/context/AppContext';
import { apiFetch } from '../../src/utils/api';
import { mapPrescriptionToPharmacyDraftLines } from '../../src/utils/pharmacy-prescription';
import { lightColors, darkColors } from '../../src/theme/colors';
import { LocalizedText } from '../../src/components/LocalizedText';

export default function PharmacyPrescriptionOrderScreen() {
  const insets = useSafeAreaInsets(); const { isDark } = useApp() as any; const colors = isDark ? darkColors : lightColors; const { prescriptionId } = useLocalSearchParams<{ prescriptionId?: string }>(); const requestedId = Array.isArray(prescriptionId) ? prescriptionId[0] : prescriptionId;
  const [prescription, setPrescription] = useState<any>(null); const [active, setActive] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { if (requestedId) { const response: any = await apiFetch(`/prescriptions/${requestedId}`); setPrescription(response?.data || response); setActive([]); } else { const response: any = await apiFetch('/prescriptions/active'); const list = response?.data || response; setActive(Array.isArray(list) ? list : []); setPrescription(null); } } catch (reason: any) { setError(reason?.message || 'تعذر تحميل الوصفة'); } finally { setLoading(false); } }, [requestedId]);
  useEffect(() => { void load(); }, [load]); const lines = mapPrescriptionToPharmacyDraftLines(prescription || {});
  return <View style={[styles.container, { backgroundColor: colors.bg, paddingTop: insets.top + 16 }]}><View style={styles.header}><TouchableOpacity onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.s }]}><LocalizedText style={{ fontFamily: 'MaterialSymbolsRounded', color: colors.n, fontSize: 25 }}>arrow_forward</LocalizedText></TouchableOpacity><LocalizedText style={[styles.title, { color: colors.n }]}>طلب أدوية الوصفة</LocalizedText><View style={{ width: 44 }} /></View><ScrollView contentContainerStyle={{ padding: 20, gap: 12, paddingBottom: insets.bottom + 28 }}>{loading ? <ActivityIndicator color={colors.p} /> : error ? <><LocalizedText style={{ color: colors.cr, textAlign: 'center' }}>{error}</LocalizedText><TouchableOpacity onPress={() => void load()} style={[styles.primary, { backgroundColor: colors.p }]}><LocalizedText style={styles.primaryText}>تحديث يدوياً</LocalizedText></TouchableOpacity></> : prescription ? <><LocalizedText style={[styles.copy, { color: colors.t2 }]}>تُرسل هذه الوصفة المحفوظة إلى الصيدليات كمرجع طبي. لا يظهر أو يُرسل سعر أو وسيلة دفع قبل اختيار عرض وسعر نهائي.</LocalizedText>{lines.map((line) => <View key={line.id} style={[styles.card, { backgroundColor: colors.s, borderColor: colors.bd }]}><LocalizedText style={{ color: colors.n, fontFamily: 'Cairo-Bold' }}>{line.name}</LocalizedText><LocalizedText style={{ color: colors.t2 }}>الكمية: {line.qty}</LocalizedText></View>)}{!lines.length && <LocalizedText style={{ color: colors.cr, textAlign: 'center' }}>لا توجد أصناف قابلة للطلب في هذه الوصفة.</LocalizedText>}{Boolean(lines.length) && <TouchableOpacity onPress={() => router.replace({ pathname: '/pharmacy/checkout', params: { prescriptionId: String(prescription.id) } })} style={[styles.primary, { backgroundColor: colors.p }]}><LocalizedText style={styles.primaryText}>مراجعة العنوان وطلب عروض</LocalizedText></TouchableOpacity>}</> : <><LocalizedText style={[styles.copy, { color: colors.t2 }]}>اختر وصفة نشطة لبدء طلب جديد. لا يعاد استخدام سعر أو دفع من أي طلب سابق.</LocalizedText>{active.map((rx) => <TouchableOpacity key={rx.id} onPress={() => router.replace({ pathname: '/pharmacy/rx-order', params: { prescriptionId: String(rx.id) } })} style={[styles.card, { backgroundColor: colors.s, borderColor: colors.bd }]}><LocalizedText style={{ color: colors.n, fontFamily: 'Cairo-Bold' }}>وصفة #{String(rx.id).slice(-6).toUpperCase()}</LocalizedText><LocalizedText style={{ color: colors.t2 }}>{Array.isArray(rx.items) ? `${rx.items.length} أصناف` : 'تفاصيل الوصفة'}</LocalizedText></TouchableOpacity>)}{!active.length && <LocalizedText style={{ color: colors.t2, textAlign: 'center' }}>لا توجد وصفات نشطة قابلة للطلب.</LocalizedText>}</>}</ScrollView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1 }, header: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingBottom: 16 }, back: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, title: { fontFamily: 'Cairo-Black', fontSize: 18 }, copy: { fontFamily: 'Cairo-Regular', lineHeight: 21, textAlign: 'center' }, card: { gap: 6, borderWidth: 1, borderRadius: 16, padding: 15 }, primary: { minWidth: '100%', borderRadius: 14, paddingVertical: 15, alignItems: 'center', marginTop: 4 }, primaryText: { color: '#fff', fontFamily: 'Cairo-Bold' } });
