import React, { useState } from 'react';
import { ActivityIndicator, Image, StyleSheet, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import { useApp } from '../../src/context/AppContext';
import { darkColors, lightColors } from '../../src/theme/colors';
import { apiFetch } from '../../src/utils/api';
import { LocalizedText } from '../../src/components/LocalizedText';
import { showLocalizedAlert } from '../../src/components/LocalizedAlert';

export default function ScanPrescriptionScreen() {
  const insets = useSafeAreaInsets(); const { isDark } = useApp() as any; const colors = isDark ? darkColors : lightColors; const [imageUri, setImageUri] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [statusText, setStatusText] = useState('');
  async function pickImage(camera = false) { try { const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return showLocalizedAlert('الصلاحية مطلوبة', camera ? 'نحتاج إذن الكاميرا لالتقاط الوصفة.' : 'نحتاج إذن الوصول إلى الصور لاختيار الوصفة.'); const result = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'] as any, quality: 0.8, base64: true }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'] as any, quality: 0.8, base64: true }); if (!result.canceled && result.assets?.[0]?.uri) { setImageUri(result.assets[0].uri); await process(result.assets[0].base64 || ''); } } catch (reason: any) { setStatusText(reason?.message || 'تعذر اختيار صورة الوصفة.'); } }
  async function process(base64: string) { if (!base64) return setStatusText('تعذر قراءة صورة الوصفة.'); setLoading(true); setStatusText('جاري حفظ الوصفة للتحقق الصيدلي…'); try { const ocr: any = await apiFetch('/ai/prescription-ocr', { method: 'POST', body: JSON.stringify({ image_base64: `data:image/jpeg;base64,${base64}` }) }); const saved: any = await apiFetch('/prescriptions/upload', { method: 'POST', body: JSON.stringify({ upload_image: `data:image/jpeg;base64,${base64}`, items: Array.isArray(ocr?.items) ? ocr.items : [], notes: 'OCR extraction; requires pharmacy review' }) }); const id = saved?.data?.id || saved?.id; if (!id) throw new Error('تعذر حفظ الوصفة'); setStatusText('تم حفظ الوصفة. راجع الأصناف والعنوان قبل طلب العروض.'); router.replace({ pathname: '/pharmacy/rx-order', params: { prescriptionId: String(id) } }); } catch (reason: any) { setStatusText(reason?.message || 'تعذر حفظ الوصفة أو تحليلها.'); } finally { setLoading(false); } }
  return <View style={[styles.container, { backgroundColor: colors.bg, paddingTop: insets.top + 20 }]}><LocalizedText style={[styles.title, { color: colors.n }]}>مسح وصفة طبية</LocalizedText><LocalizedText style={[styles.copy, { color: colors.t2 }]}>تُحفظ الوصفة أولاً للمراجعة. لا تُضاف أسعار أو طريقة دفع إلى الطلب من هذه الشاشة.</LocalizedText>{imageUri && <Image source={{ uri: imageUri }} style={styles.preview} />}{loading && <ActivityIndicator color={colors.p} />}{Boolean(statusText) && <LocalizedText style={{ color: colors.t2, textAlign: 'center' }}>{statusText}</LocalizedText>}<TouchableOpacity disabled={loading} onPress={() => void pickImage(true)} style={[styles.primary, { backgroundColor: colors.p }]}><LocalizedText style={styles.primaryText}>التقاط صورة</LocalizedText></TouchableOpacity><TouchableOpacity disabled={loading} onPress={() => void pickImage(false)} style={[styles.secondary, { borderColor: colors.p }]}><LocalizedText style={{ color: colors.p, fontFamily: 'Cairo-Bold' }}>اختيار من الصور</LocalizedText></TouchableOpacity></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, alignItems: 'center', gap: 16, paddingHorizontal: 24 }, title: { fontFamily: 'Cairo-Black', fontSize: 22, textAlign: 'center' }, copy: { fontFamily: 'Cairo-Regular', lineHeight: 22, textAlign: 'center' }, preview: { width: '100%', height: 270, resizeMode: 'contain', borderRadius: 16 }, primary: { minWidth: '100%', borderRadius: 14, paddingVertical: 15, alignItems: 'center' }, secondary: { minWidth: '100%', borderWidth: 1, borderRadius: 14, paddingVertical: 15, alignItems: 'center' }, primaryText: { color: '#fff', fontFamily: 'Cairo-Bold' } });
