import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useApp } from '../../src/context/AppContext';
import { lightColors, darkColors } from '../../src/theme/colors';
import { apiFetch } from '../../src/utils/api';
import { LocalizedText } from '../../src/components/LocalizedText';
import { showLocalizedAlert } from '../../src/components/LocalizedAlert';

const key = () => `mobile-pharmacy-cancel-${Date.now()}-${Math.random().toString(36).slice(2)}`;
export default function WaitingForPharmacyScreen() {
  const insets = useSafeAreaInsets(); const { isDark } = useApp() as any; const colors = isDark ? darkColors : lightColors; const { orderId } = useLocalSearchParams<{ orderId: string }>(); const id = Array.isArray(orderId) ? orderId[0] : orderId;
  const [order, setOrder] = useState<any>(null); const [loading, setLoading] = useState(true); const [cancelling, setCancelling] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!id) { setLoading(false); return; } setLoading(true); setError(''); try { const response: any = await apiFetch(`/patient/pharmacy/orders/${id}`); const data = response?.data || response; setOrder(data); if (data?.governed_state === 'OFFERS_READY') router.replace({ pathname: '/pharmacy/broadcast-status', params: { orderId: id } }); } catch (reason: any) { setError(reason?.message || 'تعذر تحميل حالة البث'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const state = order?.governed_state; const canCancel = Boolean(order) && !['CANCELLED', 'DELIVERED', 'COMPLETED'].includes(order?.status);
  function cancel() { if (!id || cancelling || !canCancel) return; showLocalizedAlert('إلغاء الطلب', 'سيُرسل طلب الإلغاء إلى الخادم. لا يغيّر التطبيق الحالة محلياً قبل قبول الاستجابة.', [{ text: 'تراجع', style: 'cancel' }, { text: 'تأكيد الإلغاء', style: 'destructive', onPress: () => void (async () => { setCancelling(true); setError(''); try { await apiFetch(`/patient/pharmacy/orders/${id}/cancel`, { method: 'POST', headers: { 'Idempotency-Key': key() }, body: JSON.stringify({ reason: 'patient_requested' }) }); router.replace('/(tabs)/pharmacy'); } catch (reason: any) { setError(reason?.message || 'تعذر إلغاء الطلب'); } finally { setCancelling(false); } })() }]); }
  const text = state === 'ORDER_BROADCASTING' ? 'تم بث طلبك إلى الصيدليات القريبة المؤهلة. ستظهر العروض عندما يقدمها مزودو الخدمة.' : state === 'OFFERS_READY' ? 'العروض جاهزة للمراجعة.' : state ? `حالة الطلب الحاكمة: ${state}` : 'راجع حالة البث يدوياً للحصول على آخر بيانات الخادم.';
  return <View style={[styles.container, { backgroundColor: colors.bg, paddingTop: insets.top + 20 }]}><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 28 }]}><View style={[styles.icon, { backgroundColor: colors.s, borderColor: colors.bd }]}><LocalizedText style={{ fontFamily: 'MaterialSymbolsRounded', fontSize: 52, color: colors.p }}>local_pharmacy</LocalizedText></View><LocalizedText style={[styles.title, { color: colors.n }]}>انتظار عروض الصيدليات</LocalizedText><LocalizedText style={[styles.copy, { color: colors.t2 }]}>{text}</LocalizedText><View style={[styles.card, { backgroundColor: colors.s, borderColor: colors.bd }]}><LocalizedText style={{ color: colors.n, fontFamily: 'Cairo-Bold', textAlign: 'center' }}>لا توجد متابعة تلقائية داخل التطبيق</LocalizedText><LocalizedText style={{ color: colors.t2, textAlign: 'center', fontFamily: 'Cairo-Regular' }}>تحديث الحالة يتم بطلب يدوي من الخادم. لا يعني البث تخصيصاً أو سعراً أو دفعاً.</LocalizedText></View>{loading ? <ActivityIndicator color={colors.p} /> : error ? <LocalizedText style={{ color: colors.cr, textAlign: 'center' }}>{error}</LocalizedText> : null}<TouchableOpacity disabled={loading} onPress={() => void load()} style={[styles.primary, { backgroundColor: loading ? colors.bd : colors.p }]}><LocalizedText style={styles.primaryText}>تحديث حالة البث يدوياً</LocalizedText></TouchableOpacity>{state === 'OFFERS_READY' && <TouchableOpacity onPress={() => router.replace({ pathname: '/pharmacy/broadcast-status', params: { orderId: id } })} style={[styles.secondary, { borderColor: colors.p }]}><LocalizedText style={{ color: colors.p, fontFamily: 'Cairo-Bold' }}>مراجعة عروض الصيدليات</LocalizedText></TouchableOpacity>}{canCancel && <TouchableOpacity disabled={cancelling} onPress={cancel} style={[styles.cancel, { borderColor: colors.cr }]}>{cancelling ? <ActivityIndicator color={colors.cr} /> : <LocalizedText style={{ color: colors.cr, fontFamily: 'Cairo-Bold' }}>إلغاء الطلب</LocalizedText>}</TouchableOpacity>}</ScrollView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1 }, content: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24, gap: 16 }, icon: { width: 112, height: 112, borderRadius: 34, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, title: { fontFamily: 'Cairo-Black', fontSize: 21, textAlign: 'center' }, copy: { fontFamily: 'Cairo-Regular', fontSize: 14, lineHeight: 23, textAlign: 'center' }, card: { width: '100%', gap: 7, borderWidth: 1, borderRadius: 18, padding: 16 }, primary: { minWidth: '100%', borderRadius: 14, paddingVertical: 16, alignItems: 'center' }, secondary: { minWidth: '100%', borderWidth: 1, borderRadius: 14, paddingVertical: 15, alignItems: 'center' }, cancel: { minWidth: '100%', borderWidth: 1, borderRadius: 14, paddingVertical: 14, alignItems: 'center' }, primaryText: { color: '#fff', fontFamily: 'Cairo-Bold' } });
