"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, LoaderCircle, ShieldCheck } from "lucide-react";
import type { Locale } from "@/lib/i18n";
import styles from "./otp-screen.module.css";

const copy: Record<Locale,{title:string;body:string;code:string;resend:string;wait:string;verify:string;busy:string;invalid:string;failed:string;missing:string;back:string}>={
 ar:{title:"تحقق من رقمك",body:"أدخل الرمز المكوّن من 6 أرقام الذي أرسلناه إليك.",code:"رمز التحقق",resend:"إعادة إرسال الرمز",wait:"إعادة الإرسال خلال",verify:"تأكيد الرمز",busy:"جارٍ التحقق…",invalid:"أدخل رمزاً من 6 أرقام.",failed:"تعذر التحقق من الرمز. لم يتم تسجيل الدخول.",missing:"افتح شاشة OTP من تسجيل الدخول أو التسجيل.",back:"العودة"},
 en:{title:"Verify your account",body:"Enter the 6-digit code we sent to you.",code:"Verification code",resend:"Resend code",wait:"Resend available in",verify:"Verify code",busy:"Verifying…",invalid:"Enter a 6-digit code.",failed:"The code could not be verified. You are not signed in.",missing:"Open OTP from login or registration.",back:"Back"},
 fil:{title:"I-verify ang account",body:"Ilagay ang 6-digit code na ipinadala sa iyo.",code:"Verification code",resend:"Ipadala muli",wait:"Muling ipadala sa",verify:"I-verify",busy:"Vine-verify…",invalid:"Maglagay ng 6-digit code.",failed:"Hindi ma-verify ang code.",missing:"Buksan ang OTP mula sa login o registration.",back:"Bumalik"},
 hi:{title:"खाते का सत्यापन",body:"आपको भेजा गया 6 अंकों का कोड दर्ज करें।",code:"सत्यापन कोड",resend:"कोड फिर भेजें",wait:"फिर भेजने में",verify:"कोड सत्यापित करें",busy:"सत्यापन हो रहा है…",invalid:"6 अंकों का कोड दर्ज करें।",failed:"कोड सत्यापित नहीं हो सका।",missing:"लॉगिन या रजिस्ट्रेशन से OTP खोलें।",back:"वापस"},
 ur:{title:"اکاؤنٹ کی تصدیق",body:"آپ کو بھیجا گیا 6 ہندسوں کا کوڈ درج کریں۔",code:"تصدیقی کوڈ",resend:"کوڈ دوبارہ بھیجیں",wait:"دوبارہ بھیجنے میں",verify:"کوڈ کی تصدیق",busy:"تصدیق جاری ہے…",invalid:"6 ہندسوں کا کوڈ درج کریں۔",failed:"کوڈ کی تصدیق نہیں ہو سکی۔",missing:"لاگ اِن یا رجسٹریشن سے OTP کھولیں۔",back:"واپس"},
 bn:{title:"অ্যাকাউন্ট যাচাই",body:"আপনাকে পাঠানো ৬ সংখ্যার কোডটি লিখুন।",code:"যাচাইকরণ কোড",resend:"কোড আবার পাঠান",wait:"আবার পাঠাতে",verify:"কোড যাচাই করুন",busy:"যাচাই হচ্ছে…",invalid:"৬ সংখ্যার কোড লিখুন।",failed:"কোড যাচাই করা যায়নি।",missing:"লগইন বা রেজিস্ট্রেশন থেকে OTP খুলুন।",back:"ফিরে যান"}
};

export function OtpScreen({ locale }: { locale: Locale }) {
 const t=copy[locale]; const router=useRouter(); const params=useSearchParams(); const identifier=params.get("identifier") ?? ""; const [digits,setDigits]=useState(["","","","","",""]); const [seconds,setSeconds]=useState(60); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(identifier?null:t.missing); const refs=useRef<Array<HTMLInputElement|null>>([]);
 useEffect(()=>{ if(seconds<=0)return; const id=window.setInterval(()=>setSeconds(v=>Math.max(0,v-1)),1000); return()=>window.clearInterval(id); },[seconds]);
 function update(index:number,value:string){const next=value.replace(/\D/g,"").slice(-1);const copyDigits=[...digits];copyDigits[index]=next;setDigits(copyDigits);if(next&&index<5)refs.current[index+1]?.focus();}
 function keyDown(index:number,event:React.KeyboardEvent<HTMLInputElement>){if(event.key==="Backspace"&&!digits[index]&&index>0)refs.current[index-1]?.focus();}
 async function resend(){if(!identifier||seconds>0||busy)return;setError(null);const response=await fetch("/api/auth/otp/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identifier})});if(response.ok)setSeconds(60);else setError(t.failed);}
 async function verify(event:React.FormEvent){event.preventDefault();const code=digits.join("");if(!identifier||code.length!==6){setError(t.invalid);return;}setBusy(true);setError(null);try{const verified=await fetch("/api/auth/otp/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identifier,code})});if(!verified.ok){setError(t.failed);return;}const exchanged=await fetch("/api/auth/session/exchange",{method:"POST"});if(!exchanged.ok){setError(t.failed);return;}router.replace(`/${locale}/dashboard`);}catch{setError(t.failed)}finally{setBusy(false)}}
 return <main className={styles.page} dir={locale === "ar" || locale === "ur" ? "rtl":"ltr"}><section className={styles.card}><button className={styles.back} type="button" onClick={()=>router.back()}><ArrowLeft size={16}/>{t.back}</button><div className={styles.icon}><ShieldCheck size={26}/></div><h1 className={styles.title}>{t.title}</h1><p className={styles.description}>{identifier ? <>{t.body}<br/><strong>{identifier}</strong></> : t.missing}</p><form onSubmit={verify}><fieldset disabled={!identifier||busy}><legend>{t.code}</legend><div className={styles.cells}>{digits.map((digit,index)=><input key={index} ref={el=>{refs.current[index]=el}} value={digit} onChange={e=>update(index,e.target.value)} onKeyDown={e=>keyDown(index,e)} inputMode="numeric" autoComplete={index===0?"one-time-code":"off"} aria-label={`${t.code} ${index+1}`} />)}</div><button className={styles.submit} disabled={busy||digits.join("").length!==6}>{busy?<LoaderCircle className={styles.spinner} size={18}/>:null}{busy?t.busy:t.verify}</button></fieldset></form><button className={styles.resend} type="button" disabled={seconds>0||busy||!identifier} onClick={resend}>{seconds>0?`${t.wait} 00:${String(seconds).padStart(2,"0")}`:t.resend}</button>{error?<p className={styles.error} role="alert">{error}</p>:null}</section></main>;
}
