import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Activity, CalendarDays, ChevronLeft, Moon, ShieldCheck } from "lucide-react";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { getPatientSleepReadings } from "@/lib/api/sleep-server";
import { parseSleepReadings } from "@/lib/api/sleep";
import { requirePatientAccess } from "@/lib/auth/session";
import { isLocale } from "@/lib/i18n";
import { RetryButton } from "@/components-next/retry-button";
import styles from "../health.module.css";
type Props={params:Promise<{locale:string}>};
export default async function SleepPage({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();setRequestLocale(locale);const t=await getTranslations("Sleep");const token=await requirePatientAccess(locale);let response:Response;try{response=await getPatientSleepReadings(token);}catch{return <main className={`main ${styles.page}`}><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;}if(response.status===401)redirect(`/${locale}/login`);if(response.status===403||response.status===404)notFound();if(!response.ok)return <main className={`main ${styles.page}`}><section className={styles.state} role="alert"><h1>{t("unavailableTitle")}</h1><p>{t("unavailable")}</p><RetryButton/></section></main>;const readings=parseSleepReadings(await response.json().catch(()=>null));return <main className={`main ${styles.page}`}><Link className={styles.back} href={`/${locale}/health`}><ChevronLeft size={17} aria-hidden="true"/>{t("back")}</Link><section className={styles.hero}><div><p className={styles.eyebrow}><Moon size={15} aria-hidden="true"/>{t("eyebrow")}</p><h1>{t("title")}</h1></div><span className={styles.heroIcon}><Activity size={27} aria-hidden="true"/></span></section>{readings.length?<section className={styles.grid} aria-label={t("title")}>{readings.map((reading,index)=><article className={styles.card} key={reading.id||`${reading.measuredAt||"reading"}-${index}`}><div className={styles.cardTop}><span>{t("reading")}</span><span className={styles.glyph}><Moon size={18} aria-hidden="true"/></span></div><p className={styles.value}>{reading.score!==undefined?`${reading.score} ${t("score")}`:t("notAvailable")}</p>{reading.durationHours!==undefined?<p className={styles.date}>{t("duration")}: {reading.durationHours} {t("hours")}</p>:null}{reading.measuredAt?<p className={styles.date}><CalendarDays size={14} aria-hidden="true"/>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(reading.measuredAt))}</p>:null}</article>)}</section>:<section className={styles.state}><Moon size={25} aria-hidden="true"/><p>{t("empty")}</p></section>}<p className={styles.notice}><ShieldCheck size={15} aria-hidden="true"/> {t("notice")}</p></main>}
