export interface SeedLocation {
  code: string;
  name_ar: string;
  name_en: string;
  type: 'country' | 'region' | 'city' | 'district' | 'sub_area';
  parent_code?: string | null;
  aliases: string[];
  coordinates?: { lat: number; lng: number };
  coverage?: { pharmacy_delivery: boolean; home_healthcare: boolean; lab_collection: boolean };
  is_active: boolean;
}

export const SAUDI_LOCATIONS_SEED: SeedLocation[] = [
  // Country
  {
    code: 'sa',
    name_ar: 'المملكة العربية السعودية',
    name_en: 'Saudi Arabia',
    type: 'country',
    parent_code: null,
    aliases: ['السعودية', 'المملكة', 'KSA', 'Saudi', 'Saudi Arabia'],
    coordinates: { lat: 24.7136, lng: 46.6753 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },

  // Regions
  {
    code: 'sa-riyadh-region',
    name_ar: 'منطقة الرياض',
    name_en: 'Riyadh Region',
    type: 'region',
    parent_code: 'sa',
    aliases: ['منطقة الرياض', 'الرياض', 'Riyadh Region', 'Riyadh'],
    coordinates: { lat: 24.7136, lng: 46.6753 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-makkah-region',
    name_ar: 'منطقة مكة المكرمة',
    name_en: 'Makkah Region',
    type: 'region',
    parent_code: 'sa',
    aliases: ['منطقة مكة', 'الغربية', 'Makkah Region', 'Western Region'],
    coordinates: { lat: 21.4225, lng: 39.8262 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-eastern-region',
    name_ar: 'المنطقة الشرقية',
    name_en: 'Eastern Province',
    type: 'region',
    parent_code: 'sa',
    aliases: ['الشرقية', 'المنطقة الشرقية', 'Eastern Province', 'Ash Sharqiyah'],
    coordinates: { lat: 26.4207, lng: 50.0888 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-madinah-region',
    name_ar: 'منطقة المدينة المنورة',
    name_en: 'Madinah Region',
    type: 'region',
    parent_code: 'sa',
    aliases: ['المدينة', 'منطقة المدينة', 'Madinah Region', 'Medina'],
    coordinates: { lat: 24.5247, lng: 39.5692 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },

  // Cities
  {
    code: 'sa-riyadh-city',
    name_ar: 'الرياض',
    name_en: 'Riyadh',
    type: 'city',
    parent_code: 'sa-riyadh-region',
    aliases: ['الرياض', 'مدينة الرياض', 'Riyadh', 'Ar Riyadh', 'Riyad'],
    coordinates: { lat: 24.7136, lng: 46.6753 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-jeddah-city',
    name_ar: 'جدة',
    name_en: 'Jeddah',
    type: 'city',
    parent_code: 'sa-makkah-region',
    aliases: ['جدة', 'عروس البحر الأحمر', 'Jeddah', 'Jidda', 'Jedda'],
    coordinates: { lat: 21.5433, lng: 39.1728 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-makkah-city',
    name_ar: 'مكة المكرمة',
    name_en: 'Makkah',
    type: 'city',
    parent_code: 'sa-makkah-region',
    aliases: ['مكة', 'مكة المكرمة', 'العاصمة المقدسة', 'Makkah', 'Mecca'],
    coordinates: { lat: 21.4225, lng: 39.8262 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-dammam-city',
    name_ar: 'الدمام',
    name_en: 'Dammam',
    type: 'city',
    parent_code: 'sa-eastern-region',
    aliases: ['الدمام', 'مدينة الدمام', 'Dammam', 'Ad Dammam'],
    coordinates: { lat: 26.4207, lng: 50.0888 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-khobar-city',
    name_ar: 'الخبر',
    name_en: 'Khobar',
    type: 'city',
    parent_code: 'sa-eastern-region',
    aliases: ['الخبر', 'مدينة الخبر', 'Khobar', 'Al Khobar', 'Al-Khobar'],
    coordinates: { lat: 26.2172, lng: 50.1971 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-madinah-city',
    name_ar: 'المدينة المنورة',
    name_en: 'Madinah',
    type: 'city',
    parent_code: 'sa-madinah-region',
    aliases: ['المدينة المنورة', 'المدينة', 'Madinah', 'Medina', 'Al Madinah'],
    coordinates: { lat: 24.5247, lng: 39.5692 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },

  // Riyadh Districts (Verified)
  {
    code: 'sa-riyadh-olaya',
    name_ar: 'العليا',
    name_en: 'Al Olaya',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['العليا', 'حي العليا', 'olaya', 'al olaya', 'al-olaya', 'وسط الرياض'],
    coordinates: { lat: 24.7142, lng: 46.6859 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-nakheel',
    name_ar: 'النخيل',
    name_en: 'Al Nakheel',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['النخيل', 'حي النخيل', 'nakheel', 'al nakheel', 'al-nakheel', 'شمال الرياض'],
    coordinates: { lat: 24.7762, lng: 46.6378 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-sulaymaniyah',
    name_ar: 'السليمانية',
    name_en: 'Al Sulaymaniyah',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['السليمانية', 'حي السليمانية', 'sulaymaniyah', 'al sulaymaniyah', 'sulaimaniyah'],
    coordinates: { lat: 24.7088, lng: 46.7025 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-malaz',
    name_ar: 'الملز',
    name_en: 'Al Malaz',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['الملز', 'حي الملز', 'malaz', 'al malaz', 'al-malaz', 'وسط الرياض'],
    coordinates: { lat: 24.6653, lng: 46.7329 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-sahafa',
    name_ar: 'الصحافة',
    name_en: 'Al Sahafa',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['الصحافة', 'حي الصحافة', 'sahafa', 'al sahafa', 'al-sahafa', 'شمال الرياض', 'north riyadh'],
    coordinates: { lat: 24.8105, lng: 46.6366 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-yasmin',
    name_ar: 'الياسمين',
    name_en: 'Al Yasmin',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['الياسمين', 'حي الياسمين', 'yasmin', 'al yasmin', 'al-yasmin', 'شمال الرياض', 'north riyadh'],
    coordinates: { lat: 24.8322, lng: 46.6436 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-narjis',
    name_ar: 'النرجس',
    name_en: 'Al Narjis',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['النرجس', 'حي النرجس', 'narjis', 'al narjis', 'al-narjis', 'شمال الرياض', 'north riyadh'],
    coordinates: { lat: 24.8519, lng: 46.6781 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-aqiq',
    name_ar: 'العقيق',
    name_en: 'Al Aqiq',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['العقيق', 'حي العقيق', 'aqiq', 'al aqiq', 'al-aqiq', 'شمال الرياض', 'north riyadh'],
    coordinates: { lat: 24.7749, lng: 46.6212 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-wadi',
    name_ar: 'الوادي',
    name_en: 'Al Wadi',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['الوادي', 'حي الوادي', 'wadi', 'al wadi', 'al-wadi', 'شمال الرياض', 'north riyadh'],
    coordinates: { lat: 24.7936, lng: 46.6853 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-waha',
    name_ar: 'الواحة',
    name_en: 'Al Waha',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['الواحة', 'حي الواحة', 'waha', 'al waha', 'al-waha', 'شرق الرياض'],
    coordinates: { lat: 24.7397, lng: 46.7188 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-riyadh-rawdah',
    name_ar: 'الروضة',
    name_en: 'Al Rawdah',
    type: 'district',
    parent_code: 'sa-riyadh-city',
    aliases: ['الروضة', 'حي الروضة', 'rawdah', 'al rawdah', 'al-rawdah', 'شرق الرياض'],
    coordinates: { lat: 24.7571, lng: 46.7797 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },

  // Jeddah Districts (Verified)
  {
    code: 'sa-jeddah-zahra',
    name_ar: 'الزهراء',
    name_en: 'Al Zahra',
    type: 'district',
    parent_code: 'sa-jeddah-city',
    aliases: ['الزهراء', 'حي الزهراء', 'zahra', 'al zahra', 'al-zahra'],
    coordinates: { lat: 21.5898, lng: 39.1417 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-jeddah-shati',
    name_ar: 'الشاطئ',
    name_en: 'Al Shati',
    type: 'district',
    parent_code: 'sa-jeddah-city',
    aliases: ['الشاطئ', 'حي الشاطئ', 'shati', 'al shati', 'al-shati', 'الكورنيش'],
    coordinates: { lat: 21.6083, lng: 39.1172 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
  {
    code: 'sa-jeddah-salamah',
    name_ar: 'السلامة',
    name_en: 'Al Salamah',
    type: 'district',
    parent_code: 'sa-jeddah-city',
    aliases: ['السلامة', 'حي السلامة', 'salamah', 'al salamah', 'al-salamah'],
    coordinates: { lat: 21.5824, lng: 39.1601 },
    coverage: { pharmacy_delivery: true, home_healthcare: true, lab_collection: true },
    is_active: true,
  },
];
