import { z } from "zod";

const doctorId = z.string().regex(/^[A-Za-z0-9_-]{1,128}$/);
const doctorSchema = z.object({
  id: doctorId.optional().nullable(), _id: doctorId.optional().nullable(),
  name_ar: z.string().max(180).optional().nullable(), name_en: z.string().max(180).optional().nullable(), name: z.string().max(180).optional().nullable(), display_name: z.string().max(180).optional().nullable(),
  degree: z.string().max(120).optional().nullable(), title: z.string().max(120).optional().nullable(),
  specialty_ar: z.string().max(180).optional().nullable(), specialty: z.string().max(180).optional().nullable(),
  rating: z.number().min(0).max(5).optional().nullable(), review_count: z.number().int().nonnegative().optional().nullable(), reviews_count: z.number().int().nonnegative().optional().nullable(),
  consultation_fee: z.number().nonnegative().optional().nullable(), price: z.number().nonnegative().optional().nullable(), average_wait: z.number().nonnegative().optional().nullable(), years_experience: z.number().int().nonnegative().optional().nullable(), experience_years: z.number().int().nonnegative().optional().nullable(),
  offers_online: z.boolean().optional().nullable(), offers_clinic: z.boolean().optional().nullable(), offers_home: z.boolean().optional().nullable(), accepts_insurance: z.boolean().optional().nullable(), facility_name: z.string().max(180).optional().nullable(), clinic_name: z.string().max(180).optional().nullable(), next_available_slot: z.string().max(80).optional().nullable(),
}).strip();
export type DoctorRow = { id: string; name?: string; degree?: string; specialty?: string; rating?: number; reviews?: number; price?: number; waitMinutes?: number; experienceYears?: number; online: boolean; clinic: boolean; home: boolean; acceptsInsurance: boolean; facility?: string; nextSlot?: string };
function rowsFrom(payload: unknown): unknown[] { if (Array.isArray(payload)) return payload; if (payload && typeof payload === "object" && !Array.isArray(payload)) { const root=payload as Record<string,unknown>; for (const key of ["data","items","doctors","results"]) if (Array.isArray(root[key])) return root[key]; } return []; }
export function extractDoctors(payload: unknown): DoctorRow[] { return rowsFrom(payload).flatMap((value) => { const parsed=doctorSchema.safeParse(value); if(!parsed.success) return []; const d=parsed.data; const id=d.id ?? d._id; if(!id) return []; const name=d.name_ar ?? d.name_en ?? d.name ?? d.display_name ?? undefined; const specialty=d.specialty_ar ?? d.specialty ?? undefined; const degree=d.degree ?? d.title ?? undefined; return [{ id, name, degree, specialty, rating:d.rating ?? undefined, reviews:d.review_count ?? d.reviews_count ?? undefined, price:d.consultation_fee ?? d.price ?? undefined, waitMinutes:d.average_wait ?? undefined, experienceYears:d.years_experience ?? d.experience_years ?? undefined, online:Boolean(d.offers_online), clinic:Boolean(d.offers_clinic), home:Boolean(d.offers_home), acceptsInsurance:Boolean(d.accepts_insurance), facility:d.facility_name ?? d.clinic_name ?? undefined, nextSlot:d.next_available_slot ?? undefined }]; }); }
export function doctorQuery(input: { search?: string; specialty?: string; sort?: "rating" | "price" | "wait" }) { const params=new URLSearchParams(); const search=(input.search ?? input.specialty ?? "").trim(); if(search) params.set("search", search.slice(0,100)); if(input.sort) params.set("sort", input.sort); const query=params.toString(); return `/care/doctors${query ? `?${query}` : ""}`; }
export function extractDoctor(payload: unknown): DoctorRow | null { const rows = extractDoctors([payload && typeof payload === "object" && !Array.isArray(payload) && "data" in payload ? (payload as Record<string, unknown>).data : payload]); return rows[0] ?? null; }
export type DoctorSlot = { start: string; end: string; label: string; available: boolean };
export type DoctorSlots = { date: string; serviceType: "clinic" | "video" | "home"; slots: DoctorSlot[]; reason?: string };
export function extractDoctorSlots(payload: unknown): DoctorSlots | null { if (!payload || typeof payload !== "object" || Array.isArray(payload)) return null; const p=payload as Record<string, unknown>; if(typeof p.date!=="string" || !["clinic","video","home"].includes(String(p.service_type))) return null; const slots=Array.isArray(p.slots)?p.slots.flatMap((s)=>{ if(!s||typeof s!=="object") return []; const x=s as Record<string,unknown>; if(typeof x.start!=="string"||typeof x.end!=="string"||typeof x.label!=="string"||typeof x.available!=="boolean") return []; return [{start:x.start,end:x.end,label:x.label,available:x.available}]; }):[]; return {date:p.date,serviceType:p.service_type as DoctorSlots["serviceType"],slots,reason:typeof p.reason==="string"?p.reason:undefined}; }
export function doctorSlotsQuery(input: { id: string; date: string; serviceType: "clinic" | "video" | "home" }) { return `/care/doctors/${encodeURIComponent(input.id)}/slots?date=${encodeURIComponent(input.date)}&service_type=${input.serviceType}`; }
export function parseDoctorId(value: string) { return doctorId.safeParse(value); }
