import { beforeEach, describe, expect, it, vi } from "vitest";
const state = vi.hoisted(() => ({ createPatientPaymentIntent: vi.fn(), cookieStore: { get: vi.fn() } }));
vi.mock("@/lib/api/payments-server", () => ({ createPatientPaymentIntent: state.createPatientPaymentIntent })); vi.mock("next/headers", () => ({ cookies: async () => state.cookieStore }));
import { POST } from "./route";
const id = "33333333-3333-4333-8333-333333333333"; const context = { params: Promise.resolve({ requestId: id }) };
function request(body: unknown = { method: "card" }, headers: HeadersInit = {}) { return new Request("https://web.test", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": "insurance-pay-key-123456", ...headers }, body: JSON.stringify(body) }); }
describe("insurance payment intent BFF", () => {
  beforeEach(() => { state.createPatientPaymentIntent.mockReset(); state.cookieStore.get.mockImplementation((name: string) => name === "nabd_access" ? { value: "server-access" } : undefined); });
  it("requires a valid request id, idempotency key, authenticated session, and a declared online method", async () => { expect((await POST(request(), { params: Promise.resolve({ requestId: "not-a-id" }) })).status).toBe(404); expect((await POST(request({ method: "card" }, { "idempotency-key": "short" }), context)).status).toBe(400); expect((await POST(request({ method: "unsupported" }), context)).status).toBe(400); state.cookieStore.get.mockReturnValue(undefined); expect((await POST(request(), context)).status).toBe(401); });
  it("forwards the selected method only to the insurance payment contract", async () => { state.createPatientPaymentIntent.mockResolvedValue(new Response(JSON.stringify({ id: "44444444-4444-4444-8444-444444444444", status: "pending", amount: 75, currency: "SAR", checkout_url: "https://gateway.test/checkout", client_secret: "private" }), { status: 201 })); const response = await POST(request({ method: "google-pay" }), context); expect(response.status).toBe(201); expect(await response.json()).toEqual({ transactionId: "44444444-4444-4444-8444-444444444444", status: "pending", amount: 75, currency: "SAR", checkoutUrl: "https://gateway.test/checkout" }); expect(state.createPatientPaymentIntent).toHaveBeenCalledWith("server-access", "insurance", id, "insurance-pay-key-123456", "google-pay"); });
  it("does not fabricate a checkout result when the upstream response is malformed", async () => { state.createPatientPaymentIntent.mockResolvedValue(new Response(JSON.stringify({ id: "invalid" }), { status: 201 })); expect((await POST(request(), context)).status).toBe(502); });
});
