import { notFound, redirect } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { CalendarDays, House, ShieldCheck, Stethoscope } from "lucide-react";
import { extractNursingVisits } from "@/lib/api/nursing-visits";
import { getPatientNursingVisits } from "@/lib/api/nursing-visits-server";
import { requirePatientAccess } from "@/lib/auth/session";
import { isLocale } from "@/lib/i18n";
import styles from "./visits.module.css";

type Props={params:Promise<{locale:string}>};
export default async function NursingVisitsPage({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();setRequestLocale(locale);const t=await getTranslations("NursingVisits");const token=await requirePatientAccess(locale);const response=await getPatientNursingVisits(token);if(response.status===401)redirect(`/${locale}/login`);if(response.status===403||response.status===404)notFound();if(!response.ok)return <main className={`main ${styles.page}`}><section className={styles.state} role="alert"><Stethoscope size={28}/><h1>{t("unavailable")}</h1><p>{t("unavailableBody")}</p></section></main>;const visits=extractNursingVisits(await response.json().catch(()=>null));return <main className={`main ${styles.page}`} dir={locale==="ar"||locale==="ur"?"rtl":"ltr"}><section className={styles.hero}><div><p className={styles.eyebrow}><ShieldCheck size={15}/>{t("eyebrow")}</p><h1>{t("title")}</h1><p className={styles.subtitle}>{t("subtitle")}</p></div><span className={styles.heroIcon}><House size={28}/></span></section>{visits.length===0?<section className={styles.state}><CalendarDays size={26}/><h2>{t("empty")}</h2></section>:<section className={styles.grid} aria-label={t("title")}>{visits.map((visit)=><article className={styles.card} key={visit.id}><span className={styles.icon}><Stethoscope size={21}/></span><div><h2>{visit.serviceName||t("visit")}</h2>{visit.providerName?<p>{visit.providerName}</p>:null}{visit.scheduledAt?<p className={styles.meta}><CalendarDays size={14}/>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(visit.scheduledAt))}</p>:null}{visit.status?<span className={styles.status}>{visit.status}</span>:null}</div></article>)}</section>}</main>}
